#!/usr/bin/env python3
"""Build src/data/trip-data.ts from the CSV output of fetch.py.

Since the engine overhaul, chain search runs CLIENT-SIDE (src/lib/engine.ts).
This script ships the raw offers — every price tier, with exact station
coordinates — so the browser engine can compute every possible trip live.
"""
from __future__ import annotations
import csv
import json
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OFFERS_CSV = ROOT / 'data' / 'movacar_offers.csv'
OUT_PATH = ROOT / 'src' / 'data' / 'trip-data.ts'

HOME_CITY_OF = {}
for hc, names in {
    'Bochum': {'Bochum', 'Essen', 'Dormagen', 'Bielefeld', 'Bonn', 'Duisburg',
               'Dortmund', 'Düsseldorf', 'Köln', 'Cologne', 'Münster', 'Aachen'},
    'Hannover': {'Hannover', 'Laatzen', 'Weyhe'},
    'München': {'München', 'Munich', 'Berglern', 'Augsburg', 'Gersthofen', 'Rosenheim'},
    'Marburg': {'Marburg', 'Kassel', 'Frankfurt am Main', 'Mainz'},
}.items():
    for n in names:
        HOME_CITY_OF[n] = hc


def read_offers() -> list[dict]:
    if not OFFERS_CSV.exists():
        return []
    with OFFERS_CSV.open(newline='', encoding='utf-8') as f:
        return list(csv.DictReader(f))


def fnum(v: str | None) -> float | None:
    try:
        return float(v) if v not in (None, '') else None
    except ValueError:
        return None


def build_offer_obj(o: dict) -> dict | None:
    try:
        obj = {
            'offerId': o['offer_id'],
            'originName': o['origin_name'],
            'destName': o['destination_name'],
            'startUtc': o['start_date_utc'],
            'endUtc': o['end_date_utc'],
            'periodHours': int(float(o.get('period_hours') or 72)),
            'distanceKm': float(o.get('distance_km') or 0),
            'freeKm': float(o.get('free_km') or 0),
            'make': o.get('make', ''),
            'model': o.get('model', ''),
            'priceEur': round(float(o.get('price_eur') or 0), 2),
        }
    except (ValueError, KeyError):
        return None
    for key, col in [('originLat', 'origin_lat'), ('originLng', 'origin_lng'),
                     ('destLat', 'dest_lat'), ('destLng', 'dest_lng')]:
        v = fnum(o.get(col))
        if v is not None:
            obj[key] = round(v, 5)
    hc = HOME_CITY_OF.get(o['origin_name'])
    if hc:
        obj['homeCity'] = hc
    return obj


def main() -> None:
    print('→ Reading offers…')
    offers_raw = read_offers()
    offers = [obj for obj in (build_offer_obj(o) for o in offers_raw) if obj]
    eur1 = sum(1 for o in offers if o['priceEur'] <= 1.0)
    print(f'  {len(offers)} offers ({eur1} at €1)')

    generated = datetime.now(timezone.utc).isoformat(timespec='seconds').replace('+00:00', 'Z')
    payload = {
        'meta': {
            'generated': generated,
            'offerCount': len(offers),
            'recommendedCount': 0,  # chains are computed client-side now
        },
        'offers': offers,
        'recommended': [],
    }

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    header = (
        '// AUTO-GENERATED by scripts/build.py — do not edit manually.\n'
        f'// Generated: {generated}\n'
        '// Chain search happens client-side (src/lib/engine.ts); this file\n'
        '// carries the raw offers (all price tiers).\n\n'
        "import type { TripData } from '@/lib/chains';\n\n"
        'export const TRIP_DATA: TripData = '
    )
    body = json.dumps(payload, ensure_ascii=False, indent=2)
    OUT_PATH.write_text(header + body + ' as const;\n', encoding='utf-8')
    print(f'✓ Written to {OUT_PATH}')
    print(f'  offers={len(offers)}')


if __name__ == '__main__':
    main()
