// AUTO-GENERATED by scripts/build.py — do not edit manually.
// Generated: 2026-05-22T12:56:46Z
// Run `npm run refresh` to regenerate.

import type { TripData } from '@/lib/chains';

export const TRIP_DATA: TripData = {
  "meta": {
    "generated": "2026-05-22T12:56:46Z",
    "offerCount": 51,
    "recommendedCount": 61
  },
  "offers": [
    {
      "offerId": "244312",
      "originName": "Marburg",
      "destName": "Wien",
      "startUtc": "2026-05-17T22:00:00Z",
      "endUtc": "2026-05-25T21:59:59Z",
      "periodHours": 72,
      "distanceKm": 826.3,
      "freeKm": 1400.0,
      "make": "FAMILY FINCA",
      "model": "VW Grand California 600 - VW Crafter 2"
    },
    {
      "offerId": "244727",
      "originName": "Mérignac",
      "destName": "Dormagen",
      "startUtc": "2026-05-17T22:00:00Z",
      "endUtc": "2026-05-27T21:59:59Z",
      "periodHours": 72,
      "distanceKm": 1091.9,
      "freeKm": 1400.0,
      "make": "ROAD HOUSE",
      "model": "Westfalia Eliseo C540 - Fiat Ducato 8"
    },
    {
      "offerId": "245064",
      "originName": "Marburg",
      "destName": "Graz",
      "startUtc": "2026-05-17T22:00:00Z",
      "endUtc": "2026-05-25T21:59:59Z",
      "periodHours": 72,
      "distanceKm": 807.8,
      "freeKm": 1400.0,
      "make": "CAMPER CABIN DELUXE",
      "model": "Ford Nugget Plus - Ford Transit Custom V362"
    },
    {
      "offerId": "245850",
      "originName": "Marburg",
      "destName": "Graz",
      "startUtc": "2026-05-17T22:00:00Z",
      "endUtc": "2026-05-25T21:59:59Z",
      "periodHours": 72,
      "distanceKm": 807.8,
      "freeKm": 1400.0,
      "make": "CAMPER CABIN DELUXE",
      "model": "Ford Nugget Plus - Ford Transit Custom V362"
    },
    {
      "offerId": "246509",
      "originName": "Cabriès",
      "destName": "Wangen",
      "startUtc": "2026-05-17T22:00:00Z",
      "endUtc": "2026-05-25T21:59:59Z",
      "periodHours": 72,
      "distanceKm": 877.3,
      "freeKm": 1400.0,
      "make": "TRAVEL HOME",
      "model": "Mercedes Benz Marco Polo - V-Klasse"
    },
    {
      "offerId": "244148",
      "originName": "Nantes",
      "destName": "Frankfurt am Main",
      "startUtc": "2026-05-19T22:00:00Z",
      "endUtc": "2026-05-27T21:59:59Z",
      "periodHours": 72,
      "distanceKm": 955.0,
      "freeKm": 1400.0,
      "make": "CAMPER CASTLE",
      "model": "Fiat Tracer 680DL - Fiat Ducato Serie 2"
    },
    {
      "offerId": "246293",
      "originName": "Castellanza",
      "destName": "Leipzig",
      "startUtc": "2026-05-19T22:00:00Z",
      "endUtc": "2026-05-27T21:59:59Z",
      "periodHours": 72,
      "distanceKm": 883.9,
      "freeKm": 1400.0,
      "make": "SURFER SUITE",
      "model": "VW California Ocean"
    },
    {
      "offerId": "246852",
      "originName": "Hamburg",
      "destName": "Dresden",
      "startUtc": "2026-05-20T04:00:00Z",
      "endUtc": "2026-05-26T21:00:00Z",
      "periodHours": 24,
      "distanceKm": 528.1,
      "freeKm": 1000.0,
      "make": "Citroen",
      "model": "Mooveo Light Tei-70 EB"
    },
    {
      "offerId": "246853",
      "originName": "Hamburg",
      "destName": "Dresden",
      "startUtc": "2026-05-20T04:00:00Z",
      "endUtc": "2026-05-26T21:00:00Z",
      "periodHours": 24,
      "distanceKm": 528.1,
      "freeKm": 1000.0,
      "make": "Citroen",
      "model": "Mooveo Light Tei-70 EB"
    },
    {
      "offerId": "246696",
      "originName": "Nantes",
      "destName": "Bilbao",
      "startUtc": "2026-05-20T04:00:05Z",
      "endUtc": "2026-05-28T21:51:05Z",
      "periodHours": 48,
      "distanceKm": 670.5,
      "freeKm": 960.0,
      "make": "Pilote",
      "model": "G690 GJ or similar"
    },
    {
      "offerId": "246697",
      "originName": "Florence",
      "destName": "Bastia",
      "startUtc": "2026-05-20T04:00:05Z",
      "endUtc": "2026-05-28T21:51:05Z",
      "periodHours": 24,
      "distanceKm": 281.3,
      "freeKm": 480.0,
      "make": "Fiat",
      "model": "Ducato"
    },
    {
      "offerId": "246698",
      "originName": "Florence",
      "destName": "Bastia",
      "startUtc": "2026-05-20T04:00:05Z",
      "endUtc": "2026-05-28T21:51:05Z",
      "periodHours": 24,
      "distanceKm": 281.3,
      "freeKm": 480.0,
      "make": "Fiat",
      "model": "Ducato"
    },
    {
      "offerId": "246705",
      "originName": "Nantes",
      "destName": "Madrid",
      "startUtc": "2026-05-20T04:00:05Z",
      "endUtc": "2026-05-28T21:51:05Z",
      "periodHours": 72,
      "distanceKm": 1024.4,
      "freeKm": 1380.0,
      "make": "Pilote",
      "model": "G690 GJ or similar"
    },
    {
      "offerId": "246706",
      "originName": "Nantes",
      "destName": "Barcelona",
      "startUtc": "2026-05-20T04:00:05Z",
      "endUtc": "2026-05-28T21:51:05Z",
      "periodHours": 72,
      "distanceKm": 984.8,
      "freeKm": 1150.0,
      "make": "Pilote",
      "model": "G690 GJ or similar"
    },
    {
      "offerId": "246707",
      "originName": "Berglern",
      "destName": "Saint-Mesmes",
      "startUtc": "2026-05-20T04:00:05Z",
      "endUtc": "2026-05-28T21:51:05Z",
      "periodHours": 72,
      "distanceKm": 844.2,
      "freeKm": 1150.0,
      "make": "Fiat",
      "model": "Ducato",
      "homeCity": "München"
    },
    {
      "offerId": "246708",
      "originName": "Berglern",
      "destName": "Saint-Mesmes",
      "startUtc": "2026-05-20T04:00:05Z",
      "endUtc": "2026-05-28T21:51:05Z",
      "periodHours": 72,
      "distanceKm": 844.2,
      "freeKm": 1150.0,
      "make": "Fiat",
      "model": "Ducato",
      "homeCity": "München"
    },
    {
      "offerId": "246709",
      "originName": "Nantes",
      "destName": "Madrid",
      "startUtc": "2026-05-20T04:00:05Z",
      "endUtc": "2026-05-28T21:51:05Z",
      "periodHours": 72,
      "distanceKm": 1024.4,
      "freeKm": 1380.0,
      "make": "Pilote",
      "model": "G690 GJ or similar"
    },
    {
      "offerId": "246710",
      "originName": "Nantes",
      "destName": "Barcelona",
      "startUtc": "2026-05-20T04:00:05Z",
      "endUtc": "2026-05-28T21:51:05Z",
      "periodHours": 72,
      "distanceKm": 984.8,
      "freeKm": 1150.0,
      "make": "Pilote",
      "model": "G690 GJ or similar"
    },
    {
      "offerId": "246711",
      "originName": "Nantes",
      "destName": "Lyon",
      "startUtc": "2026-05-20T04:00:05Z",
      "endUtc": "2026-05-28T21:51:05Z",
      "periodHours": 48,
      "distanceKm": 752.3,
      "freeKm": 960.0,
      "make": "Pilote",
      "model": "G690 GJ or similar"
    },
    {
      "offerId": "246712",
      "originName": "Nantes",
      "destName": "Madrid",
      "startUtc": "2026-05-20T04:00:05Z",
      "endUtc": "2026-05-28T21:51:05Z",
      "periodHours": 72,
      "distanceKm": 1024.4,
      "freeKm": 1380.0,
      "make": "Pilote",
      "model": "G690 GJ or similar"
    },
    {
      "offerId": "246713",
      "originName": "Nantes",
      "destName": "Lyon",
      "startUtc": "2026-05-20T04:00:05Z",
      "endUtc": "2026-05-28T21:51:05Z",
      "periodHours": 48,
      "distanceKm": 752.3,
      "freeKm": 960.0,
      "make": "Pilote",
      "model": "G690 GJ or similar"
    },
    {
      "offerId": "246714",
      "originName": "Florence",
      "destName": "Bastia",
      "startUtc": "2026-05-20T04:00:05Z",
      "endUtc": "2026-05-28T21:51:05Z",
      "periodHours": 24,
      "distanceKm": 281.3,
      "freeKm": 480.0,
      "make": "Fiat",
      "model": "Ducato"
    },
    {
      "offerId": "246716",
      "originName": "Nantes",
      "destName": "Bilbao",
      "startUtc": "2026-05-20T04:00:05Z",
      "endUtc": "2026-05-28T21:51:05Z",
      "periodHours": 48,
      "distanceKm": 670.5,
      "freeKm": 960.0,
      "make": "Pilote",
      "model": "G690 GJ or similar"
    },
    {
      "offerId": "246717",
      "originName": "Nantes",
      "destName": "Barcelona",
      "startUtc": "2026-05-20T04:00:05Z",
      "endUtc": "2026-05-28T21:51:05Z",
      "periodHours": 72,
      "distanceKm": 984.8,
      "freeKm": 1150.0,
      "make": "Pilote",
      "model": "G690 GJ or similar"
    },
    {
      "offerId": "246718",
      "originName": "Nantes",
      "destName": "Barcelona",
      "startUtc": "2026-05-20T04:00:05Z",
      "endUtc": "2026-05-28T21:51:05Z",
      "periodHours": 72,
      "distanceKm": 984.8,
      "freeKm": 1150.0,
      "make": "Pilote",
      "model": "G690 GJ or similar"
    },
    {
      "offerId": "246719",
      "originName": "Nantes",
      "destName": "Barcelona",
      "startUtc": "2026-05-20T04:00:05Z",
      "endUtc": "2026-05-28T21:51:05Z",
      "periodHours": 72,
      "distanceKm": 984.8,
      "freeKm": 1150.0,
      "make": "Pilote",
      "model": "G690 GJ or similar"
    },
    {
      "offerId": "246720",
      "originName": "Nantes",
      "destName": "Barcelona",
      "startUtc": "2026-05-20T04:00:05Z",
      "endUtc": "2026-05-28T21:51:05Z",
      "periodHours": 72,
      "distanceKm": 984.8,
      "freeKm": 1150.0,
      "make": "Pilote",
      "model": "G690 GJ or similar"
    },
    {
      "offerId": "246721",
      "originName": "Berglern",
      "destName": "Saint-Mesmes",
      "startUtc": "2026-05-20T04:00:05Z",
      "endUtc": "2026-05-29T21:51:05Z",
      "periodHours": 72,
      "distanceKm": 844.2,
      "freeKm": 1150.0,
      "make": "Fiat",
      "model": "Ducato",
      "homeCity": "München"
    },
    {
      "offerId": "246731",
      "originName": "Florence",
      "destName": "Lyon",
      "startUtc": "2026-05-20T04:00:05Z",
      "endUtc": "2026-05-29T21:51:05Z",
      "periodHours": 48,
      "distanceKm": 692.1,
      "freeKm": 960.0,
      "make": "Fiat",
      "model": "S 75SL / T 7400 SB or similar"
    },
    {
      "offerId": "246732",
      "originName": "Florence",
      "destName": "Lyon",
      "startUtc": "2026-05-20T04:00:05Z",
      "endUtc": "2026-05-29T21:51:05Z",
      "periodHours": 48,
      "distanceKm": 692.1,
      "freeKm": 960.0,
      "make": "Fiat",
      "model": "S 75SL / T 7400 SB or similar"
    },
    {
      "offerId": "246733",
      "originName": "Florence",
      "destName": "Bastia",
      "startUtc": "2026-05-20T04:00:05Z",
      "endUtc": "2026-05-29T21:51:05Z",
      "periodHours": 24,
      "distanceKm": 281.3,
      "freeKm": 480.0,
      "make": "Fiat",
      "model": "Ducato"
    },
    {
      "offerId": "246734",
      "originName": "Florence",
      "destName": "Lyon",
      "startUtc": "2026-05-20T04:00:05Z",
      "endUtc": "2026-05-29T21:51:05Z",
      "periodHours": 48,
      "distanceKm": 692.1,
      "freeKm": 960.0,
      "make": "Fiat",
      "model": "S 75SL / T 7400 SB or similar"
    },
    {
      "offerId": "246735",
      "originName": "Florence",
      "destName": "Bastia",
      "startUtc": "2026-05-20T04:00:05Z",
      "endUtc": "2026-05-29T21:51:05Z",
      "periodHours": 24,
      "distanceKm": 281.3,
      "freeKm": 480.0,
      "make": "Fiat",
      "model": "Ducato"
    },
    {
      "offerId": "246736",
      "originName": "Nantes",
      "destName": "Madrid",
      "startUtc": "2026-05-20T04:00:05Z",
      "endUtc": "2026-05-30T21:51:05Z",
      "periodHours": 72,
      "distanceKm": 1024.4,
      "freeKm": 1380.0,
      "make": "Pilote",
      "model": "G690 GJ or similar"
    },
    {
      "offerId": "246737",
      "originName": "Nantes",
      "destName": "Madrid",
      "startUtc": "2026-05-20T04:00:05Z",
      "endUtc": "2026-05-30T21:51:05Z",
      "periodHours": 72,
      "distanceKm": 1024.4,
      "freeKm": 1380.0,
      "make": "Pilote",
      "model": "G690 GJ or similar"
    },
    {
      "offerId": "246738",
      "originName": "Nantes",
      "destName": "Madrid",
      "startUtc": "2026-05-20T04:00:05Z",
      "endUtc": "2026-05-30T21:51:05Z",
      "periodHours": 72,
      "distanceKm": 1024.4,
      "freeKm": 1380.0,
      "make": "Pilote",
      "model": "G690 GJ or similar"
    },
    {
      "offerId": "246739",
      "originName": "Nantes",
      "destName": "Madrid",
      "startUtc": "2026-05-20T04:00:05Z",
      "endUtc": "2026-05-30T21:51:05Z",
      "periodHours": 72,
      "distanceKm": 1024.4,
      "freeKm": 1380.0,
      "make": "Pilote",
      "model": "G690 GJ or similar"
    },
    {
      "offerId": "246740",
      "originName": "Nantes",
      "destName": "Barcelona",
      "startUtc": "2026-05-20T04:00:05Z",
      "endUtc": "2026-05-30T21:51:05Z",
      "periodHours": 72,
      "distanceKm": 984.8,
      "freeKm": 1150.0,
      "make": "Pilote",
      "model": "G690 GJ or similar"
    },
    {
      "offerId": "246742",
      "originName": "Berglern",
      "destName": "Saint-Mesmes",
      "startUtc": "2026-05-20T04:00:05Z",
      "endUtc": "2026-05-29T21:51:05Z",
      "periodHours": 72,
      "distanceKm": 844.2,
      "freeKm": 1150.0,
      "make": "Fiat",
      "model": "Ducato",
      "homeCity": "München"
    },
    {
      "offerId": "246743",
      "originName": "Florence",
      "destName": "Lyon",
      "startUtc": "2026-05-20T04:00:05Z",
      "endUtc": "2026-05-29T21:51:05Z",
      "periodHours": 48,
      "distanceKm": 692.1,
      "freeKm": 960.0,
      "make": "Fiat",
      "model": "S 75SL / T 7400 SB or similar"
    },
    {
      "offerId": "246744",
      "originName": "Florence",
      "destName": "Bastia",
      "startUtc": "2026-05-20T04:00:05Z",
      "endUtc": "2026-05-29T21:51:05Z",
      "periodHours": 24,
      "distanceKm": 281.3,
      "freeKm": 480.0,
      "make": "Fiat",
      "model": "Ducato"
    },
    {
      "offerId": "246837",
      "originName": "Weingarten",
      "destName": "Vizzola Ticino",
      "startUtc": "2026-05-20T12:00:27Z",
      "endUtc": "2026-05-22T21:59:00Z",
      "periodHours": 24,
      "distanceKm": 357.6,
      "freeKm": 450.0,
      "make": "AUDI",
      "model": "A6 EST HBD AUT"
    },
    {
      "offerId": "246832",
      "originName": "München",
      "destName": "Landsberg am Lech",
      "startUtc": "2026-05-20T13:21:11Z",
      "endUtc": "2026-05-21T15:00:00Z",
      "periodHours": 24,
      "distanceKm": 89.3,
      "freeKm": 150.0,
      "make": "NISSA",
      "model": "PRIMASTAR MPV 9S DI AUT",
      "homeCity": "München"
    },
    {
      "offerId": "246833",
      "originName": "München",
      "destName": "Landsberg am Lech",
      "startUtc": "2026-05-20T13:21:11Z",
      "endUtc": "2026-05-21T15:00:00Z",
      "periodHours": 24,
      "distanceKm": 89.3,
      "freeKm": 150.0,
      "make": "NISSA",
      "model": "PRIMASTAR MPV 9S DI MAN",
      "homeCity": "München"
    },
    {
      "offerId": "246864",
      "originName": "Lörrach",
      "destName": "Sindelfingen",
      "startUtc": "2026-05-20T15:21:42Z",
      "endUtc": "2026-05-21T14:00:00Z",
      "periodHours": 24,
      "distanceKm": 256.4,
      "freeKm": 350.0,
      "make": "MAN",
      "model": "TGE 3.140 L 3,5 TO KAS DI MAN"
    },
    {
      "offerId": "235595",
      "originName": "Göteborgs Stad",
      "destName": "Marburg",
      "startUtc": "2026-05-20T22:00:00Z",
      "endUtc": "2026-05-28T21:59:59Z",
      "periodHours": 72,
      "distanceKm": 1029.8,
      "freeKm": 1400.0,
      "make": "COUPLE COTTAGE",
      "model": "Weinsberg Signeo C590 - Ford Transit V363"
    },
    {
      "offerId": "236841",
      "originName": "Marburg",
      "destName": "Turin",
      "startUtc": "2026-05-20T22:00:00Z",
      "endUtc": "2026-05-28T21:59:59Z",
      "periodHours": 72,
      "distanceKm": 822.0,
      "freeKm": 1400.0,
      "make": "SURFER SUITE",
      "model": "VW California Ocean"
    },
    {
      "offerId": "237110",
      "originName": "Marburg",
      "destName": "Saint-Jean-de-Gonville",
      "startUtc": "2026-05-20T22:00:00Z",
      "endUtc": "2026-05-28T21:59:59Z",
      "periodHours": 48,
      "distanceKm": 663.4,
      "freeKm": 1000.0,
      "make": "SURFER SUITE",
      "model": "VW California Ocean"
    },
    {
      "offerId": "242741",
      "originName": "Roma",
      "destName": "Turin",
      "startUtc": "2026-05-20T22:00:00Z",
      "endUtc": "2026-05-28T21:59:59Z",
      "periodHours": 48,
      "distanceKm": 669.3,
      "freeKm": 1000.0,
      "make": "BEACH HOSTEL",
      "model": "VW California Beach"
    },
    {
      "offerId": "246301",
      "originName": "Nantes",
      "destName": "Marburg",
      "startUtc": "2026-05-20T22:00:00Z",
      "endUtc": "2026-05-28T21:59:59Z",
      "periodHours": 72,
      "distanceKm": 1045.0,
      "freeKm": 1400.0,
      "make": "ROAD HOUSE",
      "model": "Westfalia Eliseo C540 - Fiat Ducato 8"
    },
    {
      "offerId": "246601",
      "originName": "London",
      "destName": "Edinburgh",
      "startUtc": "2026-05-21T04:00:05Z",
      "endUtc": "2026-06-03T21:51:06Z",
      "periodHours": 48,
      "distanceKm": 681.9,
      "freeKm": 960.0,
      "make": "Pilote",
      "model": "V630J or similar"
    }
  ],
  "recommended": [
    {
      "score": 145.4,
      "route": [
        "Nantes",
        "Marburg",
        "Wien"
      ],
      "legs": [
        {
          "originName": "Nantes",
          "destName": "Marburg",
          "pickup": "2026-05-21T00:00:00+02:00",
          "dropoff": "2026-05-24T00:00:00+02:00",
          "vehicle": "ROAD HOUSE Westfalia Eliseo C540 - Fiat Ducato 8",
          "make": "ROAD HOUSE",
          "model": "Westfalia Eliseo C540 - Fiat Ducato 8",
          "distanceKm": 1045.0,
          "offerId": "246301"
        },
        {
          "originName": "Marburg",
          "destName": "Wien",
          "pickup": "2026-05-23T00:00:00+02:00",
          "dropoff": "2026-05-26T00:00:00+02:00",
          "vehicle": "FAMILY FINCA VW Grand California 600 - VW Crafter 2",
          "make": "FAMILY FINCA",
          "model": "VW Grand California 600 - VW Crafter 2",
          "distanceKm": 826.3,
          "offerId": "244312"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-21T00:00:00+02:00",
      "endUtc": "2026-05-26T00:00:00+02:00",
      "days": 5.0,
      "routeKm": 1871.0,
      "freeKm": 2800.0,
      "spareKm": 929.0,
      "driveHours": 22.011764705882353,
      "countries": [
        "France",
        "Germany",
        "Austria"
      ],
      "appointment": "21 May – 26 May · Nantes → Wien"
    },
    {
      "score": 145.3,
      "route": [
        "Nantes",
        "Marburg",
        "Turin"
      ],
      "legs": [
        {
          "originName": "Nantes",
          "destName": "Marburg",
          "pickup": "2026-05-21T00:00:00+02:00",
          "dropoff": "2026-05-24T00:00:00+02:00",
          "vehicle": "ROAD HOUSE Westfalia Eliseo C540 - Fiat Ducato 8",
          "make": "ROAD HOUSE",
          "model": "Westfalia Eliseo C540 - Fiat Ducato 8",
          "distanceKm": 1045.0,
          "offerId": "246301"
        },
        {
          "originName": "Marburg",
          "destName": "Turin",
          "pickup": "2026-05-23T00:00:00+02:00",
          "dropoff": "2026-05-26T00:00:00+02:00",
          "vehicle": "SURFER SUITE VW California Ocean",
          "make": "SURFER SUITE",
          "model": "VW California Ocean",
          "distanceKm": 822.0,
          "offerId": "236841"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-21T00:00:00+02:00",
      "endUtc": "2026-05-26T00:00:00+02:00",
      "days": 5.0,
      "routeKm": 1867.0,
      "freeKm": 2800.0,
      "spareKm": 933.0,
      "driveHours": 21.96470588235294,
      "countries": [
        "France",
        "Germany",
        "Italy"
      ],
      "appointment": "21 May – 26 May · Nantes → Turin"
    },
    {
      "score": 145.3,
      "route": [
        "Göteborgs Stad",
        "Marburg",
        "Wien"
      ],
      "legs": [
        {
          "originName": "Göteborgs Stad",
          "destName": "Marburg",
          "pickup": "2026-05-21T00:00:00+02:00",
          "dropoff": "2026-05-24T00:00:00+02:00",
          "vehicle": "COUPLE COTTAGE Weinsberg Signeo C590 - Ford Transit V363",
          "make": "COUPLE COTTAGE",
          "model": "Weinsberg Signeo C590 - Ford Transit V363",
          "distanceKm": 1029.8,
          "offerId": "235595"
        },
        {
          "originName": "Marburg",
          "destName": "Wien",
          "pickup": "2026-05-23T00:00:00+02:00",
          "dropoff": "2026-05-26T00:00:00+02:00",
          "vehicle": "FAMILY FINCA VW Grand California 600 - VW Crafter 2",
          "make": "FAMILY FINCA",
          "model": "VW Grand California 600 - VW Crafter 2",
          "distanceKm": 826.3,
          "offerId": "244312"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-21T00:00:00+02:00",
      "endUtc": "2026-05-26T00:00:00+02:00",
      "days": 5.0,
      "routeKm": 1856.0,
      "freeKm": 2800.0,
      "spareKm": 944.0,
      "driveHours": 21.83529411764706,
      "countries": [
        "Sweden",
        "Germany",
        "Austria"
      ],
      "appointment": "21 May – 26 May · Göteborgs Stad → Wien"
    },
    {
      "score": 145.3,
      "route": [
        "Nantes",
        "Marburg",
        "Graz"
      ],
      "legs": [
        {
          "originName": "Nantes",
          "destName": "Marburg",
          "pickup": "2026-05-21T00:00:00+02:00",
          "dropoff": "2026-05-24T00:00:00+02:00",
          "vehicle": "ROAD HOUSE Westfalia Eliseo C540 - Fiat Ducato 8",
          "make": "ROAD HOUSE",
          "model": "Westfalia Eliseo C540 - Fiat Ducato 8",
          "distanceKm": 1045.0,
          "offerId": "246301"
        },
        {
          "originName": "Marburg",
          "destName": "Graz",
          "pickup": "2026-05-23T00:00:00+02:00",
          "dropoff": "2026-05-26T00:00:00+02:00",
          "vehicle": "CAMPER CABIN DELUXE Ford Nugget Plus - Ford Transit Custom V362",
          "make": "CAMPER CABIN DELUXE",
          "model": "Ford Nugget Plus - Ford Transit Custom V362",
          "distanceKm": 807.8,
          "offerId": "245064"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-21T00:00:00+02:00",
      "endUtc": "2026-05-26T00:00:00+02:00",
      "days": 5.0,
      "routeKm": 1853.0,
      "freeKm": 2800.0,
      "spareKm": 947.0,
      "driveHours": 21.8,
      "countries": [
        "France",
        "Germany",
        "Austria"
      ],
      "appointment": "21 May – 26 May · Nantes → Graz"
    },
    {
      "score": 145.3,
      "route": [
        "Nantes",
        "Marburg",
        "Graz"
      ],
      "legs": [
        {
          "originName": "Nantes",
          "destName": "Marburg",
          "pickup": "2026-05-21T00:00:00+02:00",
          "dropoff": "2026-05-24T00:00:00+02:00",
          "vehicle": "ROAD HOUSE Westfalia Eliseo C540 - Fiat Ducato 8",
          "make": "ROAD HOUSE",
          "model": "Westfalia Eliseo C540 - Fiat Ducato 8",
          "distanceKm": 1045.0,
          "offerId": "246301"
        },
        {
          "originName": "Marburg",
          "destName": "Graz",
          "pickup": "2026-05-23T00:00:00+02:00",
          "dropoff": "2026-05-26T00:00:00+02:00",
          "vehicle": "CAMPER CABIN DELUXE Ford Nugget Plus - Ford Transit Custom V362",
          "make": "CAMPER CABIN DELUXE",
          "model": "Ford Nugget Plus - Ford Transit Custom V362",
          "distanceKm": 807.8,
          "offerId": "245850"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-21T00:00:00+02:00",
      "endUtc": "2026-05-26T00:00:00+02:00",
      "days": 5.0,
      "routeKm": 1853.0,
      "freeKm": 2800.0,
      "spareKm": 947.0,
      "driveHours": 21.8,
      "countries": [
        "France",
        "Germany",
        "Austria"
      ],
      "appointment": "21 May – 26 May · Nantes → Graz"
    },
    {
      "score": 145.3,
      "route": [
        "Göteborgs Stad",
        "Marburg",
        "Turin"
      ],
      "legs": [
        {
          "originName": "Göteborgs Stad",
          "destName": "Marburg",
          "pickup": "2026-05-21T00:00:00+02:00",
          "dropoff": "2026-05-24T00:00:00+02:00",
          "vehicle": "COUPLE COTTAGE Weinsberg Signeo C590 - Ford Transit V363",
          "make": "COUPLE COTTAGE",
          "model": "Weinsberg Signeo C590 - Ford Transit V363",
          "distanceKm": 1029.8,
          "offerId": "235595"
        },
        {
          "originName": "Marburg",
          "destName": "Turin",
          "pickup": "2026-05-23T00:00:00+02:00",
          "dropoff": "2026-05-26T00:00:00+02:00",
          "vehicle": "SURFER SUITE VW California Ocean",
          "make": "SURFER SUITE",
          "model": "VW California Ocean",
          "distanceKm": 822.0,
          "offerId": "236841"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-21T00:00:00+02:00",
      "endUtc": "2026-05-26T00:00:00+02:00",
      "days": 5.0,
      "routeKm": 1852.0,
      "freeKm": 2800.0,
      "spareKm": 948.0,
      "driveHours": 21.788235294117648,
      "countries": [
        "Sweden",
        "Germany",
        "Italy"
      ],
      "appointment": "21 May – 26 May · Göteborgs Stad → Turin"
    },
    {
      "score": 145.2,
      "route": [
        "Göteborgs Stad",
        "Marburg",
        "Graz"
      ],
      "legs": [
        {
          "originName": "Göteborgs Stad",
          "destName": "Marburg",
          "pickup": "2026-05-21T00:00:00+02:00",
          "dropoff": "2026-05-24T00:00:00+02:00",
          "vehicle": "COUPLE COTTAGE Weinsberg Signeo C590 - Ford Transit V363",
          "make": "COUPLE COTTAGE",
          "model": "Weinsberg Signeo C590 - Ford Transit V363",
          "distanceKm": 1029.8,
          "offerId": "235595"
        },
        {
          "originName": "Marburg",
          "destName": "Graz",
          "pickup": "2026-05-23T00:00:00+02:00",
          "dropoff": "2026-05-26T00:00:00+02:00",
          "vehicle": "CAMPER CABIN DELUXE Ford Nugget Plus - Ford Transit Custom V362",
          "make": "CAMPER CABIN DELUXE",
          "model": "Ford Nugget Plus - Ford Transit Custom V362",
          "distanceKm": 807.8,
          "offerId": "245064"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-21T00:00:00+02:00",
      "endUtc": "2026-05-26T00:00:00+02:00",
      "days": 5.0,
      "routeKm": 1838.0,
      "freeKm": 2800.0,
      "spareKm": 962.0,
      "driveHours": 21.623529411764707,
      "countries": [
        "Sweden",
        "Germany",
        "Austria"
      ],
      "appointment": "21 May – 26 May · Göteborgs Stad → Graz"
    },
    {
      "score": 145.2,
      "route": [
        "Göteborgs Stad",
        "Marburg",
        "Graz"
      ],
      "legs": [
        {
          "originName": "Göteborgs Stad",
          "destName": "Marburg",
          "pickup": "2026-05-21T00:00:00+02:00",
          "dropoff": "2026-05-24T00:00:00+02:00",
          "vehicle": "COUPLE COTTAGE Weinsberg Signeo C590 - Ford Transit V363",
          "make": "COUPLE COTTAGE",
          "model": "Weinsberg Signeo C590 - Ford Transit V363",
          "distanceKm": 1029.8,
          "offerId": "235595"
        },
        {
          "originName": "Marburg",
          "destName": "Graz",
          "pickup": "2026-05-23T00:00:00+02:00",
          "dropoff": "2026-05-26T00:00:00+02:00",
          "vehicle": "CAMPER CABIN DELUXE Ford Nugget Plus - Ford Transit Custom V362",
          "make": "CAMPER CABIN DELUXE",
          "model": "Ford Nugget Plus - Ford Transit Custom V362",
          "distanceKm": 807.8,
          "offerId": "245850"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-21T00:00:00+02:00",
      "endUtc": "2026-05-26T00:00:00+02:00",
      "days": 5.0,
      "routeKm": 1838.0,
      "freeKm": 2800.0,
      "spareKm": 962.0,
      "driveHours": 21.623529411764707,
      "countries": [
        "Sweden",
        "Germany",
        "Austria"
      ],
      "appointment": "21 May – 26 May · Göteborgs Stad → Graz"
    },
    {
      "score": 144.5,
      "route": [
        "Nantes",
        "Marburg",
        "Saint-Jean-de-Gonville"
      ],
      "legs": [
        {
          "originName": "Nantes",
          "destName": "Marburg",
          "pickup": "2026-05-21T00:00:00+02:00",
          "dropoff": "2026-05-24T00:00:00+02:00",
          "vehicle": "ROAD HOUSE Westfalia Eliseo C540 - Fiat Ducato 8",
          "make": "ROAD HOUSE",
          "model": "Westfalia Eliseo C540 - Fiat Ducato 8",
          "distanceKm": 1045.0,
          "offerId": "246301"
        },
        {
          "originName": "Marburg",
          "destName": "Saint-Jean-de-Gonville",
          "pickup": "2026-05-24T00:00:00+02:00",
          "dropoff": "2026-05-26T00:00:00+02:00",
          "vehicle": "SURFER SUITE VW California Ocean",
          "make": "SURFER SUITE",
          "model": "VW California Ocean",
          "distanceKm": 663.4,
          "offerId": "237110"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-21T00:00:00+02:00",
      "endUtc": "2026-05-26T00:00:00+02:00",
      "days": 5.0,
      "routeKm": 1708.0,
      "freeKm": 2400.0,
      "spareKm": 692.0,
      "driveHours": 20.094117647058823,
      "countries": [
        "France",
        "Germany"
      ],
      "appointment": "21 May – 26 May · Nantes → Saint-Jean-de-Gonville"
    },
    {
      "score": 144.5,
      "route": [
        "Göteborgs Stad",
        "Marburg",
        "Saint-Jean-de-Gonville"
      ],
      "legs": [
        {
          "originName": "Göteborgs Stad",
          "destName": "Marburg",
          "pickup": "2026-05-21T00:00:00+02:00",
          "dropoff": "2026-05-24T00:00:00+02:00",
          "vehicle": "COUPLE COTTAGE Weinsberg Signeo C590 - Ford Transit V363",
          "make": "COUPLE COTTAGE",
          "model": "Weinsberg Signeo C590 - Ford Transit V363",
          "distanceKm": 1029.8,
          "offerId": "235595"
        },
        {
          "originName": "Marburg",
          "destName": "Saint-Jean-de-Gonville",
          "pickup": "2026-05-24T00:00:00+02:00",
          "dropoff": "2026-05-26T00:00:00+02:00",
          "vehicle": "SURFER SUITE VW California Ocean",
          "make": "SURFER SUITE",
          "model": "VW California Ocean",
          "distanceKm": 663.4,
          "offerId": "237110"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-21T00:00:00+02:00",
      "endUtc": "2026-05-26T00:00:00+02:00",
      "days": 5.0,
      "routeKm": 1693.0,
      "freeKm": 2400.0,
      "spareKm": 707.0,
      "driveHours": 19.91764705882353,
      "countries": [
        "Sweden",
        "Germany",
        "France"
      ],
      "appointment": "21 May – 26 May · Göteborgs Stad → Saint-Jean-de-Gonville"
    },
    {
      "score": 129.1,
      "route": [
        "Nantes",
        "Madrid"
      ],
      "legs": [
        {
          "originName": "Nantes",
          "destName": "Madrid",
          "pickup": "2026-05-20T06:00:05+02:00",
          "dropoff": "2026-05-23T06:00:05+02:00",
          "vehicle": "Pilote G690 GJ or similar",
          "make": "Pilote",
          "model": "G690 GJ or similar",
          "distanceKm": 1024.4,
          "offerId": "246705"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-20T06:00:05+02:00",
      "endUtc": "2026-05-23T06:00:05+02:00",
      "days": 3.0,
      "routeKm": 1024.0,
      "freeKm": 1380.0,
      "spareKm": 356.0,
      "driveHours": 12.047058823529412,
      "countries": [
        "France",
        "Spain"
      ],
      "appointment": "20 May – 23 May · Nantes → Madrid"
    },
    {
      "score": 129.1,
      "route": [
        "Nantes",
        "Madrid"
      ],
      "legs": [
        {
          "originName": "Nantes",
          "destName": "Madrid",
          "pickup": "2026-05-20T06:00:05+02:00",
          "dropoff": "2026-05-23T06:00:05+02:00",
          "vehicle": "Pilote G690 GJ or similar",
          "make": "Pilote",
          "model": "G690 GJ or similar",
          "distanceKm": 1024.4,
          "offerId": "246709"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-20T06:00:05+02:00",
      "endUtc": "2026-05-23T06:00:05+02:00",
      "days": 3.0,
      "routeKm": 1024.0,
      "freeKm": 1380.0,
      "spareKm": 356.0,
      "driveHours": 12.047058823529412,
      "countries": [
        "France",
        "Spain"
      ],
      "appointment": "20 May – 23 May · Nantes → Madrid"
    },
    {
      "score": 129.1,
      "route": [
        "Nantes",
        "Madrid"
      ],
      "legs": [
        {
          "originName": "Nantes",
          "destName": "Madrid",
          "pickup": "2026-05-20T06:00:05+02:00",
          "dropoff": "2026-05-23T06:00:05+02:00",
          "vehicle": "Pilote G690 GJ or similar",
          "make": "Pilote",
          "model": "G690 GJ or similar",
          "distanceKm": 1024.4,
          "offerId": "246712"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-20T06:00:05+02:00",
      "endUtc": "2026-05-23T06:00:05+02:00",
      "days": 3.0,
      "routeKm": 1024.0,
      "freeKm": 1380.0,
      "spareKm": 356.0,
      "driveHours": 12.047058823529412,
      "countries": [
        "France",
        "Spain"
      ],
      "appointment": "20 May – 23 May · Nantes → Madrid"
    },
    {
      "score": 129.1,
      "route": [
        "Nantes",
        "Madrid"
      ],
      "legs": [
        {
          "originName": "Nantes",
          "destName": "Madrid",
          "pickup": "2026-05-20T06:00:05+02:00",
          "dropoff": "2026-05-23T06:00:05+02:00",
          "vehicle": "Pilote G690 GJ or similar",
          "make": "Pilote",
          "model": "G690 GJ or similar",
          "distanceKm": 1024.4,
          "offerId": "246736"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-20T06:00:05+02:00",
      "endUtc": "2026-05-23T06:00:05+02:00",
      "days": 3.0,
      "routeKm": 1024.0,
      "freeKm": 1380.0,
      "spareKm": 356.0,
      "driveHours": 12.047058823529412,
      "countries": [
        "France",
        "Spain"
      ],
      "appointment": "20 May – 23 May · Nantes → Madrid"
    },
    {
      "score": 129.1,
      "route": [
        "Nantes",
        "Madrid"
      ],
      "legs": [
        {
          "originName": "Nantes",
          "destName": "Madrid",
          "pickup": "2026-05-20T06:00:05+02:00",
          "dropoff": "2026-05-23T06:00:05+02:00",
          "vehicle": "Pilote G690 GJ or similar",
          "make": "Pilote",
          "model": "G690 GJ or similar",
          "distanceKm": 1024.4,
          "offerId": "246737"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-20T06:00:05+02:00",
      "endUtc": "2026-05-23T06:00:05+02:00",
      "days": 3.0,
      "routeKm": 1024.0,
      "freeKm": 1380.0,
      "spareKm": 356.0,
      "driveHours": 12.047058823529412,
      "countries": [
        "France",
        "Spain"
      ],
      "appointment": "20 May – 23 May · Nantes → Madrid"
    },
    {
      "score": 129.1,
      "route": [
        "Nantes",
        "Madrid"
      ],
      "legs": [
        {
          "originName": "Nantes",
          "destName": "Madrid",
          "pickup": "2026-05-20T06:00:05+02:00",
          "dropoff": "2026-05-23T06:00:05+02:00",
          "vehicle": "Pilote G690 GJ or similar",
          "make": "Pilote",
          "model": "G690 GJ or similar",
          "distanceKm": 1024.4,
          "offerId": "246738"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-20T06:00:05+02:00",
      "endUtc": "2026-05-23T06:00:05+02:00",
      "days": 3.0,
      "routeKm": 1024.0,
      "freeKm": 1380.0,
      "spareKm": 356.0,
      "driveHours": 12.047058823529412,
      "countries": [
        "France",
        "Spain"
      ],
      "appointment": "20 May – 23 May · Nantes → Madrid"
    },
    {
      "score": 129.1,
      "route": [
        "Nantes",
        "Madrid"
      ],
      "legs": [
        {
          "originName": "Nantes",
          "destName": "Madrid",
          "pickup": "2026-05-20T06:00:05+02:00",
          "dropoff": "2026-05-23T06:00:05+02:00",
          "vehicle": "Pilote G690 GJ or similar",
          "make": "Pilote",
          "model": "G690 GJ or similar",
          "distanceKm": 1024.4,
          "offerId": "246739"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-20T06:00:05+02:00",
      "endUtc": "2026-05-23T06:00:05+02:00",
      "days": 3.0,
      "routeKm": 1024.0,
      "freeKm": 1380.0,
      "spareKm": 356.0,
      "driveHours": 12.047058823529412,
      "countries": [
        "France",
        "Spain"
      ],
      "appointment": "20 May – 23 May · Nantes → Madrid"
    },
    {
      "score": 128.9,
      "route": [
        "Nantes",
        "Barcelona"
      ],
      "legs": [
        {
          "originName": "Nantes",
          "destName": "Barcelona",
          "pickup": "2026-05-20T06:00:05+02:00",
          "dropoff": "2026-05-23T06:00:05+02:00",
          "vehicle": "Pilote G690 GJ or similar",
          "make": "Pilote",
          "model": "G690 GJ or similar",
          "distanceKm": 984.8,
          "offerId": "246706"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-20T06:00:05+02:00",
      "endUtc": "2026-05-23T06:00:05+02:00",
      "days": 3.0,
      "routeKm": 985.0,
      "freeKm": 1150.0,
      "spareKm": 165.0,
      "driveHours": 11.588235294117647,
      "countries": [
        "France",
        "Spain"
      ],
      "appointment": "20 May – 23 May · Nantes → Barcelona"
    },
    {
      "score": 128.9,
      "route": [
        "Nantes",
        "Barcelona"
      ],
      "legs": [
        {
          "originName": "Nantes",
          "destName": "Barcelona",
          "pickup": "2026-05-20T06:00:05+02:00",
          "dropoff": "2026-05-23T06:00:05+02:00",
          "vehicle": "Pilote G690 GJ or similar",
          "make": "Pilote",
          "model": "G690 GJ or similar",
          "distanceKm": 984.8,
          "offerId": "246710"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-20T06:00:05+02:00",
      "endUtc": "2026-05-23T06:00:05+02:00",
      "days": 3.0,
      "routeKm": 985.0,
      "freeKm": 1150.0,
      "spareKm": 165.0,
      "driveHours": 11.588235294117647,
      "countries": [
        "France",
        "Spain"
      ],
      "appointment": "20 May – 23 May · Nantes → Barcelona"
    },
    {
      "score": 128.9,
      "route": [
        "Nantes",
        "Barcelona"
      ],
      "legs": [
        {
          "originName": "Nantes",
          "destName": "Barcelona",
          "pickup": "2026-05-20T06:00:05+02:00",
          "dropoff": "2026-05-23T06:00:05+02:00",
          "vehicle": "Pilote G690 GJ or similar",
          "make": "Pilote",
          "model": "G690 GJ or similar",
          "distanceKm": 984.8,
          "offerId": "246717"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-20T06:00:05+02:00",
      "endUtc": "2026-05-23T06:00:05+02:00",
      "days": 3.0,
      "routeKm": 985.0,
      "freeKm": 1150.0,
      "spareKm": 165.0,
      "driveHours": 11.588235294117647,
      "countries": [
        "France",
        "Spain"
      ],
      "appointment": "20 May – 23 May · Nantes → Barcelona"
    },
    {
      "score": 128.9,
      "route": [
        "Nantes",
        "Barcelona"
      ],
      "legs": [
        {
          "originName": "Nantes",
          "destName": "Barcelona",
          "pickup": "2026-05-20T06:00:05+02:00",
          "dropoff": "2026-05-23T06:00:05+02:00",
          "vehicle": "Pilote G690 GJ or similar",
          "make": "Pilote",
          "model": "G690 GJ or similar",
          "distanceKm": 984.8,
          "offerId": "246718"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-20T06:00:05+02:00",
      "endUtc": "2026-05-23T06:00:05+02:00",
      "days": 3.0,
      "routeKm": 985.0,
      "freeKm": 1150.0,
      "spareKm": 165.0,
      "driveHours": 11.588235294117647,
      "countries": [
        "France",
        "Spain"
      ],
      "appointment": "20 May – 23 May · Nantes → Barcelona"
    },
    {
      "score": 128.9,
      "route": [
        "Nantes",
        "Barcelona"
      ],
      "legs": [
        {
          "originName": "Nantes",
          "destName": "Barcelona",
          "pickup": "2026-05-20T06:00:05+02:00",
          "dropoff": "2026-05-23T06:00:05+02:00",
          "vehicle": "Pilote G690 GJ or similar",
          "make": "Pilote",
          "model": "G690 GJ or similar",
          "distanceKm": 984.8,
          "offerId": "246719"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-20T06:00:05+02:00",
      "endUtc": "2026-05-23T06:00:05+02:00",
      "days": 3.0,
      "routeKm": 985.0,
      "freeKm": 1150.0,
      "spareKm": 165.0,
      "driveHours": 11.588235294117647,
      "countries": [
        "France",
        "Spain"
      ],
      "appointment": "20 May – 23 May · Nantes → Barcelona"
    },
    {
      "score": 128.9,
      "route": [
        "Nantes",
        "Barcelona"
      ],
      "legs": [
        {
          "originName": "Nantes",
          "destName": "Barcelona",
          "pickup": "2026-05-20T06:00:05+02:00",
          "dropoff": "2026-05-23T06:00:05+02:00",
          "vehicle": "Pilote G690 GJ or similar",
          "make": "Pilote",
          "model": "G690 GJ or similar",
          "distanceKm": 984.8,
          "offerId": "246720"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-20T06:00:05+02:00",
      "endUtc": "2026-05-23T06:00:05+02:00",
      "days": 3.0,
      "routeKm": 985.0,
      "freeKm": 1150.0,
      "spareKm": 165.0,
      "driveHours": 11.588235294117647,
      "countries": [
        "France",
        "Spain"
      ],
      "appointment": "20 May – 23 May · Nantes → Barcelona"
    },
    {
      "score": 128.9,
      "route": [
        "Nantes",
        "Barcelona"
      ],
      "legs": [
        {
          "originName": "Nantes",
          "destName": "Barcelona",
          "pickup": "2026-05-20T06:00:05+02:00",
          "dropoff": "2026-05-23T06:00:05+02:00",
          "vehicle": "Pilote G690 GJ or similar",
          "make": "Pilote",
          "model": "G690 GJ or similar",
          "distanceKm": 984.8,
          "offerId": "246740"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-20T06:00:05+02:00",
      "endUtc": "2026-05-23T06:00:05+02:00",
      "days": 3.0,
      "routeKm": 985.0,
      "freeKm": 1150.0,
      "spareKm": 165.0,
      "driveHours": 11.588235294117647,
      "countries": [
        "France",
        "Spain"
      ],
      "appointment": "20 May – 23 May · Nantes → Barcelona"
    },
    {
      "score": 128.4,
      "route": [
        "Cabriès",
        "Wangen"
      ],
      "legs": [
        {
          "originName": "Cabriès",
          "destName": "Wangen",
          "pickup": "2026-05-20T00:00:00+02:00",
          "dropoff": "2026-05-23T00:00:00+02:00",
          "vehicle": "TRAVEL HOME Mercedes Benz Marco Polo - V-Klasse",
          "make": "TRAVEL HOME",
          "model": "Mercedes Benz Marco Polo - V-Klasse",
          "distanceKm": 877.3,
          "offerId": "246509"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-20T00:00:00+02:00",
      "endUtc": "2026-05-23T00:00:00+02:00",
      "days": 3.0,
      "routeKm": 877.0,
      "freeKm": 1400.0,
      "spareKm": 523.0,
      "driveHours": 10.31764705882353,
      "countries": [
        "France",
        "Germany"
      ],
      "appointment": "20 May – 23 May · Cabriès → Wangen"
    },
    {
      "score": 128.1,
      "route": [
        "Marburg",
        "Wien"
      ],
      "legs": [
        {
          "originName": "Marburg",
          "destName": "Wien",
          "pickup": "2026-05-20T00:00:00+02:00",
          "dropoff": "2026-05-23T00:00:00+02:00",
          "vehicle": "FAMILY FINCA VW Grand California 600 - VW Crafter 2",
          "make": "FAMILY FINCA",
          "model": "VW Grand California 600 - VW Crafter 2",
          "distanceKm": 826.3,
          "offerId": "244312"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-20T00:00:00+02:00",
      "endUtc": "2026-05-23T00:00:00+02:00",
      "days": 3.0,
      "routeKm": 826.0,
      "freeKm": 1400.0,
      "spareKm": 574.0,
      "driveHours": 9.717647058823529,
      "countries": [
        "Germany",
        "Austria"
      ],
      "appointment": "20 May – 23 May · Marburg → Wien"
    },
    {
      "score": 128.1,
      "route": [
        "Marburg",
        "Turin"
      ],
      "legs": [
        {
          "originName": "Marburg",
          "destName": "Turin",
          "pickup": "2026-05-21T00:00:00+02:00",
          "dropoff": "2026-05-24T00:00:00+02:00",
          "vehicle": "SURFER SUITE VW California Ocean",
          "make": "SURFER SUITE",
          "model": "VW California Ocean",
          "distanceKm": 822.0,
          "offerId": "236841"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-21T00:00:00+02:00",
      "endUtc": "2026-05-24T00:00:00+02:00",
      "days": 3.0,
      "routeKm": 822.0,
      "freeKm": 1400.0,
      "spareKm": 578.0,
      "driveHours": 9.670588235294117,
      "countries": [
        "Germany",
        "Italy"
      ],
      "appointment": "21 May – 24 May · Marburg → Turin"
    },
    {
      "score": 128.0,
      "route": [
        "Marburg",
        "Graz"
      ],
      "legs": [
        {
          "originName": "Marburg",
          "destName": "Graz",
          "pickup": "2026-05-20T00:00:00+02:00",
          "dropoff": "2026-05-23T00:00:00+02:00",
          "vehicle": "CAMPER CABIN DELUXE Ford Nugget Plus - Ford Transit Custom V362",
          "make": "CAMPER CABIN DELUXE",
          "model": "Ford Nugget Plus - Ford Transit Custom V362",
          "distanceKm": 807.8,
          "offerId": "245064"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-20T00:00:00+02:00",
      "endUtc": "2026-05-23T00:00:00+02:00",
      "days": 3.0,
      "routeKm": 808.0,
      "freeKm": 1400.0,
      "spareKm": 592.0,
      "driveHours": 9.505882352941176,
      "countries": [
        "Germany",
        "Austria"
      ],
      "appointment": "20 May – 23 May · Marburg → Graz"
    },
    {
      "score": 128.0,
      "route": [
        "Marburg",
        "Graz"
      ],
      "legs": [
        {
          "originName": "Marburg",
          "destName": "Graz",
          "pickup": "2026-05-20T00:00:00+02:00",
          "dropoff": "2026-05-23T00:00:00+02:00",
          "vehicle": "CAMPER CABIN DELUXE Ford Nugget Plus - Ford Transit Custom V362",
          "make": "CAMPER CABIN DELUXE",
          "model": "Ford Nugget Plus - Ford Transit Custom V362",
          "distanceKm": 807.8,
          "offerId": "245850"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-20T00:00:00+02:00",
      "endUtc": "2026-05-23T00:00:00+02:00",
      "days": 3.0,
      "routeKm": 808.0,
      "freeKm": 1400.0,
      "spareKm": 592.0,
      "driveHours": 9.505882352941176,
      "countries": [
        "Germany",
        "Austria"
      ],
      "appointment": "20 May – 23 May · Marburg → Graz"
    },
    {
      "score": 125.4,
      "route": [
        "Nantes",
        "Bilbao"
      ],
      "legs": [
        {
          "originName": "Nantes",
          "destName": "Bilbao",
          "pickup": "2026-05-20T06:00:05+02:00",
          "dropoff": "2026-05-22T06:00:05+02:00",
          "vehicle": "Pilote G690 GJ or similar",
          "make": "Pilote",
          "model": "G690 GJ or similar",
          "distanceKm": 670.5,
          "offerId": "246696"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-20T06:00:05+02:00",
      "endUtc": "2026-05-22T06:00:05+02:00",
      "days": 2.0,
      "routeKm": 670.0,
      "freeKm": 960.0,
      "spareKm": 290.0,
      "driveHours": 7.882352941176471,
      "countries": [
        "France",
        "Spain"
      ],
      "appointment": "20 May – 22 May · Nantes → Bilbao"
    },
    {
      "score": 125.4,
      "route": [
        "Nantes",
        "Bilbao"
      ],
      "legs": [
        {
          "originName": "Nantes",
          "destName": "Bilbao",
          "pickup": "2026-05-20T06:00:05+02:00",
          "dropoff": "2026-05-22T06:00:05+02:00",
          "vehicle": "Pilote G690 GJ or similar",
          "make": "Pilote",
          "model": "G690 GJ or similar",
          "distanceKm": 670.5,
          "offerId": "246716"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-20T06:00:05+02:00",
      "endUtc": "2026-05-22T06:00:05+02:00",
      "days": 2.0,
      "routeKm": 670.0,
      "freeKm": 960.0,
      "spareKm": 290.0,
      "driveHours": 7.882352941176471,
      "countries": [
        "France",
        "Spain"
      ],
      "appointment": "20 May – 22 May · Nantes → Bilbao"
    },
    {
      "score": 125.3,
      "route": [
        "Roma",
        "Turin"
      ],
      "legs": [
        {
          "originName": "Roma",
          "destName": "Turin",
          "pickup": "2026-05-21T00:00:00+02:00",
          "dropoff": "2026-05-23T00:00:00+02:00",
          "vehicle": "BEACH HOSTEL VW California Beach",
          "make": "BEACH HOSTEL",
          "model": "VW California Beach",
          "distanceKm": 669.3,
          "offerId": "242741"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-21T00:00:00+02:00",
      "endUtc": "2026-05-23T00:00:00+02:00",
      "days": 2.0,
      "routeKm": 669.0,
      "freeKm": 1000.0,
      "spareKm": 331.0,
      "driveHours": 7.870588235294117,
      "countries": [
        "Italy"
      ],
      "appointment": "21 May – 23 May · Roma → Turin"
    },
    {
      "score": 125.3,
      "route": [
        "Marburg",
        "Saint-Jean-de-Gonville"
      ],
      "legs": [
        {
          "originName": "Marburg",
          "destName": "Saint-Jean-de-Gonville",
          "pickup": "2026-05-21T00:00:00+02:00",
          "dropoff": "2026-05-23T00:00:00+02:00",
          "vehicle": "SURFER SUITE VW California Ocean",
          "make": "SURFER SUITE",
          "model": "VW California Ocean",
          "distanceKm": 663.4,
          "offerId": "237110"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-21T00:00:00+02:00",
      "endUtc": "2026-05-23T00:00:00+02:00",
      "days": 2.0,
      "routeKm": 663.0,
      "freeKm": 1000.0,
      "spareKm": 337.0,
      "driveHours": 7.8,
      "countries": [
        "Germany",
        "France"
      ],
      "appointment": "21 May – 23 May · Marburg → Saint-Jean-de-Gonville"
    },
    {
      "score": 109.5,
      "route": [
        "Mérignac",
        "Dormagen"
      ],
      "legs": [
        {
          "originName": "Mérignac",
          "destName": "Dormagen",
          "pickup": "2026-05-20T00:00:00+02:00",
          "dropoff": "2026-05-23T00:00:00+02:00",
          "vehicle": "ROAD HOUSE Westfalia Eliseo C540 - Fiat Ducato 8",
          "make": "ROAD HOUSE",
          "model": "Westfalia Eliseo C540 - Fiat Ducato 8",
          "distanceKm": 1091.9,
          "offerId": "244727"
        }
      ],
      "type": "inbound",
      "homeCity": "Bochum",
      "startUtc": "2026-05-20T00:00:00+02:00",
      "endUtc": "2026-05-23T00:00:00+02:00",
      "days": 3.0,
      "routeKm": 1092.0,
      "freeKm": 1400.0,
      "spareKm": 308.0,
      "driveHours": 12.847058823529412,
      "countries": [
        "France",
        "Germany"
      ],
      "appointment": "20 May – 23 May · Mérignac → Dormagen"
    },
    {
      "score": 109.2,
      "route": [
        "Nantes",
        "Marburg"
      ],
      "legs": [
        {
          "originName": "Nantes",
          "destName": "Marburg",
          "pickup": "2026-05-21T00:00:00+02:00",
          "dropoff": "2026-05-24T00:00:00+02:00",
          "vehicle": "ROAD HOUSE Westfalia Eliseo C540 - Fiat Ducato 8",
          "make": "ROAD HOUSE",
          "model": "Westfalia Eliseo C540 - Fiat Ducato 8",
          "distanceKm": 1045.0,
          "offerId": "246301"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-21T00:00:00+02:00",
      "endUtc": "2026-05-24T00:00:00+02:00",
      "days": 3.0,
      "routeKm": 1045.0,
      "freeKm": 1400.0,
      "spareKm": 355.0,
      "driveHours": 12.294117647058824,
      "countries": [
        "France",
        "Germany"
      ],
      "appointment": "21 May – 24 May · Nantes → Marburg"
    },
    {
      "score": 109.1,
      "route": [
        "Göteborgs Stad",
        "Marburg"
      ],
      "legs": [
        {
          "originName": "Göteborgs Stad",
          "destName": "Marburg",
          "pickup": "2026-05-21T00:00:00+02:00",
          "dropoff": "2026-05-24T00:00:00+02:00",
          "vehicle": "COUPLE COTTAGE Weinsberg Signeo C590 - Ford Transit V363",
          "make": "COUPLE COTTAGE",
          "model": "Weinsberg Signeo C590 - Ford Transit V363",
          "distanceKm": 1029.8,
          "offerId": "235595"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-21T00:00:00+02:00",
      "endUtc": "2026-05-24T00:00:00+02:00",
      "days": 3.0,
      "routeKm": 1030.0,
      "freeKm": 1400.0,
      "spareKm": 370.0,
      "driveHours": 12.117647058823529,
      "countries": [
        "Sweden",
        "Germany"
      ],
      "appointment": "21 May – 24 May · Göteborgs Stad → Marburg"
    },
    {
      "score": 108.8,
      "route": [
        "Nantes",
        "Frankfurt am Main"
      ],
      "legs": [
        {
          "originName": "Nantes",
          "destName": "Frankfurt am Main",
          "pickup": "2026-05-20T00:00:00+02:00",
          "dropoff": "2026-05-23T00:00:00+02:00",
          "vehicle": "CAMPER CASTLE Fiat Tracer 680DL - Fiat Ducato Serie 2",
          "make": "CAMPER CASTLE",
          "model": "Fiat Tracer 680DL - Fiat Ducato Serie 2",
          "distanceKm": 955.0,
          "offerId": "244148"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-20T00:00:00+02:00",
      "endUtc": "2026-05-23T00:00:00+02:00",
      "days": 3.0,
      "routeKm": 955.0,
      "freeKm": 1400.0,
      "spareKm": 445.0,
      "driveHours": 11.235294117647058,
      "countries": [
        "France",
        "Germany"
      ],
      "appointment": "20 May – 23 May · Nantes → Frankfurt am Main"
    },
    {
      "score": 108.4,
      "route": [
        "Castellanza",
        "Leipzig"
      ],
      "legs": [
        {
          "originName": "Castellanza",
          "destName": "Leipzig",
          "pickup": "2026-05-20T00:00:00+02:00",
          "dropoff": "2026-05-23T00:00:00+02:00",
          "vehicle": "SURFER SUITE VW California Ocean",
          "make": "SURFER SUITE",
          "model": "VW California Ocean",
          "distanceKm": 883.9,
          "offerId": "246293"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-20T00:00:00+02:00",
      "endUtc": "2026-05-23T00:00:00+02:00",
      "days": 3.0,
      "routeKm": 884.0,
      "freeKm": 1400.0,
      "spareKm": 516.0,
      "driveHours": 10.4,
      "countries": [
        "Italy",
        "Germany"
      ],
      "appointment": "20 May – 23 May · Castellanza → Leipzig"
    },
    {
      "score": 108.2,
      "route": [
        "Berglern",
        "Saint-Mesmes"
      ],
      "legs": [
        {
          "originName": "Berglern",
          "destName": "Saint-Mesmes",
          "pickup": "2026-05-20T06:00:05+02:00",
          "dropoff": "2026-05-23T06:00:05+02:00",
          "vehicle": "Fiat Ducato",
          "make": "Fiat",
          "model": "Ducato",
          "distanceKm": 844.2,
          "offerId": "246707"
        }
      ],
      "type": "oneway",
      "homeCity": "München",
      "startUtc": "2026-05-20T06:00:05+02:00",
      "endUtc": "2026-05-23T06:00:05+02:00",
      "days": 3.0,
      "routeKm": 844.0,
      "freeKm": 1150.0,
      "spareKm": 306.0,
      "driveHours": 9.929411764705883,
      "countries": [
        "Germany",
        "France"
      ],
      "appointment": "20 May – 23 May · Berglern → Saint-Mesmes"
    },
    {
      "score": 108.2,
      "route": [
        "Berglern",
        "Saint-Mesmes"
      ],
      "legs": [
        {
          "originName": "Berglern",
          "destName": "Saint-Mesmes",
          "pickup": "2026-05-20T06:00:05+02:00",
          "dropoff": "2026-05-23T06:00:05+02:00",
          "vehicle": "Fiat Ducato",
          "make": "Fiat",
          "model": "Ducato",
          "distanceKm": 844.2,
          "offerId": "246708"
        }
      ],
      "type": "oneway",
      "homeCity": "München",
      "startUtc": "2026-05-20T06:00:05+02:00",
      "endUtc": "2026-05-23T06:00:05+02:00",
      "days": 3.0,
      "routeKm": 844.0,
      "freeKm": 1150.0,
      "spareKm": 306.0,
      "driveHours": 9.929411764705883,
      "countries": [
        "Germany",
        "France"
      ],
      "appointment": "20 May – 23 May · Berglern → Saint-Mesmes"
    },
    {
      "score": 108.2,
      "route": [
        "Berglern",
        "Saint-Mesmes"
      ],
      "legs": [
        {
          "originName": "Berglern",
          "destName": "Saint-Mesmes",
          "pickup": "2026-05-20T06:00:05+02:00",
          "dropoff": "2026-05-23T06:00:05+02:00",
          "vehicle": "Fiat Ducato",
          "make": "Fiat",
          "model": "Ducato",
          "distanceKm": 844.2,
          "offerId": "246721"
        }
      ],
      "type": "oneway",
      "homeCity": "München",
      "startUtc": "2026-05-20T06:00:05+02:00",
      "endUtc": "2026-05-23T06:00:05+02:00",
      "days": 3.0,
      "routeKm": 844.0,
      "freeKm": 1150.0,
      "spareKm": 306.0,
      "driveHours": 9.929411764705883,
      "countries": [
        "Germany",
        "France"
      ],
      "appointment": "20 May – 23 May · Berglern → Saint-Mesmes"
    },
    {
      "score": 108.2,
      "route": [
        "Berglern",
        "Saint-Mesmes"
      ],
      "legs": [
        {
          "originName": "Berglern",
          "destName": "Saint-Mesmes",
          "pickup": "2026-05-20T06:00:05+02:00",
          "dropoff": "2026-05-23T06:00:05+02:00",
          "vehicle": "Fiat Ducato",
          "make": "Fiat",
          "model": "Ducato",
          "distanceKm": 844.2,
          "offerId": "246742"
        }
      ],
      "type": "oneway",
      "homeCity": "München",
      "startUtc": "2026-05-20T06:00:05+02:00",
      "endUtc": "2026-05-23T06:00:05+02:00",
      "days": 3.0,
      "routeKm": 844.0,
      "freeKm": 1150.0,
      "spareKm": 306.0,
      "driveHours": 9.929411764705883,
      "countries": [
        "Germany",
        "France"
      ],
      "appointment": "20 May – 23 May · Berglern → Saint-Mesmes"
    },
    {
      "score": 105.8,
      "route": [
        "Nantes",
        "Lyon"
      ],
      "legs": [
        {
          "originName": "Nantes",
          "destName": "Lyon",
          "pickup": "2026-05-20T06:00:05+02:00",
          "dropoff": "2026-05-22T06:00:05+02:00",
          "vehicle": "Pilote G690 GJ or similar",
          "make": "Pilote",
          "model": "G690 GJ or similar",
          "distanceKm": 752.3,
          "offerId": "246711"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-20T06:00:05+02:00",
      "endUtc": "2026-05-22T06:00:05+02:00",
      "days": 2.0,
      "routeKm": 752.0,
      "freeKm": 960.0,
      "spareKm": 208.0,
      "driveHours": 8.847058823529412,
      "countries": [
        "France"
      ],
      "appointment": "20 May – 22 May · Nantes → Lyon"
    },
    {
      "score": 105.8,
      "route": [
        "Nantes",
        "Lyon"
      ],
      "legs": [
        {
          "originName": "Nantes",
          "destName": "Lyon",
          "pickup": "2026-05-20T06:00:05+02:00",
          "dropoff": "2026-05-22T06:00:05+02:00",
          "vehicle": "Pilote G690 GJ or similar",
          "make": "Pilote",
          "model": "G690 GJ or similar",
          "distanceKm": 752.3,
          "offerId": "246713"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-20T06:00:05+02:00",
      "endUtc": "2026-05-22T06:00:05+02:00",
      "days": 2.0,
      "routeKm": 752.0,
      "freeKm": 960.0,
      "spareKm": 208.0,
      "driveHours": 8.847058823529412,
      "countries": [
        "France"
      ],
      "appointment": "20 May – 22 May · Nantes → Lyon"
    },
    {
      "score": 105.5,
      "route": [
        "Florence",
        "Lyon"
      ],
      "legs": [
        {
          "originName": "Florence",
          "destName": "Lyon",
          "pickup": "2026-05-20T06:00:05+02:00",
          "dropoff": "2026-05-22T06:00:05+02:00",
          "vehicle": "Fiat S 75SL / T 7400 SB or similar",
          "make": "Fiat",
          "model": "S 75SL / T 7400 SB or similar",
          "distanceKm": 692.1,
          "offerId": "246731"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-20T06:00:05+02:00",
      "endUtc": "2026-05-22T06:00:05+02:00",
      "days": 2.0,
      "routeKm": 692.0,
      "freeKm": 960.0,
      "spareKm": 268.0,
      "driveHours": 8.141176470588235,
      "countries": [
        "Italy",
        "France"
      ],
      "appointment": "20 May – 22 May · Florence → Lyon"
    },
    {
      "score": 105.5,
      "route": [
        "Florence",
        "Lyon"
      ],
      "legs": [
        {
          "originName": "Florence",
          "destName": "Lyon",
          "pickup": "2026-05-20T06:00:05+02:00",
          "dropoff": "2026-05-22T06:00:05+02:00",
          "vehicle": "Fiat S 75SL / T 7400 SB or similar",
          "make": "Fiat",
          "model": "S 75SL / T 7400 SB or similar",
          "distanceKm": 692.1,
          "offerId": "246732"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-20T06:00:05+02:00",
      "endUtc": "2026-05-22T06:00:05+02:00",
      "days": 2.0,
      "routeKm": 692.0,
      "freeKm": 960.0,
      "spareKm": 268.0,
      "driveHours": 8.141176470588235,
      "countries": [
        "Italy",
        "France"
      ],
      "appointment": "20 May – 22 May · Florence → Lyon"
    },
    {
      "score": 105.5,
      "route": [
        "Florence",
        "Lyon"
      ],
      "legs": [
        {
          "originName": "Florence",
          "destName": "Lyon",
          "pickup": "2026-05-20T06:00:05+02:00",
          "dropoff": "2026-05-22T06:00:05+02:00",
          "vehicle": "Fiat S 75SL / T 7400 SB or similar",
          "make": "Fiat",
          "model": "S 75SL / T 7400 SB or similar",
          "distanceKm": 692.1,
          "offerId": "246734"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-20T06:00:05+02:00",
      "endUtc": "2026-05-22T06:00:05+02:00",
      "days": 2.0,
      "routeKm": 692.0,
      "freeKm": 960.0,
      "spareKm": 268.0,
      "driveHours": 8.141176470588235,
      "countries": [
        "Italy",
        "France"
      ],
      "appointment": "20 May – 22 May · Florence → Lyon"
    },
    {
      "score": 105.5,
      "route": [
        "Florence",
        "Lyon"
      ],
      "legs": [
        {
          "originName": "Florence",
          "destName": "Lyon",
          "pickup": "2026-05-20T06:00:05+02:00",
          "dropoff": "2026-05-22T06:00:05+02:00",
          "vehicle": "Fiat S 75SL / T 7400 SB or similar",
          "make": "Fiat",
          "model": "S 75SL / T 7400 SB or similar",
          "distanceKm": 692.1,
          "offerId": "246743"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-20T06:00:05+02:00",
      "endUtc": "2026-05-22T06:00:05+02:00",
      "days": 2.0,
      "routeKm": 692.0,
      "freeKm": 960.0,
      "spareKm": 268.0,
      "driveHours": 8.141176470588235,
      "countries": [
        "Italy",
        "France"
      ],
      "appointment": "20 May – 22 May · Florence → Lyon"
    },
    {
      "score": 105.4,
      "route": [
        "London",
        "Edinburgh"
      ],
      "legs": [
        {
          "originName": "London",
          "destName": "Edinburgh",
          "pickup": "2026-05-21T06:00:05+02:00",
          "dropoff": "2026-05-23T06:00:05+02:00",
          "vehicle": "Pilote V630J or similar",
          "make": "Pilote",
          "model": "V630J or similar",
          "distanceKm": 681.9,
          "offerId": "246601"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-21T06:00:05+02:00",
      "endUtc": "2026-05-23T06:00:05+02:00",
      "days": 2.0,
      "routeKm": 682.0,
      "freeKm": 960.0,
      "spareKm": 278.0,
      "driveHours": 8.023529411764706,
      "countries": [
        "UK",
        "Europe"
      ],
      "appointment": "21 May – 23 May · London → Edinburgh"
    },
    {
      "score": 102.6,
      "route": [
        "Hamburg",
        "Dresden"
      ],
      "legs": [
        {
          "originName": "Hamburg",
          "destName": "Dresden",
          "pickup": "2026-05-20T06:00:00+02:00",
          "dropoff": "2026-05-21T06:00:00+02:00",
          "vehicle": "Citroen Mooveo Light Tei-70 EB",
          "make": "Citroen",
          "model": "Mooveo Light Tei-70 EB",
          "distanceKm": 528.1,
          "offerId": "246852"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-20T06:00:00+02:00",
      "endUtc": "2026-05-21T06:00:00+02:00",
      "days": 1.0,
      "routeKm": 528.0,
      "freeKm": 1000.0,
      "spareKm": 472.0,
      "driveHours": 6.211764705882353,
      "countries": [
        "Germany"
      ],
      "appointment": "20 May – 21 May · Hamburg → Dresden"
    },
    {
      "score": 102.6,
      "route": [
        "Hamburg",
        "Dresden"
      ],
      "legs": [
        {
          "originName": "Hamburg",
          "destName": "Dresden",
          "pickup": "2026-05-20T06:00:00+02:00",
          "dropoff": "2026-05-21T06:00:00+02:00",
          "vehicle": "Citroen Mooveo Light Tei-70 EB",
          "make": "Citroen",
          "model": "Mooveo Light Tei-70 EB",
          "distanceKm": 528.1,
          "offerId": "246853"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-20T06:00:00+02:00",
      "endUtc": "2026-05-21T06:00:00+02:00",
      "days": 1.0,
      "routeKm": 528.0,
      "freeKm": 1000.0,
      "spareKm": 472.0,
      "driveHours": 6.211764705882353,
      "countries": [
        "Germany"
      ],
      "appointment": "20 May – 21 May · Hamburg → Dresden"
    },
    {
      "score": 101.8,
      "route": [
        "Weingarten",
        "Vizzola Ticino"
      ],
      "legs": [
        {
          "originName": "Weingarten",
          "destName": "Vizzola Ticino",
          "pickup": "2026-05-20T14:00:27+02:00",
          "dropoff": "2026-05-21T14:00:27+02:00",
          "vehicle": "AUDI A6 EST HBD AUT",
          "make": "AUDI",
          "model": "A6 EST HBD AUT",
          "distanceKm": 357.6,
          "offerId": "246837"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-20T14:00:27+02:00",
      "endUtc": "2026-05-21T14:00:27+02:00",
      "days": 1.0,
      "routeKm": 358.0,
      "freeKm": 450.0,
      "spareKm": 92.0,
      "driveHours": 4.211764705882353,
      "countries": [
        "Germany",
        "Italy"
      ],
      "appointment": "20 May – 21 May · Weingarten → Vizzola Ticino"
    },
    {
      "score": 101.4,
      "route": [
        "Florence",
        "Bastia"
      ],
      "legs": [
        {
          "originName": "Florence",
          "destName": "Bastia",
          "pickup": "2026-05-20T06:00:05+02:00",
          "dropoff": "2026-05-21T06:00:05+02:00",
          "vehicle": "Fiat Ducato",
          "make": "Fiat",
          "model": "Ducato",
          "distanceKm": 281.3,
          "offerId": "246697"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-20T06:00:05+02:00",
      "endUtc": "2026-05-21T06:00:05+02:00",
      "days": 1.0,
      "routeKm": 281.0,
      "freeKm": 480.0,
      "spareKm": 199.0,
      "driveHours": 3.3058823529411763,
      "countries": [
        "Italy"
      ],
      "appointment": "20 May – 21 May · Florence → Bastia"
    },
    {
      "score": 101.4,
      "route": [
        "Florence",
        "Bastia"
      ],
      "legs": [
        {
          "originName": "Florence",
          "destName": "Bastia",
          "pickup": "2026-05-20T06:00:05+02:00",
          "dropoff": "2026-05-21T06:00:05+02:00",
          "vehicle": "Fiat Ducato",
          "make": "Fiat",
          "model": "Ducato",
          "distanceKm": 281.3,
          "offerId": "246698"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-20T06:00:05+02:00",
      "endUtc": "2026-05-21T06:00:05+02:00",
      "days": 1.0,
      "routeKm": 281.0,
      "freeKm": 480.0,
      "spareKm": 199.0,
      "driveHours": 3.3058823529411763,
      "countries": [
        "Italy"
      ],
      "appointment": "20 May – 21 May · Florence → Bastia"
    },
    {
      "score": 101.4,
      "route": [
        "Florence",
        "Bastia"
      ],
      "legs": [
        {
          "originName": "Florence",
          "destName": "Bastia",
          "pickup": "2026-05-20T06:00:05+02:00",
          "dropoff": "2026-05-21T06:00:05+02:00",
          "vehicle": "Fiat Ducato",
          "make": "Fiat",
          "model": "Ducato",
          "distanceKm": 281.3,
          "offerId": "246714"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-20T06:00:05+02:00",
      "endUtc": "2026-05-21T06:00:05+02:00",
      "days": 1.0,
      "routeKm": 281.0,
      "freeKm": 480.0,
      "spareKm": 199.0,
      "driveHours": 3.3058823529411763,
      "countries": [
        "Italy"
      ],
      "appointment": "20 May – 21 May · Florence → Bastia"
    },
    {
      "score": 101.4,
      "route": [
        "Florence",
        "Bastia"
      ],
      "legs": [
        {
          "originName": "Florence",
          "destName": "Bastia",
          "pickup": "2026-05-20T06:00:05+02:00",
          "dropoff": "2026-05-21T06:00:05+02:00",
          "vehicle": "Fiat Ducato",
          "make": "Fiat",
          "model": "Ducato",
          "distanceKm": 281.3,
          "offerId": "246733"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-20T06:00:05+02:00",
      "endUtc": "2026-05-21T06:00:05+02:00",
      "days": 1.0,
      "routeKm": 281.0,
      "freeKm": 480.0,
      "spareKm": 199.0,
      "driveHours": 3.3058823529411763,
      "countries": [
        "Italy"
      ],
      "appointment": "20 May – 21 May · Florence → Bastia"
    },
    {
      "score": 101.4,
      "route": [
        "Florence",
        "Bastia"
      ],
      "legs": [
        {
          "originName": "Florence",
          "destName": "Bastia",
          "pickup": "2026-05-20T06:00:05+02:00",
          "dropoff": "2026-05-21T06:00:05+02:00",
          "vehicle": "Fiat Ducato",
          "make": "Fiat",
          "model": "Ducato",
          "distanceKm": 281.3,
          "offerId": "246735"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-20T06:00:05+02:00",
      "endUtc": "2026-05-21T06:00:05+02:00",
      "days": 1.0,
      "routeKm": 281.0,
      "freeKm": 480.0,
      "spareKm": 199.0,
      "driveHours": 3.3058823529411763,
      "countries": [
        "Italy"
      ],
      "appointment": "20 May – 21 May · Florence → Bastia"
    },
    {
      "score": 101.4,
      "route": [
        "Florence",
        "Bastia"
      ],
      "legs": [
        {
          "originName": "Florence",
          "destName": "Bastia",
          "pickup": "2026-05-20T06:00:05+02:00",
          "dropoff": "2026-05-21T06:00:05+02:00",
          "vehicle": "Fiat Ducato",
          "make": "Fiat",
          "model": "Ducato",
          "distanceKm": 281.3,
          "offerId": "246744"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-20T06:00:05+02:00",
      "endUtc": "2026-05-21T06:00:05+02:00",
      "days": 1.0,
      "routeKm": 281.0,
      "freeKm": 480.0,
      "spareKm": 199.0,
      "driveHours": 3.3058823529411763,
      "countries": [
        "Italy"
      ],
      "appointment": "20 May – 21 May · Florence → Bastia"
    },
    {
      "score": 101.3,
      "route": [
        "Lörrach",
        "Sindelfingen"
      ],
      "legs": [
        {
          "originName": "Lörrach",
          "destName": "Sindelfingen",
          "pickup": "2026-05-20T17:21:42+02:00",
          "dropoff": "2026-05-21T17:21:42+02:00",
          "vehicle": "MAN TGE 3.140 L 3,5 TO KAS DI MAN",
          "make": "MAN",
          "model": "TGE 3.140 L 3,5 TO KAS DI MAN",
          "distanceKm": 256.4,
          "offerId": "246864"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-20T17:21:42+02:00",
      "endUtc": "2026-05-21T17:21:42+02:00",
      "days": 1.0,
      "routeKm": 256.0,
      "freeKm": 350.0,
      "spareKm": 94.0,
      "driveHours": 3.011764705882353,
      "countries": [
        "Germany"
      ],
      "appointment": "20 May – 21 May · Lörrach → Sindelfingen"
    },
    {
      "score": 100.4,
      "route": [
        "München",
        "Landsberg am Lech"
      ],
      "legs": [
        {
          "originName": "München",
          "destName": "Landsberg am Lech",
          "pickup": "2026-05-20T15:21:11+02:00",
          "dropoff": "2026-05-21T15:21:11+02:00",
          "vehicle": "NISSA PRIMASTAR MPV 9S DI AUT",
          "make": "NISSA",
          "model": "PRIMASTAR MPV 9S DI AUT",
          "distanceKm": 89.3,
          "offerId": "246832"
        }
      ],
      "type": "oneway",
      "homeCity": "München",
      "startUtc": "2026-05-20T15:21:11+02:00",
      "endUtc": "2026-05-21T15:21:11+02:00",
      "days": 1.0,
      "routeKm": 89.0,
      "freeKm": 150.0,
      "spareKm": 61.0,
      "driveHours": 1.0470588235294118,
      "countries": [
        "Germany"
      ],
      "appointment": "20 May – 21 May · München → Landsberg am Lech"
    },
    {
      "score": 100.4,
      "route": [
        "München",
        "Landsberg am Lech"
      ],
      "legs": [
        {
          "originName": "München",
          "destName": "Landsberg am Lech",
          "pickup": "2026-05-20T15:21:11+02:00",
          "dropoff": "2026-05-21T15:21:11+02:00",
          "vehicle": "NISSA PRIMASTAR MPV 9S DI MAN",
          "make": "NISSA",
          "model": "PRIMASTAR MPV 9S DI MAN",
          "distanceKm": 89.3,
          "offerId": "246833"
        }
      ],
      "type": "oneway",
      "homeCity": "München",
      "startUtc": "2026-05-20T15:21:11+02:00",
      "endUtc": "2026-05-21T15:21:11+02:00",
      "days": 1.0,
      "routeKm": 89.0,
      "freeKm": 150.0,
      "spareKm": 61.0,
      "driveHours": 1.0470588235294118,
      "countries": [
        "Germany"
      ],
      "appointment": "20 May – 21 May · München → Landsberg am Lech"
    }
  ]
} as const;
