// AUTO-GENERATED by scripts/build.py — do not edit manually.
// Generated: 2026-05-23T11:55:20Z
// Run `npm run refresh` to regenerate.

import type { TripData } from '@/lib/chains';

export const TRIP_DATA: TripData = {
  "meta": {
    "generated": "2026-05-23T11:55:20Z",
    "offerCount": 68,
    "recommendedCount": 71
  },
  "offers": [
    {
      "offerId": "247752",
      "originName": "Marburg",
      "destName": "Champlan",
      "startUtc": "2026-05-17T22:00:00Z",
      "endUtc": "2026-05-25T21:59:59Z",
      "periodHours": 48,
      "distanceKm": 651.9,
      "freeKm": 1000.0,
      "make": "CAMPER CABIN DELUXE",
      "model": "Ford Nugget Plus - Ford Transit Custom V362"
    },
    {
      "offerId": "247229",
      "originName": "Gersthofen",
      "destName": "Leipzig",
      "startUtc": "2026-05-19T22:00:00Z",
      "endUtc": "2026-05-27T21:59:59Z",
      "periodHours": 48,
      "distanceKm": 419.4,
      "freeKm": 1000.0,
      "make": "COZY COTTAGE",
      "model": "Knaus Van TI Plus 650 MEG Platinum Selection - VW Crafter 2",
      "homeCity": "München"
    },
    {
      "offerId": "245064",
      "originName": "Marburg",
      "destName": "Graz",
      "startUtc": "2026-05-21T22:00:00Z",
      "endUtc": "2026-05-29T21:59:59Z",
      "periodHours": 72,
      "distanceKm": 807.8,
      "freeKm": 1400.0,
      "make": "CAMPER CABIN DELUXE",
      "model": "Ford Nugget Plus - Ford Transit Custom V362"
    },
    {
      "offerId": "246239",
      "originName": "Marburg",
      "destName": "Castellanza",
      "startUtc": "2026-05-21T22:00:00Z",
      "endUtc": "2026-05-29T21:59:59Z",
      "periodHours": 48,
      "distanceKm": 740.4,
      "freeKm": 1000.0,
      "make": "FAMILY FINCA",
      "model": "VW Grand California 600 - VW Crafter 2"
    },
    {
      "offerId": "246475",
      "originName": "Saint-Jean-de-Gonville",
      "destName": "Aach",
      "startUtc": "2026-05-22T22:00:00Z",
      "endUtc": "2026-05-30T21:59:59Z",
      "periodHours": 24,
      "distanceKm": 353.4,
      "freeKm": 600.0,
      "make": "SURFER SUITE",
      "model": "VW California Ocean"
    },
    {
      "offerId": "247816",
      "originName": "Champlan",
      "destName": "Frankfurt am Main",
      "startUtc": "2026-05-22T22:00:00Z",
      "endUtc": "2026-05-30T21:59:59Z",
      "periodHours": 48,
      "distanceKm": 573.3,
      "freeKm": 1000.0,
      "make": "COUPLE COTTAGE",
      "model": "Weinsberg Signeo C590 - Ford Transit V363"
    },
    {
      "offerId": "243264",
      "originName": "Weyhe",
      "destName": "Castellanza",
      "startUtc": "2026-05-24T22:00:00Z",
      "endUtc": "2026-06-01T21:59:59Z",
      "periodHours": 72,
      "distanceKm": 1066.5,
      "freeKm": 1400.0,
      "make": "CAMPER CASTLE",
      "model": "Fiat Tracer 680DL - Fiat Ducato Serie 2",
      "homeCity": "Hannover"
    },
    {
      "offerId": "242808",
      "originName": "Marburg",
      "destName": "Staffanstorps kommun",
      "startUtc": "2026-05-25T22:00:00Z",
      "endUtc": "2026-06-02T21:59:59Z",
      "periodHours": 48,
      "distanceKm": 769.8,
      "freeKm": 1000.0,
      "make": "CAMPER CASTLE",
      "model": "Fiat Tracer 680DL - Fiat Ducato Serie 2"
    },
    {
      "offerId": "243325",
      "originName": "Berlin",
      "destName": "Bochum",
      "startUtc": "2026-05-25T22:00:00Z",
      "endUtc": "2026-06-01T21:59:59Z",
      "periodHours": 48,
      "distanceKm": 512.1,
      "freeKm": 1000.0,
      "make": "COZY COTTAGE",
      "model": "Knaus Van TI Plus 650 MEG Platinum Selection - VW Crafter 2"
    },
    {
      "offerId": "247836",
      "originName": "Florence",
      "destName": "Bastia",
      "startUtc": "2026-05-26T04:00:05Z",
      "endUtc": "2026-06-03T21:51:06Z",
      "periodHours": 24,
      "distanceKm": 281.3,
      "freeKm": 480.0,
      "make": "Fiat",
      "model": "Ducato"
    },
    {
      "offerId": "247837",
      "originName": "Nantes",
      "destName": "Bilbao",
      "startUtc": "2026-05-26T04:00:05Z",
      "endUtc": "2026-06-03T21:51:06Z",
      "periodHours": 48,
      "distanceKm": 670.5,
      "freeKm": 960.0,
      "make": "Pilote",
      "model": "G690 GJ or similar"
    },
    {
      "offerId": "247838",
      "originName": "Florence",
      "destName": "Lyon",
      "startUtc": "2026-05-26T04:00:05Z",
      "endUtc": "2026-05-31T21:51:05Z",
      "periodHours": 48,
      "distanceKm": 692.1,
      "freeKm": 960.0,
      "make": "Fiat",
      "model": "S 75SL / T 7400 SB or similar"
    },
    {
      "offerId": "247842",
      "originName": "Berglern",
      "destName": "Saint-Mesmes",
      "startUtc": "2026-05-26T04:00:05Z",
      "endUtc": "2026-06-01T21:51:06Z",
      "periodHours": 72,
      "distanceKm": 844.2,
      "freeKm": 1150.0,
      "make": "Fiat",
      "model": "Ducato",
      "homeCity": "München"
    },
    {
      "offerId": "247844",
      "originName": "Bordeaux",
      "destName": "Barcelona",
      "startUtc": "2026-05-26T04:00:05Z",
      "endUtc": "2026-06-03T21:51:06Z",
      "periodHours": 48,
      "distanceKm": 662.2,
      "freeKm": 960.0,
      "make": "Fiat",
      "model": "Sport 346 or similar"
    },
    {
      "offerId": "247846",
      "originName": "Grigny",
      "destName": "Saint-Mesmes",
      "startUtc": "2026-05-26T04:00:05Z",
      "endUtc": "2026-06-03T21:51:06Z",
      "periodHours": 24,
      "distanceKm": 56.1,
      "freeKm": 240.0,
      "make": "Ford",
      "model": "Transit/Jumper or similar"
    },
    {
      "offerId": "247851",
      "originName": "Nantes",
      "destName": "Lyon",
      "startUtc": "2026-05-26T04:00:05Z",
      "endUtc": "2026-06-03T21:51:06Z",
      "periodHours": 48,
      "distanceKm": 752.3,
      "freeKm": 960.0,
      "make": "Pilote",
      "model": "G690 GJ or similar"
    },
    {
      "offerId": "247852",
      "originName": "Toulouse",
      "destName": "Saint-Mesmes",
      "startUtc": "2026-05-26T04:00:05Z",
      "endUtc": "2026-06-03T21:51:06Z",
      "periodHours": 48,
      "distanceKm": 706.0,
      "freeKm": 960.0,
      "make": "Volkswagen",
      "model": "California"
    },
    {
      "offerId": "247854",
      "originName": "Lyon",
      "destName": "Saint-Mesmes",
      "startUtc": "2026-05-26T04:00:05Z",
      "endUtc": "2026-06-03T21:51:06Z",
      "periodHours": 48,
      "distanceKm": 526.4,
      "freeKm": 720.0,
      "make": "Volkswagen",
      "model": "California"
    },
    {
      "offerId": "247856",
      "originName": "Nantes",
      "destName": "Madrid",
      "startUtc": "2026-05-26T04:00:05Z",
      "endUtc": "2026-06-05T21:51:06Z",
      "periodHours": 72,
      "distanceKm": 1024.4,
      "freeKm": 1380.0,
      "make": "Pilote",
      "model": "G690 GJ or similar"
    },
    {
      "offerId": "247860",
      "originName": "Nantes",
      "destName": "Barcelona",
      "startUtc": "2026-05-26T04:00:05Z",
      "endUtc": "2026-06-05T21:51:06Z",
      "periodHours": 72,
      "distanceKm": 984.8,
      "freeKm": 1150.0,
      "make": "Pilote",
      "model": "G690 GJ or similar"
    },
    {
      "offerId": "247929",
      "originName": "Amstelveen",
      "destName": "Stuttgart",
      "startUtc": "2026-05-26T04:00:05Z",
      "endUtc": "2026-06-01T21:51:06Z",
      "periodHours": 48,
      "distanceKm": 681.9,
      "freeKm": 960.0,
      "make": "Volkswagen",
      "model": "California"
    },
    {
      "offerId": "247930",
      "originName": "Berglern",
      "destName": "Venezia",
      "startUtc": "2026-05-26T04:00:05Z",
      "endUtc": "2026-06-01T21:51:06Z",
      "periodHours": 48,
      "distanceKm": 560.0,
      "freeKm": 720.0,
      "make": "Fiat",
      "model": "Ducato",
      "homeCity": "München"
    },
    {
      "offerId": "247931",
      "originName": "Florence",
      "destName": "Milan",
      "startUtc": "2026-05-26T04:00:05Z",
      "endUtc": "2026-06-01T21:51:06Z",
      "periodHours": 24,
      "distanceKm": 345.7,
      "freeKm": 480.0,
      "make": "Fiat",
      "model": "S 75SL / T 7400 SB or similar"
    },
    {
      "offerId": "247934",
      "originName": "Florence",
      "destName": "Cagliari",
      "startUtc": "2026-05-26T04:00:05Z",
      "endUtc": "2026-06-01T21:51:06Z",
      "periodHours": 48,
      "distanceKm": 649.4,
      "freeKm": 960.0,
      "make": "Fiat",
      "model": "Ducato"
    },
    {
      "offerId": "247936",
      "originName": "Bologna",
      "destName": "Milan",
      "startUtc": "2026-05-26T04:00:05Z",
      "endUtc": "2026-06-01T21:51:06Z",
      "periodHours": 24,
      "distanceKm": 263.8,
      "freeKm": 480.0,
      "make": "Fiat",
      "model": "S 75SL / T 7400 SB or similar"
    },
    {
      "offerId": "247937",
      "originName": "Nantes",
      "destName": "Milan",
      "startUtc": "2026-05-26T04:00:05Z",
      "endUtc": "2026-06-03T21:51:06Z",
      "periodHours": 72,
      "distanceKm": 1118.6,
      "freeKm": 1380.0,
      "make": "Pilote",
      "model": "G690 GJ or similar"
    },
    {
      "offerId": "247940",
      "originName": "Berlin",
      "destName": "Warszawa",
      "startUtc": "2026-05-26T04:00:05Z",
      "endUtc": "2026-06-01T21:51:06Z",
      "periodHours": 48,
      "distanceKm": 560.9,
      "freeKm": 720.0,
      "make": "Fiat",
      "model": "Ducato"
    },
    {
      "offerId": "247941",
      "originName": "Berglern",
      "destName": "Bologna",
      "startUtc": "2026-05-26T04:00:05Z",
      "endUtc": "2026-06-01T21:51:06Z",
      "periodHours": 48,
      "distanceKm": 580.4,
      "freeKm": 720.0,
      "make": "Fiat",
      "model": "Ducato",
      "homeCity": "München"
    },
    {
      "offerId": "247946",
      "originName": "Florence",
      "destName": "Bergamo",
      "startUtc": "2026-05-26T04:00:05Z",
      "endUtc": "2026-06-01T21:51:06Z",
      "periodHours": 24,
      "distanceKm": 325.4,
      "freeKm": 480.0,
      "make": "Fiat",
      "model": "S 75SL / T 7400 SB or similar"
    },
    {
      "offerId": "247950",
      "originName": "Florence",
      "destName": "Olbia",
      "startUtc": "2026-05-26T04:00:05Z",
      "endUtc": "2026-06-01T21:51:06Z",
      "periodHours": 24,
      "distanceKm": 396.0,
      "freeKm": 480.0,
      "make": "Fiat",
      "model": "Ducato"
    },
    {
      "offerId": "247963",
      "originName": "Nantes",
      "destName": "Bergamo",
      "startUtc": "2026-05-26T04:00:05Z",
      "endUtc": "2026-06-04T21:51:06Z",
      "periodHours": 72,
      "distanceKm": 1164.9,
      "freeKm": 1380.0,
      "make": "Pilote",
      "model": "G690 GJ or similar"
    },
    {
      "offerId": "247965",
      "originName": "Berglern",
      "destName": "Milan",
      "startUtc": "2026-05-26T04:00:05Z",
      "endUtc": "2026-06-01T21:51:06Z",
      "periodHours": 48,
      "distanceKm": 535.0,
      "freeKm": 720.0,
      "make": "Fiat",
      "model": "Ducato",
      "homeCity": "München"
    },
    {
      "offerId": "248013",
      "originName": "Berglern",
      "destName": "Olbia",
      "startUtc": "2026-05-26T04:00:05Z",
      "endUtc": "2026-06-03T21:51:06Z",
      "periodHours": 72,
      "distanceKm": 1059.7,
      "freeKm": 1380.0,
      "make": "Fiat",
      "model": "Ducato",
      "homeCity": "München"
    },
    {
      "offerId": "248017",
      "originName": "Berglern",
      "destName": "Bergamo",
      "startUtc": "2026-05-26T04:00:05Z",
      "endUtc": "2026-06-01T21:51:06Z",
      "periodHours": 48,
      "distanceKm": 534.6,
      "freeKm": 720.0,
      "make": "Fiat",
      "model": "Ducato",
      "homeCity": "München"
    },
    {
      "offerId": "248020",
      "originName": "Berglern",
      "destName": "Hamburg",
      "startUtc": "2026-05-26T04:00:05Z",
      "endUtc": "2026-06-02T21:51:06Z",
      "periodHours": 48,
      "distanceKm": 788.1,
      "freeKm": 960.0,
      "make": "Fiat",
      "model": "Ducato",
      "homeCity": "München"
    },
    {
      "offerId": "248023",
      "originName": "Berglern",
      "destName": "Frankfurt am Main",
      "startUtc": "2026-05-26T04:00:05Z",
      "endUtc": "2026-06-01T21:51:06Z",
      "periodHours": 48,
      "distanceKm": 412.8,
      "freeKm": 720.0,
      "make": "Fiat",
      "model": "Ducato",
      "homeCity": "München"
    },
    {
      "offerId": "248033",
      "originName": "Berglern",
      "destName": "Florence",
      "startUtc": "2026-05-26T04:00:05Z",
      "endUtc": "2026-06-01T21:51:06Z",
      "periodHours": 48,
      "distanceKm": 660.8,
      "freeKm": 960.0,
      "make": "Fiat",
      "model": "Ducato",
      "homeCity": "München"
    },
    {
      "offerId": "248034",
      "originName": "Berglern",
      "destName": "Roma",
      "startUtc": "2026-05-26T04:00:05Z",
      "endUtc": "2026-06-03T21:51:06Z",
      "periodHours": 72,
      "distanceKm": 963.2,
      "freeKm": 1150.0,
      "make": "Fiat",
      "model": "Ducato",
      "homeCity": "München"
    },
    {
      "offerId": "248036",
      "originName": "Berglern",
      "destName": "Stuttgart",
      "startUtc": "2026-05-26T04:00:05Z",
      "endUtc": "2026-06-01T21:51:06Z",
      "periodHours": 24,
      "distanceKm": 244.9,
      "freeKm": 480.0,
      "make": "Fiat",
      "model": "Ducato",
      "homeCity": "München"
    },
    {
      "offerId": "247849",
      "originName": "Berglern",
      "destName": "Saint-Mesmes",
      "startUtc": "2026-05-27T04:00:05Z",
      "endUtc": "2026-06-03T21:51:06Z",
      "periodHours": 72,
      "distanceKm": 844.2,
      "freeKm": 1150.0,
      "make": "Fiat",
      "model": "Ducato",
      "homeCity": "München"
    },
    {
      "offerId": "244129",
      "originName": "Gersthofen",
      "destName": "Flensburg",
      "startUtc": "2026-05-28T22:00:00Z",
      "endUtc": "2026-06-05T21:59:59Z",
      "periodHours": 72,
      "distanceKm": 899.6,
      "freeKm": 1400.0,
      "make": "CAMPER CABIN",
      "model": "Ford Nugget - Ford Transit Custom V710",
      "homeCity": "München"
    },
    {
      "offerId": "247831",
      "originName": "München",
      "destName": "Venezia",
      "startUtc": "2026-06-02T22:00:00Z",
      "endUtc": "2026-06-10T21:59:59Z",
      "periodHours": 48,
      "distanceKm": 552.1,
      "freeKm": 1000.0,
      "make": "CAMPER CABIN DELUXE",
      "model": "Ford Nugget Plus - Ford Transit Custom V362",
      "homeCity": "München"
    },
    {
      "offerId": "244799",
      "originName": "Bochum",
      "destName": "Goussainville",
      "startUtc": "2026-06-03T22:00:00Z",
      "endUtc": "2026-06-11T21:59:59Z",
      "periodHours": 48,
      "distanceKm": 542.0,
      "freeKm": 1000.0,
      "make": "COUPLE COTTAGE",
      "model": "Weinsberg Signeo C590 - Ford Transit V363",
      "homeCity": "Bochum"
    },
    {
      "offerId": "248062",
      "originName": "Berglern",
      "destName": "Bologna",
      "startUtc": "2026-06-04T04:00:06Z",
      "endUtc": "2026-06-11T21:51:06Z",
      "periodHours": 48,
      "distanceKm": 580.4,
      "freeKm": 720.0,
      "make": "Fiat",
      "model": "Ducato",
      "homeCity": "München"
    },
    {
      "offerId": "245565",
      "originName": "Dormagen",
      "destName": "Goussainville",
      "startUtc": "2026-06-04T22:00:00Z",
      "endUtc": "2026-06-12T21:59:59Z",
      "periodHours": 48,
      "distanceKm": 481.7,
      "freeKm": 1000.0,
      "make": "ROAD HOUSE",
      "model": "Westfalia Eliseo C540 - Fiat Ducato 8",
      "homeCity": "Bochum"
    },
    {
      "offerId": "241199",
      "originName": "Weyhe",
      "destName": "Sint-Pieters-Leeuw",
      "startUtc": "2026-06-04T22:00:00Z",
      "endUtc": "2026-06-12T21:59:59Z",
      "periodHours": 48,
      "distanceKm": 504.7,
      "freeKm": 1000.0,
      "make": "COUPLE COTTAGE",
      "model": "Weinsberg Signeo C590 - Ford Transit V363",
      "homeCity": "Hannover"
    },
    {
      "offerId": "244273",
      "originName": "Weyhe",
      "destName": "Göteborgs Stad",
      "startUtc": "2026-06-04T22:00:00Z",
      "endUtc": "2026-06-12T21:59:59Z",
      "periodHours": 48,
      "distanceKm": 743.7,
      "freeKm": 1000.0,
      "make": "SUNRISE SUITE",
      "model": "VW California Ocean / Coast",
      "homeCity": "Hannover"
    },
    {
      "offerId": "245561",
      "originName": "Dormagen",
      "destName": "Nantes",
      "startUtc": "2026-06-05T22:00:00Z",
      "endUtc": "2026-06-13T21:59:59Z",
      "periodHours": 72,
      "distanceKm": 881.3,
      "freeKm": 1400.0,
      "make": "CAMPER CASTLE",
      "model": "Fiat Tracer 680DL - Fiat Ducato Serie 2",
      "homeCity": "Bochum"
    },
    {
      "offerId": "245571",
      "originName": "Dormagen",
      "destName": "Goussainville",
      "startUtc": "2026-06-05T22:00:00Z",
      "endUtc": "2026-06-13T21:59:59Z",
      "periodHours": 48,
      "distanceKm": 481.7,
      "freeKm": 1000.0,
      "make": "ROAD HOUSE",
      "model": "Westfalia Eliseo C540 - Fiat Ducato 8",
      "homeCity": "Bochum"
    },
    {
      "offerId": "245551",
      "originName": "Bochum",
      "destName": "Sint-Pieters-Leeuw",
      "startUtc": "2026-06-07T22:00:00Z",
      "endUtc": "2026-06-15T21:59:59Z",
      "periodHours": 24,
      "distanceKm": 279.2,
      "freeKm": 600.0,
      "make": "SURFER SUITE",
      "model": "VW California Ocean",
      "homeCity": "Bochum"
    },
    {
      "offerId": "245562",
      "originName": "Dormagen",
      "destName": "Mérignac",
      "startUtc": "2026-06-07T22:00:00Z",
      "endUtc": "2026-06-15T21:59:59Z",
      "periodHours": 72,
      "distanceKm": 1091.9,
      "freeKm": 1400.0,
      "make": "CAMPER CABIN",
      "model": "Ford Nugget - Ford Transit Custom V710",
      "homeCity": "Bochum"
    },
    {
      "offerId": "245569",
      "originName": "Dormagen",
      "destName": "Dagneux",
      "startUtc": "2026-06-07T22:00:00Z",
      "endUtc": "2026-06-15T21:59:59Z",
      "periodHours": 48,
      "distanceKm": 745.4,
      "freeKm": 1000.0,
      "make": "CAMPER CABIN",
      "model": "Ford Nugget - Ford Transit Custom V710",
      "homeCity": "Bochum"
    },
    {
      "offerId": "247670",
      "originName": "Dormagen",
      "destName": "Leipzig",
      "startUtc": "2026-06-07T22:00:00Z",
      "endUtc": "2026-06-15T21:59:59Z",
      "periodHours": 48,
      "distanceKm": 502.4,
      "freeKm": 1000.0,
      "make": "BEACH HOSTEL",
      "model": "VW California Beach",
      "homeCity": "Bochum"
    },
    {
      "offerId": "245555",
      "originName": "Weyhe",
      "destName": "Staffanstorps kommun",
      "startUtc": "2026-06-07T22:00:00Z",
      "endUtc": "2026-06-15T21:59:59Z",
      "periodHours": 48,
      "distanceKm": 484.1,
      "freeKm": 1000.0,
      "make": "COUPLE COTTAGE",
      "model": "Weinsberg Signeo C590 - Ford Transit V363",
      "homeCity": "Hannover"
    },
    {
      "offerId": "244851",
      "originName": "München",
      "destName": "Dagneux",
      "startUtc": "2026-06-07T22:00:00Z",
      "endUtc": "2026-06-15T21:59:59Z",
      "periodHours": 48,
      "distanceKm": 723.3,
      "freeKm": 1000.0,
      "make": "ROAD HOUSE",
      "model": "Westfalia Eliseo C540 - Fiat Ducato 8",
      "homeCity": "München"
    },
    {
      "offerId": "248060",
      "originName": "Berglern",
      "destName": "Warszawa",
      "startUtc": "2026-06-09T04:00:06Z",
      "endUtc": "2026-06-18T21:51:06Z",
      "periodHours": 72,
      "distanceKm": 1048.8,
      "freeKm": 1380.0,
      "make": "Fiat",
      "model": "Ducato",
      "homeCity": "München"
    },
    {
      "offerId": "247669",
      "originName": "Dormagen",
      "destName": "Dagneux",
      "startUtc": "2026-06-09T22:00:00Z",
      "endUtc": "2026-06-17T21:59:59Z",
      "periodHours": 48,
      "distanceKm": 745.4,
      "freeKm": 1000.0,
      "make": "ROAD HOUSE",
      "model": "Westfalia Eliseo C540 - Fiat Ducato 8",
      "homeCity": "Bochum"
    },
    {
      "offerId": "244803",
      "originName": "Weyhe",
      "destName": "Sint-Pieters-Leeuw",
      "startUtc": "2026-06-09T22:00:00Z",
      "endUtc": "2026-06-17T21:59:59Z",
      "periodHours": 48,
      "distanceKm": 504.7,
      "freeKm": 1000.0,
      "make": "CAMPER CABIN",
      "model": "Ford Nugget - Ford Transit Custom V710",
      "homeCity": "Hannover"
    },
    {
      "offerId": "246304",
      "originName": "Bochum",
      "destName": "Saint-Jean-de-Gonville",
      "startUtc": "2026-06-11T22:00:00Z",
      "endUtc": "2026-06-19T21:59:59Z",
      "periodHours": 72,
      "distanceKm": 801.0,
      "freeKm": 1400.0,
      "make": "TRAVEL HOME",
      "model": "Mercedes Benz Marco Polo - V-Klasse",
      "homeCity": "Bochum"
    },
    {
      "offerId": "245528",
      "originName": "Gersthofen",
      "destName": "Roma",
      "startUtc": "2026-06-11T22:00:00Z",
      "endUtc": "2026-06-19T21:59:59Z",
      "periodHours": 72,
      "distanceKm": 988.8,
      "freeKm": 1400.0,
      "make": "ROAD HOUSE",
      "model": "Westfalia Eliseo C540 - Fiat Ducato 8",
      "homeCity": "München"
    },
    {
      "offerId": "246813",
      "originName": "Bochum",
      "destName": "Saint-Jean-de-Gonville",
      "startUtc": "2026-06-14T22:00:00Z",
      "endUtc": "2026-06-22T21:59:59Z",
      "periodHours": 72,
      "distanceKm": 801.0,
      "freeKm": 1400.0,
      "make": "COUPLE COTTAGE",
      "model": "Weinsberg Signeo C590 - Ford Transit V363",
      "homeCity": "Bochum"
    },
    {
      "offerId": "245554",
      "originName": "Weyhe",
      "destName": "Staffanstorps kommun",
      "startUtc": "2026-06-14T22:00:00Z",
      "endUtc": "2026-06-22T21:59:59Z",
      "periodHours": 48,
      "distanceKm": 484.1,
      "freeKm": 1000.0,
      "make": "CAMPER CASTLE",
      "model": "Fiat Tracer 680DL - Fiat Ducato Serie 2",
      "homeCity": "Hannover"
    },
    {
      "offerId": "245558",
      "originName": "Weyhe",
      "destName": "Staffanstorps kommun",
      "startUtc": "2026-06-15T22:00:00Z",
      "endUtc": "2026-06-23T21:59:59Z",
      "periodHours": 48,
      "distanceKm": 484.1,
      "freeKm": 1000.0,
      "make": "COUPLE COTTAGE",
      "model": "Weinsberg Signeo C590 - Ford Transit V363",
      "homeCity": "Hannover"
    },
    {
      "offerId": "247208",
      "originName": "Dormagen",
      "destName": "Mérignac",
      "startUtc": "2026-06-22T22:00:00Z",
      "endUtc": "2026-06-30T21:59:59Z",
      "periodHours": 72,
      "distanceKm": 1091.9,
      "freeKm": 1400.0,
      "make": "SUNRISE SUITE",
      "model": "VW California Ocean / Coast",
      "homeCity": "Bochum"
    },
    {
      "offerId": "244805",
      "originName": "Weyhe",
      "destName": "Sint-Pieters-Leeuw",
      "startUtc": "2026-06-22T22:00:00Z",
      "endUtc": "2026-06-30T21:59:59Z",
      "periodHours": 48,
      "distanceKm": 504.7,
      "freeKm": 1000.0,
      "make": "SUNRISE SUITE",
      "model": "VW California Ocean / Coast",
      "homeCity": "Hannover"
    },
    {
      "offerId": "247666",
      "originName": "Weyhe",
      "destName": "Wien",
      "startUtc": "2026-06-23T22:00:00Z",
      "endUtc": "2026-07-01T21:59:59Z",
      "periodHours": 72,
      "distanceKm": 925.5,
      "freeKm": 1400.0,
      "make": "SUNRISE SUITE",
      "model": "VW California Ocean / Coast",
      "homeCity": "Hannover"
    },
    {
      "offerId": "246792",
      "originName": "München",
      "destName": "Venezia",
      "startUtc": "2026-06-26T22:00:00Z",
      "endUtc": "2026-07-04T21:59:59Z",
      "periodHours": 48,
      "distanceKm": 552.1,
      "freeKm": 1000.0,
      "make": "SURFER SUITE",
      "model": "VW California Ocean",
      "homeCity": "München"
    },
    {
      "offerId": "247241",
      "originName": "Gersthofen",
      "destName": "Castellanza",
      "startUtc": "2026-06-26T22:00:00Z",
      "endUtc": "2026-07-04T21:59:59Z",
      "periodHours": 48,
      "distanceKm": 469.6,
      "freeKm": 1000.0,
      "make": "SUNRISE SUITE",
      "model": "VW California Ocean / Coast",
      "homeCity": "München"
    }
  ],
  "recommended": [
    {
      "score": 153.4,
      "route": [
        "Berglern",
        "Florence",
        "Lyon",
        "Saint-Mesmes"
      ],
      "legs": [
        {
          "originName": "Berglern",
          "destName": "Florence",
          "pickup": "2026-05-26T06:00:05+02:00",
          "dropoff": "2026-05-28T06:00:05+02:00",
          "vehicle": "Fiat Ducato",
          "make": "Fiat",
          "model": "Ducato",
          "distanceKm": 660.8,
          "offerId": "248033"
        },
        {
          "originName": "Florence",
          "destName": "Lyon",
          "pickup": "2026-05-27T06:00:05+02:00",
          "dropoff": "2026-05-29T06:00:05+02:00",
          "vehicle": "Fiat S 75SL / T 7400 SB or similar",
          "make": "Fiat",
          "model": "S 75SL / T 7400 SB or similar",
          "distanceKm": 692.1,
          "offerId": "247838"
        },
        {
          "originName": "Lyon",
          "destName": "Saint-Mesmes",
          "pickup": "2026-05-29T06:00:05+02:00",
          "dropoff": "2026-05-31T06:00:05+02:00",
          "vehicle": "Volkswagen California",
          "make": "Volkswagen",
          "model": "California",
          "distanceKm": 526.4,
          "offerId": "247854"
        }
      ],
      "type": "oneway",
      "homeCity": "München",
      "startUtc": "2026-05-26T06:00:05+02:00",
      "endUtc": "2026-05-31T06:00:05+02:00",
      "days": 5.0,
      "routeKm": 1879.0,
      "freeKm": 2640.0,
      "spareKm": 761.0,
      "driveHours": 22.105882352941176,
      "countries": [
        "Germany",
        "Italy",
        "France"
      ],
      "appointment": "26 May – 31 May · Berglern → Saint-Mesmes"
    },
    {
      "score": 142.8,
      "route": [
        "Berglern",
        "Florence",
        "Lyon"
      ],
      "legs": [
        {
          "originName": "Berglern",
          "destName": "Florence",
          "pickup": "2026-05-26T06:00:05+02:00",
          "dropoff": "2026-05-28T06:00:05+02:00",
          "vehicle": "Fiat Ducato",
          "make": "Fiat",
          "model": "Ducato",
          "distanceKm": 660.8,
          "offerId": "248033"
        },
        {
          "originName": "Florence",
          "destName": "Lyon",
          "pickup": "2026-05-29T06:00:05+02:00",
          "dropoff": "2026-05-31T06:00:05+02:00",
          "vehicle": "Fiat S 75SL / T 7400 SB or similar",
          "make": "Fiat",
          "model": "S 75SL / T 7400 SB or similar",
          "distanceKm": 692.1,
          "offerId": "247838"
        }
      ],
      "type": "oneway",
      "homeCity": "München",
      "startUtc": "2026-05-26T06:00:05+02:00",
      "endUtc": "2026-05-31T06:00:05+02:00",
      "days": 5.0,
      "routeKm": 1353.0,
      "freeKm": 1920.0,
      "spareKm": 567.0,
      "driveHours": 15.91764705882353,
      "countries": [
        "Germany",
        "Italy",
        "France"
      ],
      "appointment": "26 May – 31 May · Berglern → Lyon"
    },
    {
      "score": 142.6,
      "route": [
        "Berglern",
        "Florence",
        "Cagliari"
      ],
      "legs": [
        {
          "originName": "Berglern",
          "destName": "Florence",
          "pickup": "2026-05-26T06:00:05+02:00",
          "dropoff": "2026-05-28T06:00:05+02:00",
          "vehicle": "Fiat Ducato",
          "make": "Fiat",
          "model": "Ducato",
          "distanceKm": 660.8,
          "offerId": "248033"
        },
        {
          "originName": "Florence",
          "destName": "Cagliari",
          "pickup": "2026-05-29T06:00:05+02:00",
          "dropoff": "2026-05-31T06:00:05+02:00",
          "vehicle": "Fiat Ducato",
          "make": "Fiat",
          "model": "Ducato",
          "distanceKm": 649.4,
          "offerId": "247934"
        }
      ],
      "type": "oneway",
      "homeCity": "München",
      "startUtc": "2026-05-26T06:00:05+02:00",
      "endUtc": "2026-05-31T06:00:05+02:00",
      "days": 5.0,
      "routeKm": 1310.0,
      "freeKm": 1920.0,
      "spareKm": 610.0,
      "driveHours": 15.411764705882353,
      "countries": [
        "Germany",
        "Italy",
        "Europe"
      ],
      "appointment": "26 May – 31 May · Berglern → Cagliari"
    },
    {
      "score": 141.3,
      "route": [
        "Berglern",
        "Florence",
        "Olbia"
      ],
      "legs": [
        {
          "originName": "Berglern",
          "destName": "Florence",
          "pickup": "2026-05-26T06:00:05+02:00",
          "dropoff": "2026-05-28T06:00:05+02:00",
          "vehicle": "Fiat Ducato",
          "make": "Fiat",
          "model": "Ducato",
          "distanceKm": 660.8,
          "offerId": "248033"
        },
        {
          "originName": "Florence",
          "destName": "Olbia",
          "pickup": "2026-05-30T06:00:05+02:00",
          "dropoff": "2026-05-31T06:00:05+02:00",
          "vehicle": "Fiat Ducato",
          "make": "Fiat",
          "model": "Ducato",
          "distanceKm": 396.0,
          "offerId": "247950"
        }
      ],
      "type": "oneway",
      "homeCity": "München",
      "startUtc": "2026-05-26T06:00:05+02:00",
      "endUtc": "2026-05-31T06:00:05+02:00",
      "days": 5.0,
      "routeKm": 1057.0,
      "freeKm": 1440.0,
      "spareKm": 383.0,
      "driveHours": 12.435294117647059,
      "countries": [
        "Germany",
        "Italy",
        "Europe"
      ],
      "appointment": "26 May – 31 May · Berglern → Olbia"
    },
    {
      "score": 141.0,
      "route": [
        "Berglern",
        "Florence",
        "Milan"
      ],
      "legs": [
        {
          "originName": "Berglern",
          "destName": "Florence",
          "pickup": "2026-05-26T06:00:05+02:00",
          "dropoff": "2026-05-28T06:00:05+02:00",
          "vehicle": "Fiat Ducato",
          "make": "Fiat",
          "model": "Ducato",
          "distanceKm": 660.8,
          "offerId": "248033"
        },
        {
          "originName": "Florence",
          "destName": "Milan",
          "pickup": "2026-05-30T06:00:05+02:00",
          "dropoff": "2026-05-31T06:00:05+02:00",
          "vehicle": "Fiat S 75SL / T 7400 SB or similar",
          "make": "Fiat",
          "model": "S 75SL / T 7400 SB or similar",
          "distanceKm": 345.7,
          "offerId": "247931"
        }
      ],
      "type": "oneway",
      "homeCity": "München",
      "startUtc": "2026-05-26T06:00:05+02:00",
      "endUtc": "2026-05-31T06:00:05+02:00",
      "days": 5.0,
      "routeKm": 1006.0,
      "freeKm": 1440.0,
      "spareKm": 434.0,
      "driveHours": 11.83529411764706,
      "countries": [
        "Germany",
        "Italy"
      ],
      "appointment": "26 May – 31 May · Berglern → Milan"
    },
    {
      "score": 140.9,
      "route": [
        "Berglern",
        "Florence",
        "Bergamo"
      ],
      "legs": [
        {
          "originName": "Berglern",
          "destName": "Florence",
          "pickup": "2026-05-26T06:00:05+02:00",
          "dropoff": "2026-05-28T06:00:05+02:00",
          "vehicle": "Fiat Ducato",
          "make": "Fiat",
          "model": "Ducato",
          "distanceKm": 660.8,
          "offerId": "248033"
        },
        {
          "originName": "Florence",
          "destName": "Bergamo",
          "pickup": "2026-05-30T06:00:05+02:00",
          "dropoff": "2026-05-31T06:00:05+02:00",
          "vehicle": "Fiat S 75SL / T 7400 SB or similar",
          "make": "Fiat",
          "model": "S 75SL / T 7400 SB or similar",
          "distanceKm": 325.4,
          "offerId": "247946"
        }
      ],
      "type": "oneway",
      "homeCity": "München",
      "startUtc": "2026-05-26T06:00:05+02:00",
      "endUtc": "2026-05-31T06:00:05+02:00",
      "days": 5.0,
      "routeKm": 986.0,
      "freeKm": 1440.0,
      "spareKm": 454.0,
      "driveHours": 11.6,
      "countries": [
        "Germany",
        "Italy"
      ],
      "appointment": "26 May – 31 May · Berglern → Bergamo"
    },
    {
      "score": 140.7,
      "route": [
        "Berglern",
        "Florence",
        "Bastia"
      ],
      "legs": [
        {
          "originName": "Berglern",
          "destName": "Florence",
          "pickup": "2026-05-26T06:00:05+02:00",
          "dropoff": "2026-05-28T06:00:05+02:00",
          "vehicle": "Fiat Ducato",
          "make": "Fiat",
          "model": "Ducato",
          "distanceKm": 660.8,
          "offerId": "248033"
        },
        {
          "originName": "Florence",
          "destName": "Bastia",
          "pickup": "2026-05-30T06:00:05+02:00",
          "dropoff": "2026-05-31T06:00:05+02:00",
          "vehicle": "Fiat Ducato",
          "make": "Fiat",
          "model": "Ducato",
          "distanceKm": 281.3,
          "offerId": "247836"
        }
      ],
      "type": "oneway",
      "homeCity": "München",
      "startUtc": "2026-05-26T06:00:05+02:00",
      "endUtc": "2026-05-31T06:00:05+02:00",
      "days": 5.0,
      "routeKm": 942.0,
      "freeKm": 1440.0,
      "spareKm": 498.0,
      "driveHours": 11.08235294117647,
      "countries": [
        "Germany",
        "Italy"
      ],
      "appointment": "26 May – 31 May · Berglern → Bastia"
    },
    {
      "score": 140.2,
      "route": [
        "Berglern",
        "Bologna",
        "Milan"
      ],
      "legs": [
        {
          "originName": "Berglern",
          "destName": "Bologna",
          "pickup": "2026-05-26T06:00:05+02:00",
          "dropoff": "2026-05-28T06:00:05+02:00",
          "vehicle": "Fiat Ducato",
          "make": "Fiat",
          "model": "Ducato",
          "distanceKm": 580.4,
          "offerId": "247941"
        },
        {
          "originName": "Bologna",
          "destName": "Milan",
          "pickup": "2026-05-30T06:00:05+02:00",
          "dropoff": "2026-05-31T06:00:05+02:00",
          "vehicle": "Fiat S 75SL / T 7400 SB or similar",
          "make": "Fiat",
          "model": "S 75SL / T 7400 SB or similar",
          "distanceKm": 263.8,
          "offerId": "247936"
        }
      ],
      "type": "oneway",
      "homeCity": "München",
      "startUtc": "2026-05-26T06:00:05+02:00",
      "endUtc": "2026-05-31T06:00:05+02:00",
      "days": 5.0,
      "routeKm": 844.0,
      "freeKm": 1200.0,
      "spareKm": 356.0,
      "driveHours": 9.929411764705883,
      "countries": [
        "Germany",
        "Italy"
      ],
      "appointment": "26 May – 31 May · Berglern → Milan"
    },
    {
      "score": 129.8,
      "route": [
        "Nantes",
        "Bergamo"
      ],
      "legs": [
        {
          "originName": "Nantes",
          "destName": "Bergamo",
          "pickup": "2026-05-26T06:00:05+02:00",
          "dropoff": "2026-05-29T06:00:05+02:00",
          "vehicle": "Pilote G690 GJ or similar",
          "make": "Pilote",
          "model": "G690 GJ or similar",
          "distanceKm": 1164.9,
          "offerId": "247963"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-26T06:00:05+02:00",
      "endUtc": "2026-05-29T06:00:05+02:00",
      "days": 3.0,
      "routeKm": 1165.0,
      "freeKm": 1380.0,
      "spareKm": 215.0,
      "driveHours": 13.705882352941176,
      "countries": [
        "France",
        "Italy"
      ],
      "appointment": "26 May – 29 May · Nantes → Bergamo"
    },
    {
      "score": 129.6,
      "route": [
        "Nantes",
        "Milan"
      ],
      "legs": [
        {
          "originName": "Nantes",
          "destName": "Milan",
          "pickup": "2026-05-26T06:00:05+02:00",
          "dropoff": "2026-05-29T06:00:05+02:00",
          "vehicle": "Pilote G690 GJ or similar",
          "make": "Pilote",
          "model": "G690 GJ or similar",
          "distanceKm": 1118.6,
          "offerId": "247937"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-26T06:00:05+02:00",
      "endUtc": "2026-05-29T06:00:05+02:00",
      "days": 3.0,
      "routeKm": 1119.0,
      "freeKm": 1380.0,
      "spareKm": 261.0,
      "driveHours": 13.16470588235294,
      "countries": [
        "France",
        "Italy"
      ],
      "appointment": "26 May – 29 May · Nantes → Milan"
    },
    {
      "score": 129.5,
      "route": [
        "Dormagen",
        "Mérignac"
      ],
      "legs": [
        {
          "originName": "Dormagen",
          "destName": "Mérignac",
          "pickup": "2026-06-08T00:00:00+02:00",
          "dropoff": "2026-06-11T00:00:00+02:00",
          "vehicle": "CAMPER CABIN Ford Nugget - Ford Transit Custom V710",
          "make": "CAMPER CABIN",
          "model": "Ford Nugget - Ford Transit Custom V710",
          "distanceKm": 1091.9,
          "offerId": "245562"
        }
      ],
      "type": "oneway",
      "homeCity": "Bochum",
      "startUtc": "2026-06-08T00:00:00+02:00",
      "endUtc": "2026-06-11T00:00:00+02:00",
      "days": 3.0,
      "routeKm": 1092.0,
      "freeKm": 1400.0,
      "spareKm": 308.0,
      "driveHours": 12.847058823529412,
      "countries": [
        "Germany",
        "France"
      ],
      "appointment": "08 Jun – 11 Jun · Dormagen → Mérignac"
    },
    {
      "score": 129.1,
      "route": [
        "Nantes",
        "Madrid"
      ],
      "legs": [
        {
          "originName": "Nantes",
          "destName": "Madrid",
          "pickup": "2026-05-26T06:00:05+02:00",
          "dropoff": "2026-05-29T06:00:05+02:00",
          "vehicle": "Pilote G690 GJ or similar",
          "make": "Pilote",
          "model": "G690 GJ or similar",
          "distanceKm": 1024.4,
          "offerId": "247856"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-26T06:00:05+02:00",
      "endUtc": "2026-05-29T06:00:05+02:00",
      "days": 3.0,
      "routeKm": 1024.0,
      "freeKm": 1380.0,
      "spareKm": 356.0,
      "driveHours": 12.047058823529412,
      "countries": [
        "France",
        "Spain"
      ],
      "appointment": "26 May – 29 May · Nantes → Madrid"
    },
    {
      "score": 128.9,
      "route": [
        "Gersthofen",
        "Roma"
      ],
      "legs": [
        {
          "originName": "Gersthofen",
          "destName": "Roma",
          "pickup": "2026-06-12T00:00:00+02:00",
          "dropoff": "2026-06-15T00:00:00+02:00",
          "vehicle": "ROAD HOUSE Westfalia Eliseo C540 - Fiat Ducato 8",
          "make": "ROAD HOUSE",
          "model": "Westfalia Eliseo C540 - Fiat Ducato 8",
          "distanceKm": 988.8,
          "offerId": "245528"
        }
      ],
      "type": "oneway",
      "homeCity": "München",
      "startUtc": "2026-06-12T00:00:00+02:00",
      "endUtc": "2026-06-15T00:00:00+02:00",
      "days": 3.0,
      "routeKm": 989.0,
      "freeKm": 1400.0,
      "spareKm": 411.0,
      "driveHours": 11.635294117647058,
      "countries": [
        "Germany",
        "Italy"
      ],
      "appointment": "12 Jun – 15 Jun · Gersthofen → Roma"
    },
    {
      "score": 128.9,
      "route": [
        "Nantes",
        "Barcelona"
      ],
      "legs": [
        {
          "originName": "Nantes",
          "destName": "Barcelona",
          "pickup": "2026-05-26T06:00:05+02:00",
          "dropoff": "2026-05-29T06:00:05+02:00",
          "vehicle": "Pilote G690 GJ or similar",
          "make": "Pilote",
          "model": "G690 GJ or similar",
          "distanceKm": 984.8,
          "offerId": "247860"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-26T06:00:05+02:00",
      "endUtc": "2026-05-29T06:00:05+02:00",
      "days": 3.0,
      "routeKm": 985.0,
      "freeKm": 1150.0,
      "spareKm": 165.0,
      "driveHours": 11.588235294117647,
      "countries": [
        "France",
        "Spain"
      ],
      "appointment": "26 May – 29 May · Nantes → Barcelona"
    },
    {
      "score": 128.8,
      "route": [
        "Berglern",
        "Roma"
      ],
      "legs": [
        {
          "originName": "Berglern",
          "destName": "Roma",
          "pickup": "2026-05-26T06:00:05+02:00",
          "dropoff": "2026-05-29T06:00:05+02:00",
          "vehicle": "Fiat Ducato",
          "make": "Fiat",
          "model": "Ducato",
          "distanceKm": 963.2,
          "offerId": "248034"
        }
      ],
      "type": "oneway",
      "homeCity": "München",
      "startUtc": "2026-05-26T06:00:05+02:00",
      "endUtc": "2026-05-29T06:00:05+02:00",
      "days": 3.0,
      "routeKm": 963.0,
      "freeKm": 1150.0,
      "spareKm": 187.0,
      "driveHours": 11.329411764705883,
      "countries": [
        "Germany",
        "Italy"
      ],
      "appointment": "26 May – 29 May · Berglern → Roma"
    },
    {
      "score": 128.6,
      "route": [
        "Weyhe",
        "Wien"
      ],
      "legs": [
        {
          "originName": "Weyhe",
          "destName": "Wien",
          "pickup": "2026-06-24T00:00:00+02:00",
          "dropoff": "2026-06-27T00:00:00+02:00",
          "vehicle": "SUNRISE SUITE VW California Ocean / Coast",
          "make": "SUNRISE SUITE",
          "model": "VW California Ocean / Coast",
          "distanceKm": 925.5,
          "offerId": "247666"
        }
      ],
      "type": "oneway",
      "homeCity": "Hannover",
      "startUtc": "2026-06-24T00:00:00+02:00",
      "endUtc": "2026-06-27T00:00:00+02:00",
      "days": 3.0,
      "routeKm": 926.0,
      "freeKm": 1400.0,
      "spareKm": 474.0,
      "driveHours": 10.894117647058824,
      "countries": [
        "Germany",
        "Austria"
      ],
      "appointment": "24 Jun – 27 Jun · Weyhe → Wien"
    },
    {
      "score": 128.0,
      "route": [
        "Marburg",
        "Graz"
      ],
      "legs": [
        {
          "originName": "Marburg",
          "destName": "Graz",
          "pickup": "2026-05-23T00:00:00+02:00",
          "dropoff": "2026-05-26T00:00:00+02:00",
          "vehicle": "CAMPER CABIN DELUXE Ford Nugget Plus - Ford Transit Custom V362",
          "make": "CAMPER CABIN DELUXE",
          "model": "Ford Nugget Plus - Ford Transit Custom V362",
          "distanceKm": 807.8,
          "offerId": "245064"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-23T00:00:00+02:00",
      "endUtc": "2026-05-26T00:00:00+02:00",
      "days": 3.0,
      "routeKm": 808.0,
      "freeKm": 1400.0,
      "spareKm": 592.0,
      "driveHours": 9.505882352941176,
      "countries": [
        "Germany",
        "Austria"
      ],
      "appointment": "23 May – 26 May · Marburg → Graz"
    },
    {
      "score": 128.0,
      "route": [
        "Bochum",
        "Saint-Jean-de-Gonville"
      ],
      "legs": [
        {
          "originName": "Bochum",
          "destName": "Saint-Jean-de-Gonville",
          "pickup": "2026-06-12T00:00:00+02:00",
          "dropoff": "2026-06-15T00:00:00+02:00",
          "vehicle": "TRAVEL HOME Mercedes Benz Marco Polo - V-Klasse",
          "make": "TRAVEL HOME",
          "model": "Mercedes Benz Marco Polo - V-Klasse",
          "distanceKm": 801.0,
          "offerId": "246304"
        }
      ],
      "type": "oneway",
      "homeCity": "Bochum",
      "startUtc": "2026-06-12T00:00:00+02:00",
      "endUtc": "2026-06-15T00:00:00+02:00",
      "days": 3.0,
      "routeKm": 801.0,
      "freeKm": 1400.0,
      "spareKm": 599.0,
      "driveHours": 9.423529411764706,
      "countries": [
        "Germany",
        "France"
      ],
      "appointment": "12 Jun – 15 Jun · Bochum → Saint-Jean-de-Gonville"
    },
    {
      "score": 126.6,
      "route": [
        "Berlin",
        "Bochum",
        "Saint-Jean-de-Gonville"
      ],
      "legs": [
        {
          "originName": "Berlin",
          "destName": "Bochum",
          "pickup": "2026-06-01T23:59:59+02:00",
          "dropoff": "2026-06-03T23:59:59+02:00",
          "vehicle": "COZY COTTAGE Knaus Van TI Plus 650 MEG Platinum Selection - VW Crafter 2",
          "make": "COZY COTTAGE",
          "model": "Knaus Van TI Plus 650 MEG Platinum Selection - VW Crafter 2",
          "distanceKm": 512.1,
          "offerId": "243325"
        },
        {
          "originName": "Bochum",
          "destName": "Saint-Jean-de-Gonville",
          "pickup": "2026-06-12T00:00:00+02:00",
          "dropoff": "2026-06-15T00:00:00+02:00",
          "vehicle": "TRAVEL HOME Mercedes Benz Marco Polo - V-Klasse",
          "make": "TRAVEL HOME",
          "model": "Mercedes Benz Marco Polo - V-Klasse",
          "distanceKm": 801.0,
          "offerId": "246304"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-06-01T23:59:59+02:00",
      "endUtc": "2026-06-15T00:00:00+02:00",
      "days": 13.0,
      "routeKm": 1313.0,
      "freeKm": 2400.0,
      "spareKm": 1087.0,
      "driveHours": 15.447058823529412,
      "countries": [
        "Germany",
        "France"
      ],
      "appointment": "01 Jun – 15 Jun · Berlin → Saint-Jean-de-Gonville"
    },
    {
      "score": 125.7,
      "route": [
        "Dormagen",
        "Dagneux"
      ],
      "legs": [
        {
          "originName": "Dormagen",
          "destName": "Dagneux",
          "pickup": "2026-06-08T00:00:00+02:00",
          "dropoff": "2026-06-10T00:00:00+02:00",
          "vehicle": "CAMPER CABIN Ford Nugget - Ford Transit Custom V710",
          "make": "CAMPER CABIN",
          "model": "Ford Nugget - Ford Transit Custom V710",
          "distanceKm": 745.4,
          "offerId": "245569"
        }
      ],
      "type": "oneway",
      "homeCity": "Bochum",
      "startUtc": "2026-06-08T00:00:00+02:00",
      "endUtc": "2026-06-10T00:00:00+02:00",
      "days": 2.0,
      "routeKm": 745.0,
      "freeKm": 1000.0,
      "spareKm": 255.0,
      "driveHours": 8.764705882352942,
      "countries": [
        "Germany",
        "France"
      ],
      "appointment": "08 Jun – 10 Jun · Dormagen → Dagneux"
    },
    {
      "score": 125.6,
      "route": [
        "München",
        "Dagneux"
      ],
      "legs": [
        {
          "originName": "München",
          "destName": "Dagneux",
          "pickup": "2026-06-08T00:00:00+02:00",
          "dropoff": "2026-06-10T00:00:00+02:00",
          "vehicle": "ROAD HOUSE Westfalia Eliseo C540 - Fiat Ducato 8",
          "make": "ROAD HOUSE",
          "model": "Westfalia Eliseo C540 - Fiat Ducato 8",
          "distanceKm": 723.3,
          "offerId": "244851"
        }
      ],
      "type": "oneway",
      "homeCity": "München",
      "startUtc": "2026-06-08T00:00:00+02:00",
      "endUtc": "2026-06-10T00:00:00+02:00",
      "days": 2.0,
      "routeKm": 723.0,
      "freeKm": 1000.0,
      "spareKm": 277.0,
      "driveHours": 8.505882352941176,
      "countries": [
        "Germany",
        "France"
      ],
      "appointment": "08 Jun – 10 Jun · München → Dagneux"
    },
    {
      "score": 125.4,
      "route": [
        "Amstelveen",
        "Stuttgart"
      ],
      "legs": [
        {
          "originName": "Amstelveen",
          "destName": "Stuttgart",
          "pickup": "2026-05-26T06:00:05+02:00",
          "dropoff": "2026-05-28T06:00:05+02:00",
          "vehicle": "Volkswagen California",
          "make": "Volkswagen",
          "model": "California",
          "distanceKm": 681.9,
          "offerId": "247929"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-26T06:00:05+02:00",
      "endUtc": "2026-05-28T06:00:05+02:00",
      "days": 2.0,
      "routeKm": 682.0,
      "freeKm": 960.0,
      "spareKm": 278.0,
      "driveHours": 8.023529411764706,
      "countries": [
        "Europe",
        "Germany"
      ],
      "appointment": "26 May – 28 May · Amstelveen → Stuttgart"
    },
    {
      "score": 125.4,
      "route": [
        "Nantes",
        "Bilbao"
      ],
      "legs": [
        {
          "originName": "Nantes",
          "destName": "Bilbao",
          "pickup": "2026-05-26T06:00:05+02:00",
          "dropoff": "2026-05-28T06:00:05+02:00",
          "vehicle": "Pilote G690 GJ or similar",
          "make": "Pilote",
          "model": "G690 GJ or similar",
          "distanceKm": 670.5,
          "offerId": "247837"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-26T06:00:05+02:00",
      "endUtc": "2026-05-28T06:00:05+02:00",
      "days": 2.0,
      "routeKm": 670.0,
      "freeKm": 960.0,
      "spareKm": 290.0,
      "driveHours": 7.882352941176471,
      "countries": [
        "France",
        "Spain"
      ],
      "appointment": "26 May – 28 May · Nantes → Bilbao"
    },
    {
      "score": 125.3,
      "route": [
        "Bordeaux",
        "Barcelona"
      ],
      "legs": [
        {
          "originName": "Bordeaux",
          "destName": "Barcelona",
          "pickup": "2026-05-26T06:00:05+02:00",
          "dropoff": "2026-05-28T06:00:05+02:00",
          "vehicle": "Fiat Sport 346 or similar",
          "make": "Fiat",
          "model": "Sport 346 or similar",
          "distanceKm": 662.2,
          "offerId": "247844"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-26T06:00:05+02:00",
      "endUtc": "2026-05-28T06:00:05+02:00",
      "days": 2.0,
      "routeKm": 662.0,
      "freeKm": 960.0,
      "spareKm": 298.0,
      "driveHours": 7.788235294117647,
      "countries": [
        "France",
        "Spain"
      ],
      "appointment": "26 May – 28 May · Bordeaux → Barcelona"
    },
    {
      "score": 125.3,
      "route": [
        "Berglern",
        "Florence"
      ],
      "legs": [
        {
          "originName": "Berglern",
          "destName": "Florence",
          "pickup": "2026-05-26T06:00:05+02:00",
          "dropoff": "2026-05-28T06:00:05+02:00",
          "vehicle": "Fiat Ducato",
          "make": "Fiat",
          "model": "Ducato",
          "distanceKm": 660.8,
          "offerId": "248033"
        }
      ],
      "type": "oneway",
      "homeCity": "München",
      "startUtc": "2026-05-26T06:00:05+02:00",
      "endUtc": "2026-05-28T06:00:05+02:00",
      "days": 2.0,
      "routeKm": 661.0,
      "freeKm": 960.0,
      "spareKm": 299.0,
      "driveHours": 7.776470588235294,
      "countries": [
        "Germany",
        "Italy"
      ],
      "appointment": "26 May – 28 May · Berglern → Florence"
    },
    {
      "score": 124.9,
      "route": [
        "Berglern",
        "Bologna"
      ],
      "legs": [
        {
          "originName": "Berglern",
          "destName": "Bologna",
          "pickup": "2026-05-26T06:00:05+02:00",
          "dropoff": "2026-05-28T06:00:05+02:00",
          "vehicle": "Fiat Ducato",
          "make": "Fiat",
          "model": "Ducato",
          "distanceKm": 580.4,
          "offerId": "247941"
        }
      ],
      "type": "oneway",
      "homeCity": "München",
      "startUtc": "2026-05-26T06:00:05+02:00",
      "endUtc": "2026-05-28T06:00:05+02:00",
      "days": 2.0,
      "routeKm": 580.0,
      "freeKm": 720.0,
      "spareKm": 140.0,
      "driveHours": 6.823529411764706,
      "countries": [
        "Germany",
        "Italy"
      ],
      "appointment": "26 May – 28 May · Berglern → Bologna"
    },
    {
      "score": 124.8,
      "route": [
        "Berglern",
        "Venezia"
      ],
      "legs": [
        {
          "originName": "Berglern",
          "destName": "Venezia",
          "pickup": "2026-05-26T06:00:05+02:00",
          "dropoff": "2026-05-28T06:00:05+02:00",
          "vehicle": "Fiat Ducato",
          "make": "Fiat",
          "model": "Ducato",
          "distanceKm": 560.0,
          "offerId": "247930"
        }
      ],
      "type": "oneway",
      "homeCity": "München",
      "startUtc": "2026-05-26T06:00:05+02:00",
      "endUtc": "2026-05-28T06:00:05+02:00",
      "days": 2.0,
      "routeKm": 560.0,
      "freeKm": 720.0,
      "spareKm": 160.0,
      "driveHours": 6.588235294117647,
      "countries": [
        "Germany",
        "Italy"
      ],
      "appointment": "26 May – 28 May · Berglern → Venezia"
    },
    {
      "score": 124.8,
      "route": [
        "München",
        "Venezia"
      ],
      "legs": [
        {
          "originName": "München",
          "destName": "Venezia",
          "pickup": "2026-06-03T00:00:00+02:00",
          "dropoff": "2026-06-05T00:00:00+02:00",
          "vehicle": "CAMPER CABIN DELUXE Ford Nugget Plus - Ford Transit Custom V362",
          "make": "CAMPER CABIN DELUXE",
          "model": "Ford Nugget Plus - Ford Transit Custom V362",
          "distanceKm": 552.1,
          "offerId": "247831"
        }
      ],
      "type": "oneway",
      "homeCity": "München",
      "startUtc": "2026-06-03T00:00:00+02:00",
      "endUtc": "2026-06-05T00:00:00+02:00",
      "days": 2.0,
      "routeKm": 552.0,
      "freeKm": 1000.0,
      "spareKm": 448.0,
      "driveHours": 6.4941176470588236,
      "countries": [
        "Germany",
        "Italy"
      ],
      "appointment": "03 Jun – 05 Jun · München → Venezia"
    },
    {
      "score": 124.7,
      "route": [
        "Berglern",
        "Milan"
      ],
      "legs": [
        {
          "originName": "Berglern",
          "destName": "Milan",
          "pickup": "2026-05-26T06:00:05+02:00",
          "dropoff": "2026-05-28T06:00:05+02:00",
          "vehicle": "Fiat Ducato",
          "make": "Fiat",
          "model": "Ducato",
          "distanceKm": 535.0,
          "offerId": "247965"
        }
      ],
      "type": "oneway",
      "homeCity": "München",
      "startUtc": "2026-05-26T06:00:05+02:00",
      "endUtc": "2026-05-28T06:00:05+02:00",
      "days": 2.0,
      "routeKm": 535.0,
      "freeKm": 720.0,
      "spareKm": 185.0,
      "driveHours": 6.294117647058823,
      "countries": [
        "Germany",
        "Italy"
      ],
      "appointment": "26 May – 28 May · Berglern → Milan"
    },
    {
      "score": 124.7,
      "route": [
        "Berglern",
        "Bergamo"
      ],
      "legs": [
        {
          "originName": "Berglern",
          "destName": "Bergamo",
          "pickup": "2026-05-26T06:00:05+02:00",
          "dropoff": "2026-05-28T06:00:05+02:00",
          "vehicle": "Fiat Ducato",
          "make": "Fiat",
          "model": "Ducato",
          "distanceKm": 534.6,
          "offerId": "248017"
        }
      ],
      "type": "oneway",
      "homeCity": "München",
      "startUtc": "2026-05-26T06:00:05+02:00",
      "endUtc": "2026-05-28T06:00:05+02:00",
      "days": 2.0,
      "routeKm": 535.0,
      "freeKm": 720.0,
      "spareKm": 185.0,
      "driveHours": 6.294117647058823,
      "countries": [
        "Germany",
        "Italy"
      ],
      "appointment": "26 May – 28 May · Berglern → Bergamo"
    },
    {
      "score": 122.4,
      "route": [
        "Nantes",
        "Lyon",
        "Saint-Mesmes"
      ],
      "legs": [
        {
          "originName": "Nantes",
          "destName": "Lyon",
          "pickup": "2026-05-26T06:00:05+02:00",
          "dropoff": "2026-05-28T06:00:05+02:00",
          "vehicle": "Pilote G690 GJ or similar",
          "make": "Pilote",
          "model": "G690 GJ or similar",
          "distanceKm": 752.3,
          "offerId": "247851"
        },
        {
          "originName": "Lyon",
          "destName": "Saint-Mesmes",
          "pickup": "2026-05-29T06:00:05+02:00",
          "dropoff": "2026-05-31T06:00:05+02:00",
          "vehicle": "Volkswagen California",
          "make": "Volkswagen",
          "model": "California",
          "distanceKm": 526.4,
          "offerId": "247854"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-26T06:00:05+02:00",
      "endUtc": "2026-05-31T06:00:05+02:00",
      "days": 5.0,
      "routeKm": 1279.0,
      "freeKm": 1680.0,
      "spareKm": 401.0,
      "driveHours": 15.047058823529412,
      "countries": [
        "France"
      ],
      "appointment": "26 May – 31 May · Nantes → Saint-Mesmes"
    },
    {
      "score": 122.1,
      "route": [
        "Marburg",
        "Champlan",
        "Frankfurt am Main"
      ],
      "legs": [
        {
          "originName": "Marburg",
          "destName": "Champlan",
          "pickup": "2026-05-23T00:00:00+02:00",
          "dropoff": "2026-05-25T00:00:00+02:00",
          "vehicle": "CAMPER CABIN DELUXE Ford Nugget Plus - Ford Transit Custom V362",
          "make": "CAMPER CABIN DELUXE",
          "model": "Ford Nugget Plus - Ford Transit Custom V362",
          "distanceKm": 651.9,
          "offerId": "247752"
        },
        {
          "originName": "Champlan",
          "destName": "Frankfurt am Main",
          "pickup": "2026-05-26T00:00:00+02:00",
          "dropoff": "2026-05-28T00:00:00+02:00",
          "vehicle": "COUPLE COTTAGE Weinsberg Signeo C590 - Ford Transit V363",
          "make": "COUPLE COTTAGE",
          "model": "Weinsberg Signeo C590 - Ford Transit V363",
          "distanceKm": 573.3,
          "offerId": "247816"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-23T00:00:00+02:00",
      "endUtc": "2026-05-28T00:00:00+02:00",
      "days": 5.0,
      "routeKm": 1225.0,
      "freeKm": 2000.0,
      "spareKm": 775.0,
      "driveHours": 14.411764705882353,
      "countries": [
        "Germany",
        "France"
      ],
      "appointment": "23 May – 28 May · Marburg → Frankfurt am Main"
    },
    {
      "score": 122.1,
      "route": [
        "Florence",
        "Lyon",
        "Saint-Mesmes"
      ],
      "legs": [
        {
          "originName": "Florence",
          "destName": "Lyon",
          "pickup": "2026-05-26T06:00:05+02:00",
          "dropoff": "2026-05-28T06:00:05+02:00",
          "vehicle": "Fiat S 75SL / T 7400 SB or similar",
          "make": "Fiat",
          "model": "S 75SL / T 7400 SB or similar",
          "distanceKm": 692.1,
          "offerId": "247838"
        },
        {
          "originName": "Lyon",
          "destName": "Saint-Mesmes",
          "pickup": "2026-05-29T06:00:05+02:00",
          "dropoff": "2026-05-31T06:00:05+02:00",
          "vehicle": "Volkswagen California",
          "make": "Volkswagen",
          "model": "California",
          "distanceKm": 526.4,
          "offerId": "247854"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-26T06:00:05+02:00",
      "endUtc": "2026-05-31T06:00:05+02:00",
      "days": 5.0,
      "routeKm": 1218.0,
      "freeKm": 1680.0,
      "spareKm": 462.0,
      "driveHours": 14.329411764705883,
      "countries": [
        "Italy",
        "France"
      ],
      "appointment": "26 May – 31 May · Florence → Saint-Mesmes"
    },
    {
      "score": 121.8,
      "route": [
        "Saint-Jean-de-Gonville",
        "Aach"
      ],
      "legs": [
        {
          "originName": "Saint-Jean-de-Gonville",
          "destName": "Aach",
          "pickup": "2026-05-23T00:00:00+02:00",
          "dropoff": "2026-05-24T00:00:00+02:00",
          "vehicle": "SURFER SUITE VW California Ocean",
          "make": "SURFER SUITE",
          "model": "VW California Ocean",
          "distanceKm": 353.4,
          "offerId": "246475"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-23T00:00:00+02:00",
      "endUtc": "2026-05-24T00:00:00+02:00",
      "days": 1.0,
      "routeKm": 353.0,
      "freeKm": 600.0,
      "spareKm": 247.0,
      "driveHours": 4.152941176470589,
      "countries": [
        "France",
        "Germany"
      ],
      "appointment": "23 May – 24 May · Saint-Jean-de-Gonville → Aach"
    },
    {
      "score": 121.7,
      "route": [
        "Florence",
        "Milan"
      ],
      "legs": [
        {
          "originName": "Florence",
          "destName": "Milan",
          "pickup": "2026-05-26T06:00:05+02:00",
          "dropoff": "2026-05-27T06:00:05+02:00",
          "vehicle": "Fiat S 75SL / T 7400 SB or similar",
          "make": "Fiat",
          "model": "S 75SL / T 7400 SB or similar",
          "distanceKm": 345.7,
          "offerId": "247931"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-26T06:00:05+02:00",
      "endUtc": "2026-05-27T06:00:05+02:00",
      "days": 1.0,
      "routeKm": 346.0,
      "freeKm": 480.0,
      "spareKm": 134.0,
      "driveHours": 4.070588235294117,
      "countries": [
        "Italy"
      ],
      "appointment": "26 May – 27 May · Florence → Milan"
    },
    {
      "score": 121.6,
      "route": [
        "Florence",
        "Bergamo"
      ],
      "legs": [
        {
          "originName": "Florence",
          "destName": "Bergamo",
          "pickup": "2026-05-26T06:00:05+02:00",
          "dropoff": "2026-05-27T06:00:05+02:00",
          "vehicle": "Fiat S 75SL / T 7400 SB or similar",
          "make": "Fiat",
          "model": "S 75SL / T 7400 SB or similar",
          "distanceKm": 325.4,
          "offerId": "247946"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-26T06:00:05+02:00",
      "endUtc": "2026-05-27T06:00:05+02:00",
      "days": 1.0,
      "routeKm": 325.0,
      "freeKm": 480.0,
      "spareKm": 155.0,
      "driveHours": 3.823529411764706,
      "countries": [
        "Italy"
      ],
      "appointment": "26 May – 27 May · Florence → Bergamo"
    },
    {
      "score": 121.3,
      "route": [
        "Bologna",
        "Milan"
      ],
      "legs": [
        {
          "originName": "Bologna",
          "destName": "Milan",
          "pickup": "2026-05-26T06:00:05+02:00",
          "dropoff": "2026-05-27T06:00:05+02:00",
          "vehicle": "Fiat S 75SL / T 7400 SB or similar",
          "make": "Fiat",
          "model": "S 75SL / T 7400 SB or similar",
          "distanceKm": 263.8,
          "offerId": "247936"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-26T06:00:05+02:00",
      "endUtc": "2026-05-27T06:00:05+02:00",
      "days": 1.0,
      "routeKm": 264.0,
      "freeKm": 480.0,
      "spareKm": 216.0,
      "driveHours": 3.1058823529411765,
      "countries": [
        "Italy"
      ],
      "appointment": "26 May – 27 May · Bologna → Milan"
    },
    {
      "score": 121.3,
      "route": [
        "Berlin",
        "Bochum",
        "Goussainville"
      ],
      "legs": [
        {
          "originName": "Berlin",
          "destName": "Bochum",
          "pickup": "2026-06-01T00:00:00+02:00",
          "dropoff": "2026-06-03T00:00:00+02:00",
          "vehicle": "COZY COTTAGE Knaus Van TI Plus 650 MEG Platinum Selection - VW Crafter 2",
          "make": "COZY COTTAGE",
          "model": "Knaus Van TI Plus 650 MEG Platinum Selection - VW Crafter 2",
          "distanceKm": 512.1,
          "offerId": "243325"
        },
        {
          "originName": "Bochum",
          "destName": "Goussainville",
          "pickup": "2026-06-04T00:00:00+02:00",
          "dropoff": "2026-06-06T00:00:00+02:00",
          "vehicle": "COUPLE COTTAGE Weinsberg Signeo C590 - Ford Transit V363",
          "make": "COUPLE COTTAGE",
          "model": "Weinsberg Signeo C590 - Ford Transit V363",
          "distanceKm": 542.0,
          "offerId": "244799"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-06-01T00:00:00+02:00",
      "endUtc": "2026-06-06T00:00:00+02:00",
      "days": 5.0,
      "routeKm": 1054.0,
      "freeKm": 2000.0,
      "spareKm": 946.0,
      "driveHours": 12.4,
      "countries": [
        "Germany",
        "France"
      ],
      "appointment": "01 Jun – 06 Jun · Berlin → Goussainville"
    },
    {
      "score": 121.2,
      "route": [
        "Berglern",
        "Stuttgart"
      ],
      "legs": [
        {
          "originName": "Berglern",
          "destName": "Stuttgart",
          "pickup": "2026-05-26T06:00:05+02:00",
          "dropoff": "2026-05-27T06:00:05+02:00",
          "vehicle": "Fiat Ducato",
          "make": "Fiat",
          "model": "Ducato",
          "distanceKm": 244.9,
          "offerId": "248036"
        }
      ],
      "type": "oneway",
      "homeCity": "München",
      "startUtc": "2026-05-26T06:00:05+02:00",
      "endUtc": "2026-05-27T06:00:05+02:00",
      "days": 1.0,
      "routeKm": 245.0,
      "freeKm": 480.0,
      "spareKm": 235.0,
      "driveHours": 2.8823529411764706,
      "countries": [
        "Germany"
      ],
      "appointment": "26 May – 27 May · Berglern → Stuttgart"
    },
    {
      "score": 116.0,
      "route": [
        "Berlin",
        "Bochum",
        "Sint-Pieters-Leeuw"
      ],
      "legs": [
        {
          "originName": "Berlin",
          "destName": "Bochum",
          "pickup": "2026-06-01T23:59:59+02:00",
          "dropoff": "2026-06-03T23:59:59+02:00",
          "vehicle": "COZY COTTAGE Knaus Van TI Plus 650 MEG Platinum Selection - VW Crafter 2",
          "make": "COZY COTTAGE",
          "model": "Knaus Van TI Plus 650 MEG Platinum Selection - VW Crafter 2",
          "distanceKm": 512.1,
          "offerId": "243325"
        },
        {
          "originName": "Bochum",
          "destName": "Sint-Pieters-Leeuw",
          "pickup": "2026-06-08T00:00:00+02:00",
          "dropoff": "2026-06-09T00:00:00+02:00",
          "vehicle": "SURFER SUITE VW California Ocean",
          "make": "SURFER SUITE",
          "model": "VW California Ocean",
          "distanceKm": 279.2,
          "offerId": "245551"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-06-01T23:59:59+02:00",
      "endUtc": "2026-06-09T00:00:00+02:00",
      "days": 7.0,
      "routeKm": 791.0,
      "freeKm": 1600.0,
      "spareKm": 809.0,
      "driveHours": 9.305882352941177,
      "countries": [
        "Germany",
        "Europe"
      ],
      "appointment": "01 Jun – 09 Jun · Berlin → Sint-Pieters-Leeuw"
    },
    {
      "score": 109.3,
      "route": [
        "Weyhe",
        "Castellanza"
      ],
      "legs": [
        {
          "originName": "Weyhe",
          "destName": "Castellanza",
          "pickup": "2026-05-25T00:00:00+02:00",
          "dropoff": "2026-05-28T00:00:00+02:00",
          "vehicle": "CAMPER CASTLE Fiat Tracer 680DL - Fiat Ducato Serie 2",
          "make": "CAMPER CASTLE",
          "model": "Fiat Tracer 680DL - Fiat Ducato Serie 2",
          "distanceKm": 1066.5,
          "offerId": "243264"
        }
      ],
      "type": "oneway",
      "homeCity": "Hannover",
      "startUtc": "2026-05-25T00:00:00+02:00",
      "endUtc": "2026-05-28T00:00:00+02:00",
      "days": 3.0,
      "routeKm": 1066.0,
      "freeKm": 1400.0,
      "spareKm": 334.0,
      "driveHours": 12.541176470588235,
      "countries": [
        "Germany",
        "Italy"
      ],
      "appointment": "25 May – 28 May · Weyhe → Castellanza"
    },
    {
      "score": 109.3,
      "route": [
        "Berglern",
        "Olbia"
      ],
      "legs": [
        {
          "originName": "Berglern",
          "destName": "Olbia",
          "pickup": "2026-05-26T06:00:05+02:00",
          "dropoff": "2026-05-29T06:00:05+02:00",
          "vehicle": "Fiat Ducato",
          "make": "Fiat",
          "model": "Ducato",
          "distanceKm": 1059.7,
          "offerId": "248013"
        }
      ],
      "type": "oneway",
      "homeCity": "München",
      "startUtc": "2026-05-26T06:00:05+02:00",
      "endUtc": "2026-05-29T06:00:05+02:00",
      "days": 3.0,
      "routeKm": 1060.0,
      "freeKm": 1380.0,
      "spareKm": 320.0,
      "driveHours": 12.470588235294118,
      "countries": [
        "Germany",
        "Europe"
      ],
      "appointment": "26 May – 29 May · Berglern → Olbia"
    },
    {
      "score": 109.2,
      "route": [
        "Berglern",
        "Warszawa"
      ],
      "legs": [
        {
          "originName": "Berglern",
          "destName": "Warszawa",
          "pickup": "2026-06-09T06:00:06+02:00",
          "dropoff": "2026-06-12T06:00:06+02:00",
          "vehicle": "Fiat Ducato",
          "make": "Fiat",
          "model": "Ducato",
          "distanceKm": 1048.8,
          "offerId": "248060"
        }
      ],
      "type": "oneway",
      "homeCity": "München",
      "startUtc": "2026-06-09T06:00:06+02:00",
      "endUtc": "2026-06-12T06:00:06+02:00",
      "days": 3.0,
      "routeKm": 1049.0,
      "freeKm": 1380.0,
      "spareKm": 331.0,
      "driveHours": 12.341176470588236,
      "countries": [
        "Germany",
        "Europe"
      ],
      "appointment": "09 Jun – 12 Jun · Berglern → Warszawa"
    },
    {
      "score": 108.5,
      "route": [
        "Gersthofen",
        "Flensburg"
      ],
      "legs": [
        {
          "originName": "Gersthofen",
          "destName": "Flensburg",
          "pickup": "2026-05-29T00:00:00+02:00",
          "dropoff": "2026-06-01T00:00:00+02:00",
          "vehicle": "CAMPER CABIN Ford Nugget - Ford Transit Custom V710",
          "make": "CAMPER CABIN",
          "model": "Ford Nugget - Ford Transit Custom V710",
          "distanceKm": 899.6,
          "offerId": "244129"
        }
      ],
      "type": "oneway",
      "homeCity": "München",
      "startUtc": "2026-05-29T00:00:00+02:00",
      "endUtc": "2026-06-01T00:00:00+02:00",
      "days": 3.0,
      "routeKm": 900.0,
      "freeKm": 1400.0,
      "spareKm": 500.0,
      "driveHours": 10.588235294117647,
      "countries": [
        "Germany"
      ],
      "appointment": "29 May – 01 Jun · Gersthofen → Flensburg"
    },
    {
      "score": 108.4,
      "route": [
        "Dormagen",
        "Nantes"
      ],
      "legs": [
        {
          "originName": "Dormagen",
          "destName": "Nantes",
          "pickup": "2026-06-06T00:00:00+02:00",
          "dropoff": "2026-06-09T00:00:00+02:00",
          "vehicle": "CAMPER CASTLE Fiat Tracer 680DL - Fiat Ducato Serie 2",
          "make": "CAMPER CASTLE",
          "model": "Fiat Tracer 680DL - Fiat Ducato Serie 2",
          "distanceKm": 881.3,
          "offerId": "245561"
        }
      ],
      "type": "oneway",
      "homeCity": "Bochum",
      "startUtc": "2026-06-06T00:00:00+02:00",
      "endUtc": "2026-06-09T00:00:00+02:00",
      "days": 3.0,
      "routeKm": 881.0,
      "freeKm": 1400.0,
      "spareKm": 519.0,
      "driveHours": 10.364705882352942,
      "countries": [
        "Germany",
        "France"
      ],
      "appointment": "06 Jun – 09 Jun · Dormagen → Nantes"
    },
    {
      "score": 108.2,
      "route": [
        "Berglern",
        "Saint-Mesmes"
      ],
      "legs": [
        {
          "originName": "Berglern",
          "destName": "Saint-Mesmes",
          "pickup": "2026-05-26T06:00:05+02:00",
          "dropoff": "2026-05-29T06:00:05+02:00",
          "vehicle": "Fiat Ducato",
          "make": "Fiat",
          "model": "Ducato",
          "distanceKm": 844.2,
          "offerId": "247842"
        }
      ],
      "type": "oneway",
      "homeCity": "München",
      "startUtc": "2026-05-26T06:00:05+02:00",
      "endUtc": "2026-05-29T06:00:05+02:00",
      "days": 3.0,
      "routeKm": 844.0,
      "freeKm": 1150.0,
      "spareKm": 306.0,
      "driveHours": 9.929411764705883,
      "countries": [
        "Germany",
        "France"
      ],
      "appointment": "26 May – 29 May · Berglern → Saint-Mesmes"
    },
    {
      "score": 105.9,
      "route": [
        "Berglern",
        "Hamburg"
      ],
      "legs": [
        {
          "originName": "Berglern",
          "destName": "Hamburg",
          "pickup": "2026-05-26T06:00:05+02:00",
          "dropoff": "2026-05-28T06:00:05+02:00",
          "vehicle": "Fiat Ducato",
          "make": "Fiat",
          "model": "Ducato",
          "distanceKm": 788.1,
          "offerId": "248020"
        }
      ],
      "type": "oneway",
      "homeCity": "München",
      "startUtc": "2026-05-26T06:00:05+02:00",
      "endUtc": "2026-05-28T06:00:05+02:00",
      "days": 2.0,
      "routeKm": 788.0,
      "freeKm": 960.0,
      "spareKm": 172.0,
      "driveHours": 9.270588235294118,
      "countries": [
        "Germany"
      ],
      "appointment": "26 May – 28 May · Berglern → Hamburg"
    },
    {
      "score": 105.8,
      "route": [
        "Marburg",
        "Staffanstorps kommun"
      ],
      "legs": [
        {
          "originName": "Marburg",
          "destName": "Staffanstorps kommun",
          "pickup": "2026-05-26T00:00:00+02:00",
          "dropoff": "2026-05-28T00:00:00+02:00",
          "vehicle": "CAMPER CASTLE Fiat Tracer 680DL - Fiat Ducato Serie 2",
          "make": "CAMPER CASTLE",
          "model": "Fiat Tracer 680DL - Fiat Ducato Serie 2",
          "distanceKm": 769.8,
          "offerId": "242808"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-26T00:00:00+02:00",
      "endUtc": "2026-05-28T00:00:00+02:00",
      "days": 2.0,
      "routeKm": 770.0,
      "freeKm": 1000.0,
      "spareKm": 230.0,
      "driveHours": 9.058823529411764,
      "countries": [
        "Germany",
        "Sweden"
      ],
      "appointment": "26 May – 28 May · Marburg → Staffanstorps kommun"
    },
    {
      "score": 105.8,
      "route": [
        "Nantes",
        "Lyon"
      ],
      "legs": [
        {
          "originName": "Nantes",
          "destName": "Lyon",
          "pickup": "2026-05-26T06:00:05+02:00",
          "dropoff": "2026-05-28T06:00:05+02:00",
          "vehicle": "Pilote G690 GJ or similar",
          "make": "Pilote",
          "model": "G690 GJ or similar",
          "distanceKm": 752.3,
          "offerId": "247851"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-26T06:00:05+02:00",
      "endUtc": "2026-05-28T06:00:05+02:00",
      "days": 2.0,
      "routeKm": 752.0,
      "freeKm": 960.0,
      "spareKm": 208.0,
      "driveHours": 8.847058823529412,
      "countries": [
        "France"
      ],
      "appointment": "26 May – 28 May · Nantes → Lyon"
    },
    {
      "score": 105.7,
      "route": [
        "Weyhe",
        "Göteborgs Stad"
      ],
      "legs": [
        {
          "originName": "Weyhe",
          "destName": "Göteborgs Stad",
          "pickup": "2026-06-05T00:00:00+02:00",
          "dropoff": "2026-06-07T00:00:00+02:00",
          "vehicle": "SUNRISE SUITE VW California Ocean / Coast",
          "make": "SUNRISE SUITE",
          "model": "VW California Ocean / Coast",
          "distanceKm": 743.7,
          "offerId": "244273"
        }
      ],
      "type": "oneway",
      "homeCity": "Hannover",
      "startUtc": "2026-06-05T00:00:00+02:00",
      "endUtc": "2026-06-07T00:00:00+02:00",
      "days": 2.0,
      "routeKm": 744.0,
      "freeKm": 1000.0,
      "spareKm": 256.0,
      "driveHours": 8.75294117647059,
      "countries": [
        "Germany",
        "Sweden"
      ],
      "appointment": "05 Jun – 07 Jun · Weyhe → Göteborgs Stad"
    },
    {
      "score": 105.7,
      "route": [
        "Marburg",
        "Castellanza"
      ],
      "legs": [
        {
          "originName": "Marburg",
          "destName": "Castellanza",
          "pickup": "2026-05-23T00:00:00+02:00",
          "dropoff": "2026-05-25T00:00:00+02:00",
          "vehicle": "FAMILY FINCA VW Grand California 600 - VW Crafter 2",
          "make": "FAMILY FINCA",
          "model": "VW Grand California 600 - VW Crafter 2",
          "distanceKm": 740.4,
          "offerId": "246239"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-23T00:00:00+02:00",
      "endUtc": "2026-05-25T00:00:00+02:00",
      "days": 2.0,
      "routeKm": 740.0,
      "freeKm": 1000.0,
      "spareKm": 260.0,
      "driveHours": 8.705882352941176,
      "countries": [
        "Germany",
        "Italy"
      ],
      "appointment": "23 May – 25 May · Marburg → Castellanza"
    },
    {
      "score": 105.5,
      "route": [
        "Toulouse",
        "Saint-Mesmes"
      ],
      "legs": [
        {
          "originName": "Toulouse",
          "destName": "Saint-Mesmes",
          "pickup": "2026-05-26T06:00:05+02:00",
          "dropoff": "2026-05-28T06:00:05+02:00",
          "vehicle": "Volkswagen California",
          "make": "Volkswagen",
          "model": "California",
          "distanceKm": 706.0,
          "offerId": "247852"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-26T06:00:05+02:00",
      "endUtc": "2026-05-28T06:00:05+02:00",
      "days": 2.0,
      "routeKm": 706.0,
      "freeKm": 960.0,
      "spareKm": 254.0,
      "driveHours": 8.305882352941177,
      "countries": [
        "France"
      ],
      "appointment": "26 May – 28 May · Toulouse → Saint-Mesmes"
    },
    {
      "score": 105.5,
      "route": [
        "Florence",
        "Lyon"
      ],
      "legs": [
        {
          "originName": "Florence",
          "destName": "Lyon",
          "pickup": "2026-05-26T06:00:05+02:00",
          "dropoff": "2026-05-28T06:00:05+02:00",
          "vehicle": "Fiat S 75SL / T 7400 SB or similar",
          "make": "Fiat",
          "model": "S 75SL / T 7400 SB or similar",
          "distanceKm": 692.1,
          "offerId": "247838"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-26T06:00:05+02:00",
      "endUtc": "2026-05-28T06:00:05+02:00",
      "days": 2.0,
      "routeKm": 692.0,
      "freeKm": 960.0,
      "spareKm": 268.0,
      "driveHours": 8.141176470588235,
      "countries": [
        "Italy",
        "France"
      ],
      "appointment": "26 May – 28 May · Florence → Lyon"
    },
    {
      "score": 105.3,
      "route": [
        "Marburg",
        "Champlan"
      ],
      "legs": [
        {
          "originName": "Marburg",
          "destName": "Champlan",
          "pickup": "2026-05-23T00:00:00+02:00",
          "dropoff": "2026-05-25T00:00:00+02:00",
          "vehicle": "CAMPER CABIN DELUXE Ford Nugget Plus - Ford Transit Custom V362",
          "make": "CAMPER CABIN DELUXE",
          "model": "Ford Nugget Plus - Ford Transit Custom V362",
          "distanceKm": 651.9,
          "offerId": "247752"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-23T00:00:00+02:00",
      "endUtc": "2026-05-25T00:00:00+02:00",
      "days": 2.0,
      "routeKm": 652.0,
      "freeKm": 1000.0,
      "spareKm": 348.0,
      "driveHours": 7.670588235294118,
      "countries": [
        "Germany",
        "France"
      ],
      "appointment": "23 May – 25 May · Marburg → Champlan"
    },
    {
      "score": 105.2,
      "route": [
        "Florence",
        "Cagliari"
      ],
      "legs": [
        {
          "originName": "Florence",
          "destName": "Cagliari",
          "pickup": "2026-05-26T06:00:05+02:00",
          "dropoff": "2026-05-28T06:00:05+02:00",
          "vehicle": "Fiat Ducato",
          "make": "Fiat",
          "model": "Ducato",
          "distanceKm": 649.4,
          "offerId": "247934"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-26T06:00:05+02:00",
      "endUtc": "2026-05-28T06:00:05+02:00",
      "days": 2.0,
      "routeKm": 649.0,
      "freeKm": 960.0,
      "spareKm": 311.0,
      "driveHours": 7.635294117647059,
      "countries": [
        "Italy",
        "Europe"
      ],
      "appointment": "26 May – 28 May · Florence → Cagliari"
    },
    {
      "score": 104.9,
      "route": [
        "Champlan",
        "Frankfurt am Main"
      ],
      "legs": [
        {
          "originName": "Champlan",
          "destName": "Frankfurt am Main",
          "pickup": "2026-05-23T00:00:00+02:00",
          "dropoff": "2026-05-25T00:00:00+02:00",
          "vehicle": "COUPLE COTTAGE Weinsberg Signeo C590 - Ford Transit V363",
          "make": "COUPLE COTTAGE",
          "model": "Weinsberg Signeo C590 - Ford Transit V363",
          "distanceKm": 573.3,
          "offerId": "247816"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-23T00:00:00+02:00",
      "endUtc": "2026-05-25T00:00:00+02:00",
      "days": 2.0,
      "routeKm": 573.0,
      "freeKm": 1000.0,
      "spareKm": 427.0,
      "driveHours": 6.741176470588235,
      "countries": [
        "France",
        "Germany"
      ],
      "appointment": "23 May – 25 May · Champlan → Frankfurt am Main"
    },
    {
      "score": 104.8,
      "route": [
        "Berlin",
        "Warszawa"
      ],
      "legs": [
        {
          "originName": "Berlin",
          "destName": "Warszawa",
          "pickup": "2026-05-26T06:00:05+02:00",
          "dropoff": "2026-05-28T06:00:05+02:00",
          "vehicle": "Fiat Ducato",
          "make": "Fiat",
          "model": "Ducato",
          "distanceKm": 560.9,
          "offerId": "247940"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-26T06:00:05+02:00",
      "endUtc": "2026-05-28T06:00:05+02:00",
      "days": 2.0,
      "routeKm": 561.0,
      "freeKm": 720.0,
      "spareKm": 159.0,
      "driveHours": 6.6,
      "countries": [
        "Germany",
        "Europe"
      ],
      "appointment": "26 May – 28 May · Berlin → Warszawa"
    },
    {
      "score": 104.7,
      "route": [
        "Bochum",
        "Goussainville"
      ],
      "legs": [
        {
          "originName": "Bochum",
          "destName": "Goussainville",
          "pickup": "2026-06-04T00:00:00+02:00",
          "dropoff": "2026-06-06T00:00:00+02:00",
          "vehicle": "COUPLE COTTAGE Weinsberg Signeo C590 - Ford Transit V363",
          "make": "COUPLE COTTAGE",
          "model": "Weinsberg Signeo C590 - Ford Transit V363",
          "distanceKm": 542.0,
          "offerId": "244799"
        }
      ],
      "type": "oneway",
      "homeCity": "Bochum",
      "startUtc": "2026-06-04T00:00:00+02:00",
      "endUtc": "2026-06-06T00:00:00+02:00",
      "days": 2.0,
      "routeKm": 542.0,
      "freeKm": 1000.0,
      "spareKm": 458.0,
      "driveHours": 6.376470588235295,
      "countries": [
        "Germany",
        "France"
      ],
      "appointment": "04 Jun – 06 Jun · Bochum → Goussainville"
    },
    {
      "score": 104.6,
      "route": [
        "Lyon",
        "Saint-Mesmes"
      ],
      "legs": [
        {
          "originName": "Lyon",
          "destName": "Saint-Mesmes",
          "pickup": "2026-05-26T06:00:05+02:00",
          "dropoff": "2026-05-28T06:00:05+02:00",
          "vehicle": "Volkswagen California",
          "make": "Volkswagen",
          "model": "California",
          "distanceKm": 526.4,
          "offerId": "247854"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-26T06:00:05+02:00",
      "endUtc": "2026-05-28T06:00:05+02:00",
      "days": 2.0,
      "routeKm": 526.0,
      "freeKm": 720.0,
      "spareKm": 194.0,
      "driveHours": 6.188235294117647,
      "countries": [
        "France"
      ],
      "appointment": "26 May – 28 May · Lyon → Saint-Mesmes"
    },
    {
      "score": 104.6,
      "route": [
        "Berlin",
        "Bochum"
      ],
      "legs": [
        {
          "originName": "Berlin",
          "destName": "Bochum",
          "pickup": "2026-05-26T00:00:00+02:00",
          "dropoff": "2026-05-28T00:00:00+02:00",
          "vehicle": "COZY COTTAGE Knaus Van TI Plus 650 MEG Platinum Selection - VW Crafter 2",
          "make": "COZY COTTAGE",
          "model": "Knaus Van TI Plus 650 MEG Platinum Selection - VW Crafter 2",
          "distanceKm": 512.1,
          "offerId": "243325"
        }
      ],
      "type": "inbound",
      "homeCity": "Bochum",
      "startUtc": "2026-05-26T00:00:00+02:00",
      "endUtc": "2026-05-28T00:00:00+02:00",
      "days": 2.0,
      "routeKm": 512.0,
      "freeKm": 1000.0,
      "spareKm": 488.0,
      "driveHours": 6.023529411764706,
      "countries": [
        "Germany"
      ],
      "appointment": "26 May – 28 May · Berlin → Bochum"
    },
    {
      "score": 104.5,
      "route": [
        "Weyhe",
        "Sint-Pieters-Leeuw"
      ],
      "legs": [
        {
          "originName": "Weyhe",
          "destName": "Sint-Pieters-Leeuw",
          "pickup": "2026-06-05T00:00:00+02:00",
          "dropoff": "2026-06-07T00:00:00+02:00",
          "vehicle": "COUPLE COTTAGE Weinsberg Signeo C590 - Ford Transit V363",
          "make": "COUPLE COTTAGE",
          "model": "Weinsberg Signeo C590 - Ford Transit V363",
          "distanceKm": 504.7,
          "offerId": "241199"
        }
      ],
      "type": "oneway",
      "homeCity": "Hannover",
      "startUtc": "2026-06-05T00:00:00+02:00",
      "endUtc": "2026-06-07T00:00:00+02:00",
      "days": 2.0,
      "routeKm": 505.0,
      "freeKm": 1000.0,
      "spareKm": 495.0,
      "driveHours": 5.9411764705882355,
      "countries": [
        "Germany",
        "Europe"
      ],
      "appointment": "05 Jun – 07 Jun · Weyhe → Sint-Pieters-Leeuw"
    },
    {
      "score": 104.5,
      "route": [
        "Dormagen",
        "Leipzig"
      ],
      "legs": [
        {
          "originName": "Dormagen",
          "destName": "Leipzig",
          "pickup": "2026-06-08T00:00:00+02:00",
          "dropoff": "2026-06-10T00:00:00+02:00",
          "vehicle": "BEACH HOSTEL VW California Beach",
          "make": "BEACH HOSTEL",
          "model": "VW California Beach",
          "distanceKm": 502.4,
          "offerId": "247670"
        }
      ],
      "type": "oneway",
      "homeCity": "Bochum",
      "startUtc": "2026-06-08T00:00:00+02:00",
      "endUtc": "2026-06-10T00:00:00+02:00",
      "days": 2.0,
      "routeKm": 502.0,
      "freeKm": 1000.0,
      "spareKm": 498.0,
      "driveHours": 5.905882352941177,
      "countries": [
        "Germany"
      ],
      "appointment": "08 Jun – 10 Jun · Dormagen → Leipzig"
    },
    {
      "score": 104.4,
      "route": [
        "Weyhe",
        "Staffanstorps kommun"
      ],
      "legs": [
        {
          "originName": "Weyhe",
          "destName": "Staffanstorps kommun",
          "pickup": "2026-06-08T00:00:00+02:00",
          "dropoff": "2026-06-10T00:00:00+02:00",
          "vehicle": "COUPLE COTTAGE Weinsberg Signeo C590 - Ford Transit V363",
          "make": "COUPLE COTTAGE",
          "model": "Weinsberg Signeo C590 - Ford Transit V363",
          "distanceKm": 484.1,
          "offerId": "245555"
        }
      ],
      "type": "oneway",
      "homeCity": "Hannover",
      "startUtc": "2026-06-08T00:00:00+02:00",
      "endUtc": "2026-06-10T00:00:00+02:00",
      "days": 2.0,
      "routeKm": 484.0,
      "freeKm": 1000.0,
      "spareKm": 516.0,
      "driveHours": 5.694117647058824,
      "countries": [
        "Germany",
        "Sweden"
      ],
      "appointment": "08 Jun – 10 Jun · Weyhe → Staffanstorps kommun"
    },
    {
      "score": 104.4,
      "route": [
        "Dormagen",
        "Goussainville"
      ],
      "legs": [
        {
          "originName": "Dormagen",
          "destName": "Goussainville",
          "pickup": "2026-06-05T00:00:00+02:00",
          "dropoff": "2026-06-07T00:00:00+02:00",
          "vehicle": "ROAD HOUSE Westfalia Eliseo C540 - Fiat Ducato 8",
          "make": "ROAD HOUSE",
          "model": "Westfalia Eliseo C540 - Fiat Ducato 8",
          "distanceKm": 481.7,
          "offerId": "245565"
        }
      ],
      "type": "oneway",
      "homeCity": "Bochum",
      "startUtc": "2026-06-05T00:00:00+02:00",
      "endUtc": "2026-06-07T00:00:00+02:00",
      "days": 2.0,
      "routeKm": 482.0,
      "freeKm": 1000.0,
      "spareKm": 518.0,
      "driveHours": 5.670588235294118,
      "countries": [
        "Germany",
        "France"
      ],
      "appointment": "05 Jun – 07 Jun · Dormagen → Goussainville"
    },
    {
      "score": 104.3,
      "route": [
        "Gersthofen",
        "Castellanza"
      ],
      "legs": [
        {
          "originName": "Gersthofen",
          "destName": "Castellanza",
          "pickup": "2026-06-27T00:00:00+02:00",
          "dropoff": "2026-06-29T00:00:00+02:00",
          "vehicle": "SUNRISE SUITE VW California Ocean / Coast",
          "make": "SUNRISE SUITE",
          "model": "VW California Ocean / Coast",
          "distanceKm": 469.6,
          "offerId": "247241"
        }
      ],
      "type": "oneway",
      "homeCity": "München",
      "startUtc": "2026-06-27T00:00:00+02:00",
      "endUtc": "2026-06-29T00:00:00+02:00",
      "days": 2.0,
      "routeKm": 470.0,
      "freeKm": 1000.0,
      "spareKm": 530.0,
      "driveHours": 5.529411764705882,
      "countries": [
        "Germany",
        "Italy"
      ],
      "appointment": "27 Jun – 29 Jun · Gersthofen → Castellanza"
    },
    {
      "score": 104.1,
      "route": [
        "Gersthofen",
        "Leipzig"
      ],
      "legs": [
        {
          "originName": "Gersthofen",
          "destName": "Leipzig",
          "pickup": "2026-05-23T00:00:00+02:00",
          "dropoff": "2026-05-25T00:00:00+02:00",
          "vehicle": "COZY COTTAGE Knaus Van TI Plus 650 MEG Platinum Selection - VW Crafter 2",
          "make": "COZY COTTAGE",
          "model": "Knaus Van TI Plus 650 MEG Platinum Selection - VW Crafter 2",
          "distanceKm": 419.4,
          "offerId": "247229"
        }
      ],
      "type": "oneway",
      "homeCity": "München",
      "startUtc": "2026-05-23T00:00:00+02:00",
      "endUtc": "2026-05-25T00:00:00+02:00",
      "days": 2.0,
      "routeKm": 419.0,
      "freeKm": 1000.0,
      "spareKm": 581.0,
      "driveHours": 4.929411764705883,
      "countries": [
        "Germany"
      ],
      "appointment": "23 May – 25 May · Gersthofen → Leipzig"
    },
    {
      "score": 104.1,
      "route": [
        "Berglern",
        "Frankfurt am Main"
      ],
      "legs": [
        {
          "originName": "Berglern",
          "destName": "Frankfurt am Main",
          "pickup": "2026-05-26T06:00:05+02:00",
          "dropoff": "2026-05-28T06:00:05+02:00",
          "vehicle": "Fiat Ducato",
          "make": "Fiat",
          "model": "Ducato",
          "distanceKm": 412.8,
          "offerId": "248023"
        }
      ],
      "type": "oneway",
      "homeCity": "München",
      "startUtc": "2026-05-26T06:00:05+02:00",
      "endUtc": "2026-05-28T06:00:05+02:00",
      "days": 2.0,
      "routeKm": 413.0,
      "freeKm": 720.0,
      "spareKm": 307.0,
      "driveHours": 4.858823529411764,
      "countries": [
        "Germany"
      ],
      "appointment": "26 May – 28 May · Berglern → Frankfurt am Main"
    },
    {
      "score": 102.0,
      "route": [
        "Florence",
        "Olbia"
      ],
      "legs": [
        {
          "originName": "Florence",
          "destName": "Olbia",
          "pickup": "2026-05-26T06:00:05+02:00",
          "dropoff": "2026-05-27T06:00:05+02:00",
          "vehicle": "Fiat Ducato",
          "make": "Fiat",
          "model": "Ducato",
          "distanceKm": 396.0,
          "offerId": "247950"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-26T06:00:05+02:00",
      "endUtc": "2026-05-27T06:00:05+02:00",
      "days": 1.0,
      "routeKm": 396.0,
      "freeKm": 480.0,
      "spareKm": 84.0,
      "driveHours": 4.658823529411765,
      "countries": [
        "Italy",
        "Europe"
      ],
      "appointment": "26 May – 27 May · Florence → Olbia"
    },
    {
      "score": 101.4,
      "route": [
        "Florence",
        "Bastia"
      ],
      "legs": [
        {
          "originName": "Florence",
          "destName": "Bastia",
          "pickup": "2026-05-26T06:00:05+02:00",
          "dropoff": "2026-05-27T06:00:05+02:00",
          "vehicle": "Fiat Ducato",
          "make": "Fiat",
          "model": "Ducato",
          "distanceKm": 281.3,
          "offerId": "247836"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-26T06:00:05+02:00",
      "endUtc": "2026-05-27T06:00:05+02:00",
      "days": 1.0,
      "routeKm": 281.0,
      "freeKm": 480.0,
      "spareKm": 199.0,
      "driveHours": 3.3058823529411763,
      "countries": [
        "Italy"
      ],
      "appointment": "26 May – 27 May · Florence → Bastia"
    },
    {
      "score": 101.4,
      "route": [
        "Bochum",
        "Sint-Pieters-Leeuw"
      ],
      "legs": [
        {
          "originName": "Bochum",
          "destName": "Sint-Pieters-Leeuw",
          "pickup": "2026-06-08T00:00:00+02:00",
          "dropoff": "2026-06-09T00:00:00+02:00",
          "vehicle": "SURFER SUITE VW California Ocean",
          "make": "SURFER SUITE",
          "model": "VW California Ocean",
          "distanceKm": 279.2,
          "offerId": "245551"
        }
      ],
      "type": "oneway",
      "homeCity": "Bochum",
      "startUtc": "2026-06-08T00:00:00+02:00",
      "endUtc": "2026-06-09T00:00:00+02:00",
      "days": 1.0,
      "routeKm": 279.0,
      "freeKm": 600.0,
      "spareKm": 321.0,
      "driveHours": 3.2823529411764705,
      "countries": [
        "Germany",
        "Europe"
      ],
      "appointment": "08 Jun – 09 Jun · Bochum → Sint-Pieters-Leeuw"
    },
    {
      "score": 100.3,
      "route": [
        "Grigny",
        "Saint-Mesmes"
      ],
      "legs": [
        {
          "originName": "Grigny",
          "destName": "Saint-Mesmes",
          "pickup": "2026-05-26T06:00:05+02:00",
          "dropoff": "2026-05-27T06:00:05+02:00",
          "vehicle": "Ford Transit/Jumper or similar",
          "make": "Ford",
          "model": "Transit/Jumper or similar",
          "distanceKm": 56.1,
          "offerId": "247846"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-26T06:00:05+02:00",
      "endUtc": "2026-05-27T06:00:05+02:00",
      "days": 1.0,
      "routeKm": 56.0,
      "freeKm": 240.0,
      "spareKm": 184.0,
      "driveHours": 0.6588235294117647,
      "countries": [
        "France"
      ],
      "appointment": "26 May – 27 May · Grigny → Saint-Mesmes"
    }
  ]
} as const;
