// AUTO-GENERATED by scripts/build.py — do not edit manually.
// Generated: 2026-05-22T14:01:59Z
// Run `npm run refresh` to regenerate.

import type { TripData } from '@/lib/chains';

export const TRIP_DATA: TripData = {
  "meta": {
    "generated": "2026-05-22T14:01:59Z",
    "offerCount": 65,
    "recommendedCount": 55
  },
  "offers": [
    {
      "offerId": "245850",
      "originName": "Marburg",
      "destName": "Graz",
      "startUtc": "2026-05-17T22:00:00Z",
      "endUtc": "2026-05-25T21:59:59Z",
      "periodHours": 72,
      "distanceKm": 807.8,
      "freeKm": 1400.0,
      "make": "CAMPER CABIN DELUXE",
      "model": "Ford Nugget Plus - Ford Transit Custom V362"
    },
    {
      "offerId": "247752",
      "originName": "Marburg",
      "destName": "Champlan",
      "startUtc": "2026-05-17T22:00:00Z",
      "endUtc": "2026-05-25T21:59:59Z",
      "periodHours": 48,
      "distanceKm": 651.9,
      "freeKm": 1000.0,
      "make": "CAMPER CABIN DELUXE",
      "model": "Ford Nugget Plus - Ford Transit Custom V362"
    },
    {
      "offerId": "247229",
      "originName": "Gersthofen",
      "destName": "Leipzig",
      "startUtc": "2026-05-19T22:00:00Z",
      "endUtc": "2026-05-27T21:59:59Z",
      "periodHours": 48,
      "distanceKm": 419.4,
      "freeKm": 1000.0,
      "make": "COZY COTTAGE",
      "model": "Knaus Van TI Plus 650 MEG Platinum Selection - VW Crafter 2",
      "homeCity": "München"
    },
    {
      "offerId": "245064",
      "originName": "Marburg",
      "destName": "Graz",
      "startUtc": "2026-05-21T22:00:00Z",
      "endUtc": "2026-05-29T21:59:59Z",
      "periodHours": 72,
      "distanceKm": 807.8,
      "freeKm": 1400.0,
      "make": "CAMPER CABIN DELUXE",
      "model": "Ford Nugget Plus - Ford Transit Custom V362"
    },
    {
      "offerId": "246239",
      "originName": "Marburg",
      "destName": "Castellanza",
      "startUtc": "2026-05-21T22:00:00Z",
      "endUtc": "2026-05-29T21:59:59Z",
      "periodHours": 48,
      "distanceKm": 740.4,
      "freeKm": 1000.0,
      "make": "FAMILY FINCA",
      "model": "VW Grand California 600 - VW Crafter 2"
    },
    {
      "offerId": "246252",
      "originName": "Marburg",
      "destName": "Castellanza",
      "startUtc": "2026-05-21T22:00:00Z",
      "endUtc": "2026-05-29T21:59:59Z",
      "periodHours": 48,
      "distanceKm": 740.4,
      "freeKm": 1000.0,
      "make": "FAMILY FINCA",
      "model": "VW Grand California 600 - VW Crafter 2"
    },
    {
      "offerId": "247818",
      "originName": "Bayreuth",
      "destName": "Rosenheim",
      "startUtc": "2026-05-21T22:00:00Z",
      "endUtc": "2026-05-23T12:00:00Z",
      "periodHours": 24,
      "distanceKm": 302.5,
      "freeKm": 400.0,
      "make": "MB",
      "model": "CLE180 CAB BE AUT"
    },
    {
      "offerId": "247819",
      "originName": "Bayreuth",
      "destName": "Rosenheim",
      "startUtc": "2026-05-21T22:00:00Z",
      "endUtc": "2026-05-23T12:00:00Z",
      "periodHours": 24,
      "distanceKm": 302.5,
      "freeKm": 400.0,
      "make": "VW",
      "model": "GOLF KOM BE MAN"
    },
    {
      "offerId": "247820",
      "originName": "Bamberg",
      "destName": "Rosenheim",
      "startUtc": "2026-05-21T22:00:00Z",
      "endUtc": "2026-05-23T12:00:00Z",
      "periodHours": 24,
      "distanceKm": 305.5,
      "freeKm": 400.0,
      "make": "CITRO",
      "model": "C3 AIRCROSS OFF BE AUT"
    },
    {
      "offerId": "247821",
      "originName": "Bamberg",
      "destName": "Rosenheim",
      "startUtc": "2026-05-21T22:00:00Z",
      "endUtc": "2026-05-23T12:00:00Z",
      "periodHours": 24,
      "distanceKm": 305.5,
      "freeKm": 400.0,
      "make": "AUDI",
      "model": "A5 AVANT KOM HBBP AUT"
    },
    {
      "offerId": "247823",
      "originName": "Bayreuth",
      "destName": "Rosenheim",
      "startUtc": "2026-05-21T22:00:00Z",
      "endUtc": "2026-05-23T12:00:00Z",
      "periodHours": 24,
      "distanceKm": 302.5,
      "freeKm": 400.0,
      "make": "OPEL",
      "model": "CORSA LIM BE MAN"
    },
    {
      "offerId": "247824",
      "originName": "Bayreuth",
      "destName": "Rosenheim",
      "startUtc": "2026-05-21T22:00:00Z",
      "endUtc": "2026-05-23T12:00:00Z",
      "periodHours": 24,
      "distanceKm": 302.5,
      "freeKm": 400.0,
      "make": "JEEP",
      "model": "AVENGER OFF HBB AUT"
    },
    {
      "offerId": "246475",
      "originName": "Saint-Jean-de-Gonville",
      "destName": "Aach",
      "startUtc": "2026-05-22T22:00:00Z",
      "endUtc": "2026-05-30T21:59:59Z",
      "periodHours": 24,
      "distanceKm": 353.4,
      "freeKm": 600.0,
      "make": "SURFER SUITE",
      "model": "VW California Ocean"
    },
    {
      "offerId": "247816",
      "originName": "Champlan",
      "destName": "Frankfurt am Main",
      "startUtc": "2026-05-22T22:00:00Z",
      "endUtc": "2026-05-30T21:59:59Z",
      "periodHours": 48,
      "distanceKm": 573.3,
      "freeKm": 1000.0,
      "make": "COUPLE COTTAGE",
      "model": "Weinsberg Signeo C590 - Ford Transit V363"
    },
    {
      "offerId": "247266",
      "originName": "Amstelveen",
      "destName": "Stuttgart",
      "startUtc": "2026-05-23T04:00:05Z",
      "endUtc": "2026-05-29T21:51:05Z",
      "periodHours": 48,
      "distanceKm": 681.9,
      "freeKm": 960.0,
      "make": "Volkswagen",
      "model": "California"
    },
    {
      "offerId": "247267",
      "originName": "Roma",
      "destName": "Stuttgart",
      "startUtc": "2026-05-23T04:00:05Z",
      "endUtc": "2026-05-31T21:51:05Z",
      "periodHours": 72,
      "distanceKm": 1087.9,
      "freeKm": 1380.0,
      "make": "Volkswagen",
      "model": "California"
    },
    {
      "offerId": "247270",
      "originName": "Pisa",
      "destName": "Olbia",
      "startUtc": "2026-05-23T04:00:05Z",
      "endUtc": "2026-05-29T21:51:05Z",
      "periodHours": 24,
      "distanceKm": 339.4,
      "freeKm": 480.0,
      "make": "Volkswagen",
      "model": "California"
    },
    {
      "offerId": "247272",
      "originName": "Essen",
      "destName": "Berlin",
      "startUtc": "2026-05-23T04:00:05Z",
      "endUtc": "2026-05-29T21:51:05Z",
      "periodHours": 48,
      "distanceKm": 539.2,
      "freeKm": 720.0,
      "make": "Fiat",
      "model": "Ducato",
      "homeCity": "Bochum"
    },
    {
      "offerId": "247273",
      "originName": "Berglern",
      "destName": "Venezia",
      "startUtc": "2026-05-23T04:00:05Z",
      "endUtc": "2026-05-29T21:51:05Z",
      "periodHours": 48,
      "distanceKm": 560.0,
      "freeKm": 720.0,
      "make": "Fiat",
      "model": "Ducato",
      "homeCity": "München"
    },
    {
      "offerId": "247275",
      "originName": "Florence",
      "destName": "Olbia",
      "startUtc": "2026-05-23T04:00:05Z",
      "endUtc": "2026-05-29T21:51:05Z",
      "periodHours": 24,
      "distanceKm": 396.0,
      "freeKm": 480.0,
      "make": "Fiat",
      "model": "Ducato"
    },
    {
      "offerId": "247276",
      "originName": "Florence",
      "destName": "Bergamo",
      "startUtc": "2026-05-23T04:00:05Z",
      "endUtc": "2026-05-29T21:51:05Z",
      "periodHours": 24,
      "distanceKm": 325.4,
      "freeKm": 480.0,
      "make": "Fiat",
      "model": "S 75SL / T 7400 SB or similar"
    },
    {
      "offerId": "247277",
      "originName": "Florence",
      "destName": "Bergamo",
      "startUtc": "2026-05-23T04:00:05Z",
      "endUtc": "2026-05-29T21:51:05Z",
      "periodHours": 24,
      "distanceKm": 325.4,
      "freeKm": 480.0,
      "make": "Fiat",
      "model": "S 75SL / T 7400 SB or similar"
    },
    {
      "offerId": "247278",
      "originName": "Florence",
      "destName": "Bergamo",
      "startUtc": "2026-05-23T04:00:05Z",
      "endUtc": "2026-05-29T21:51:05Z",
      "periodHours": 24,
      "distanceKm": 325.4,
      "freeKm": 480.0,
      "make": "Fiat",
      "model": "S 75SL / T 7400 SB or similar"
    },
    {
      "offerId": "247279",
      "originName": "Florence",
      "destName": "Bergamo",
      "startUtc": "2026-05-23T04:00:05Z",
      "endUtc": "2026-05-29T21:51:05Z",
      "periodHours": 24,
      "distanceKm": 325.4,
      "freeKm": 480.0,
      "make": "Fiat",
      "model": "S 75SL / T 7400 SB or similar"
    },
    {
      "offerId": "247280",
      "originName": "Florence",
      "destName": "Olbia",
      "startUtc": "2026-05-23T04:00:05Z",
      "endUtc": "2026-05-29T21:51:05Z",
      "periodHours": 24,
      "distanceKm": 396.0,
      "freeKm": 480.0,
      "make": "Fiat",
      "model": "S 75SL / T 7400 SB or similar"
    },
    {
      "offerId": "247281",
      "originName": "Florence",
      "destName": "Milan",
      "startUtc": "2026-05-23T04:00:05Z",
      "endUtc": "2026-05-29T21:51:05Z",
      "periodHours": 24,
      "distanceKm": 345.7,
      "freeKm": 480.0,
      "make": "Fiat",
      "model": "S 75SL / T 7400 SB or similar"
    },
    {
      "offerId": "247282",
      "originName": "Berglern",
      "destName": "Berlin",
      "startUtc": "2026-05-23T04:00:05Z",
      "endUtc": "2026-05-29T21:51:05Z",
      "periodHours": 48,
      "distanceKm": 598.2,
      "freeKm": 720.0,
      "make": "Fiat",
      "model": "Ducato",
      "homeCity": "München"
    },
    {
      "offerId": "247283",
      "originName": "Florence",
      "destName": "Olbia",
      "startUtc": "2026-05-23T04:00:05Z",
      "endUtc": "2026-05-29T21:51:05Z",
      "periodHours": 24,
      "distanceKm": 396.0,
      "freeKm": 480.0,
      "make": "Fiat",
      "model": "Ducato"
    },
    {
      "offerId": "247284",
      "originName": "Berglern",
      "destName": "Florence",
      "startUtc": "2026-05-23T04:00:05Z",
      "endUtc": "2026-05-29T21:51:05Z",
      "periodHours": 48,
      "distanceKm": 660.8,
      "freeKm": 960.0,
      "make": "Fiat",
      "model": "Ducato",
      "homeCity": "München"
    },
    {
      "offerId": "247286",
      "originName": "Nantes",
      "destName": "Milan",
      "startUtc": "2026-05-23T04:00:05Z",
      "endUtc": "2026-05-31T21:51:05Z",
      "periodHours": 72,
      "distanceKm": 1118.6,
      "freeKm": 1380.0,
      "make": "Pilote",
      "model": "G690 GJ or similar"
    },
    {
      "offerId": "247287",
      "originName": "Berglern",
      "destName": "Venezia",
      "startUtc": "2026-05-23T04:00:05Z",
      "endUtc": "2026-05-29T21:51:05Z",
      "periodHours": 48,
      "distanceKm": 560.0,
      "freeKm": 720.0,
      "make": "Fiat",
      "model": "Ducato",
      "homeCity": "München"
    },
    {
      "offerId": "247290",
      "originName": "Berglern",
      "destName": "Bergamo",
      "startUtc": "2026-05-23T04:00:05Z",
      "endUtc": "2026-05-29T21:51:05Z",
      "periodHours": 48,
      "distanceKm": 534.6,
      "freeKm": 720.0,
      "make": "Fiat",
      "model": "Ducato",
      "homeCity": "München"
    },
    {
      "offerId": "247291",
      "originName": "Nantes",
      "destName": "Milan",
      "startUtc": "2026-05-23T04:00:05Z",
      "endUtc": "2026-05-31T21:51:05Z",
      "periodHours": 72,
      "distanceKm": 1118.6,
      "freeKm": 1380.0,
      "make": "Pilote",
      "model": "G690 GJ or similar"
    },
    {
      "offerId": "247292",
      "originName": "Nantes",
      "destName": "Milan",
      "startUtc": "2026-05-23T04:00:05Z",
      "endUtc": "2026-05-31T21:51:05Z",
      "periodHours": 72,
      "distanceKm": 1118.6,
      "freeKm": 1380.0,
      "make": "Pilote",
      "model": "G690 GJ or similar"
    },
    {
      "offerId": "247293",
      "originName": "Nantes",
      "destName": "Milan",
      "startUtc": "2026-05-23T04:00:05Z",
      "endUtc": "2026-05-31T21:51:05Z",
      "periodHours": 72,
      "distanceKm": 1118.6,
      "freeKm": 1380.0,
      "make": "Pilote",
      "model": "G690 GJ or similar"
    },
    {
      "offerId": "247294",
      "originName": "Nantes",
      "destName": "Milan",
      "startUtc": "2026-05-23T04:00:05Z",
      "endUtc": "2026-05-31T21:51:05Z",
      "periodHours": 72,
      "distanceKm": 1118.6,
      "freeKm": 1380.0,
      "make": "Pilote",
      "model": "G690 GJ or similar"
    },
    {
      "offerId": "247295",
      "originName": "Berglern",
      "destName": "Berlin",
      "startUtc": "2026-05-23T04:00:05Z",
      "endUtc": "2026-05-29T21:51:05Z",
      "periodHours": 48,
      "distanceKm": 598.2,
      "freeKm": 720.0,
      "make": "Fiat",
      "model": "Ducato",
      "homeCity": "München"
    },
    {
      "offerId": "247297",
      "originName": "Berglern",
      "destName": "Milan",
      "startUtc": "2026-05-23T04:00:05Z",
      "endUtc": "2026-05-29T21:51:05Z",
      "periodHours": 48,
      "distanceKm": 535.0,
      "freeKm": 720.0,
      "make": "Fiat",
      "model": "Ducato",
      "homeCity": "München"
    },
    {
      "offerId": "247298",
      "originName": "Florence",
      "destName": "Milan",
      "startUtc": "2026-05-23T04:00:05Z",
      "endUtc": "2026-05-29T21:51:05Z",
      "periodHours": 24,
      "distanceKm": 345.7,
      "freeKm": 480.0,
      "make": "Fiat",
      "model": "S 75SL / T 7400 SB or similar"
    },
    {
      "offerId": "247299",
      "originName": "Nantes",
      "destName": "Bergamo",
      "startUtc": "2026-05-23T04:00:05Z",
      "endUtc": "2026-06-01T21:51:06Z",
      "periodHours": 72,
      "distanceKm": 1164.9,
      "freeKm": 1380.0,
      "make": "Pilote",
      "model": "G690 GJ or similar"
    },
    {
      "offerId": "247301",
      "originName": "Berglern",
      "destName": "Bologna",
      "startUtc": "2026-05-23T04:00:05Z",
      "endUtc": "2026-05-29T21:51:05Z",
      "periodHours": 48,
      "distanceKm": 580.4,
      "freeKm": 720.0,
      "make": "Fiat",
      "model": "Ducato",
      "homeCity": "München"
    },
    {
      "offerId": "247302",
      "originName": "Florence",
      "destName": "Bergamo",
      "startUtc": "2026-05-23T04:00:05Z",
      "endUtc": "2026-05-29T21:51:05Z",
      "periodHours": 24,
      "distanceKm": 325.4,
      "freeKm": 480.0,
      "make": "Fiat",
      "model": "S 75SL / T 7400 SB or similar"
    },
    {
      "offerId": "247303",
      "originName": "Nantes",
      "destName": "Bergamo",
      "startUtc": "2026-05-23T04:00:05Z",
      "endUtc": "2026-06-01T21:51:06Z",
      "periodHours": 72,
      "distanceKm": 1164.9,
      "freeKm": 1380.0,
      "make": "Pilote",
      "model": "G690 GJ or similar"
    },
    {
      "offerId": "247304",
      "originName": "Florence",
      "destName": "Milan",
      "startUtc": "2026-05-23T04:00:05Z",
      "endUtc": "2026-05-29T21:51:05Z",
      "periodHours": 24,
      "distanceKm": 345.7,
      "freeKm": 480.0,
      "make": "Fiat",
      "model": "S 75SL / T 7400 SB or similar"
    },
    {
      "offerId": "247305",
      "originName": "Florence",
      "destName": "Milan",
      "startUtc": "2026-05-23T04:00:05Z",
      "endUtc": "2026-05-29T21:51:05Z",
      "periodHours": 24,
      "distanceKm": 345.7,
      "freeKm": 480.0,
      "make": "Fiat",
      "model": "S 75SL / T 7400 SB or similar"
    },
    {
      "offerId": "247306",
      "originName": "Florence",
      "destName": "Cagliari",
      "startUtc": "2026-05-23T04:00:05Z",
      "endUtc": "2026-05-29T21:51:05Z",
      "periodHours": 48,
      "distanceKm": 649.4,
      "freeKm": 960.0,
      "make": "Fiat",
      "model": "Ducato"
    },
    {
      "offerId": "247309",
      "originName": "Berglern",
      "destName": "Milan",
      "startUtc": "2026-05-23T04:00:05Z",
      "endUtc": "2026-05-29T21:51:05Z",
      "periodHours": 48,
      "distanceKm": 535.0,
      "freeKm": 720.0,
      "make": "Fiat",
      "model": "Ducato",
      "homeCity": "München"
    },
    {
      "offerId": "247310",
      "originName": "Nantes",
      "destName": "Frankfurt am Main",
      "startUtc": "2026-05-23T04:00:05Z",
      "endUtc": "2026-05-31T21:51:05Z",
      "periodHours": 72,
      "distanceKm": 994.6,
      "freeKm": 1150.0,
      "make": "Pilote",
      "model": "G690 GJ or similar"
    },
    {
      "offerId": "247311",
      "originName": "Berglern",
      "destName": "Venezia",
      "startUtc": "2026-05-23T04:00:05Z",
      "endUtc": "2026-05-29T21:51:05Z",
      "periodHours": 48,
      "distanceKm": 560.0,
      "freeKm": 720.0,
      "make": "Fiat",
      "model": "Ducato",
      "homeCity": "München"
    },
    {
      "offerId": "247312",
      "originName": "Berglern",
      "destName": "Milan",
      "startUtc": "2026-05-23T04:00:05Z",
      "endUtc": "2026-05-29T21:51:05Z",
      "periodHours": 48,
      "distanceKm": 535.0,
      "freeKm": 720.0,
      "make": "Fiat",
      "model": "Ducato",
      "homeCity": "München"
    },
    {
      "offerId": "247313",
      "originName": "Florence",
      "destName": "Cagliari",
      "startUtc": "2026-05-23T04:00:05Z",
      "endUtc": "2026-05-29T21:51:05Z",
      "periodHours": 48,
      "distanceKm": 649.4,
      "freeKm": 960.0,
      "make": "Fiat",
      "model": "Ducato"
    },
    {
      "offerId": "247314",
      "originName": "Berglern",
      "destName": "Milan",
      "startUtc": "2026-05-23T04:00:05Z",
      "endUtc": "2026-05-29T21:51:05Z",
      "periodHours": 48,
      "distanceKm": 535.0,
      "freeKm": 720.0,
      "make": "Fiat",
      "model": "Ducato",
      "homeCity": "München"
    },
    {
      "offerId": "247315",
      "originName": "Hamburg",
      "destName": "Warszawa",
      "startUtc": "2026-05-23T04:00:05Z",
      "endUtc": "2026-05-30T21:51:05Z",
      "periodHours": 72,
      "distanceKm": 851.2,
      "freeKm": 1150.0,
      "make": "Fiat",
      "model": "Ducato"
    },
    {
      "offerId": "247317",
      "originName": "Bologna",
      "destName": "Milan",
      "startUtc": "2026-05-23T04:00:05Z",
      "endUtc": "2026-05-29T21:51:05Z",
      "periodHours": 24,
      "distanceKm": 263.8,
      "freeKm": 480.0,
      "make": "Fiat",
      "model": "S 75SL / T 7400 SB or similar"
    },
    {
      "offerId": "247318",
      "originName": "Nantes",
      "destName": "Milan",
      "startUtc": "2026-05-23T04:00:05Z",
      "endUtc": "2026-05-31T21:51:05Z",
      "periodHours": 72,
      "distanceKm": 1118.6,
      "freeKm": 1380.0,
      "make": "Pilote",
      "model": "G690 GJ or similar"
    },
    {
      "offerId": "247326",
      "originName": "Hamburg",
      "destName": "Warszawa",
      "startUtc": "2026-05-23T04:00:05Z",
      "endUtc": "2026-05-31T21:51:05Z",
      "periodHours": 72,
      "distanceKm": 851.2,
      "freeKm": 1150.0,
      "make": "Fiat",
      "model": "Ducato"
    },
    {
      "offerId": "247328",
      "originName": "Florence",
      "destName": "Olbia",
      "startUtc": "2026-05-23T04:00:05Z",
      "endUtc": "2026-05-29T21:51:05Z",
      "periodHours": 24,
      "distanceKm": 396.0,
      "freeKm": 480.0,
      "make": "Fiat",
      "model": "S 75SL / T 7400 SB or similar"
    },
    {
      "offerId": "247329",
      "originName": "Florence",
      "destName": "Olbia",
      "startUtc": "2026-05-23T04:00:05Z",
      "endUtc": "2026-05-29T21:51:05Z",
      "periodHours": 24,
      "distanceKm": 396.0,
      "freeKm": 480.0,
      "make": "Fiat",
      "model": "S 75SL / T 7400 SB or similar"
    },
    {
      "offerId": "247331",
      "originName": "Venezia",
      "destName": "Essen",
      "startUtc": "2026-05-23T04:00:05Z",
      "endUtc": "2026-06-03T21:51:06Z",
      "periodHours": 72,
      "distanceKm": 1156.1,
      "freeKm": 1380.0,
      "make": "Fiat",
      "model": "Ducato"
    },
    {
      "offerId": "247332",
      "originName": "Venezia",
      "destName": "Essen",
      "startUtc": "2026-05-23T04:00:05Z",
      "endUtc": "2026-06-03T21:51:06Z",
      "periodHours": 72,
      "distanceKm": 1156.1,
      "freeKm": 1380.0,
      "make": "Fiat",
      "model": "Ducato"
    },
    {
      "offerId": "247333",
      "originName": "Venezia",
      "destName": "Essen",
      "startUtc": "2026-05-23T04:00:05Z",
      "endUtc": "2026-06-03T21:51:06Z",
      "periodHours": 72,
      "distanceKm": 1156.1,
      "freeKm": 1380.0,
      "make": "Volkswagen",
      "model": "California"
    },
    {
      "offerId": "247353",
      "originName": "Pisa",
      "destName": "Essen",
      "startUtc": "2026-05-23T04:00:05Z",
      "endUtc": "2026-06-01T21:51:06Z",
      "periodHours": 72,
      "distanceKm": 1181.8,
      "freeKm": 1380.0,
      "make": "Fiat",
      "model": "Ducato"
    },
    {
      "offerId": "247359",
      "originName": "Nantes",
      "destName": "Frankfurt am Main",
      "startUtc": "2026-05-23T04:00:05Z",
      "endUtc": "2026-05-31T21:51:05Z",
      "periodHours": 72,
      "distanceKm": 994.6,
      "freeKm": 1150.0,
      "make": "Pilote",
      "model": "G690 GJ or similar"
    },
    {
      "offerId": "247360",
      "originName": "Berglern",
      "destName": "Olbia",
      "startUtc": "2026-05-23T04:00:05Z",
      "endUtc": "2026-05-31T21:51:05Z",
      "periodHours": 72,
      "distanceKm": 1059.7,
      "freeKm": 1380.0,
      "make": "Fiat",
      "model": "Ducato",
      "homeCity": "München"
    },
    {
      "offerId": "247363",
      "originName": "Roma",
      "destName": "Berglern",
      "startUtc": "2026-05-23T04:00:05Z",
      "endUtc": "2026-05-29T21:51:05Z",
      "periodHours": 72,
      "distanceKm": 963.2,
      "freeKm": 1150.0,
      "make": "Volkswagen",
      "model": "California"
    }
  ],
  "recommended": [
    {
      "score": 168.1,
      "route": [
        "Roma",
        "Berglern",
        "Venezia",
        "Essen",
        "Berlin"
      ],
      "legs": [
        {
          "originName": "Roma",
          "destName": "Berglern",
          "pickup": "2026-05-23T06:00:05+02:00",
          "dropoff": "2026-05-26T06:00:05+02:00",
          "vehicle": "Volkswagen California",
          "make": "Volkswagen",
          "model": "California",
          "distanceKm": 963.2,
          "offerId": "247363"
        },
        {
          "originName": "Berglern",
          "destName": "Venezia",
          "pickup": "2026-05-24T06:00:05+02:00",
          "dropoff": "2026-05-26T06:00:05+02:00",
          "vehicle": "Fiat Ducato",
          "make": "Fiat",
          "model": "Ducato",
          "distanceKm": 560.0,
          "offerId": "247273"
        },
        {
          "originName": "Venezia",
          "destName": "Essen",
          "pickup": "2026-05-25T06:00:05+02:00",
          "dropoff": "2026-05-28T06:00:05+02:00",
          "vehicle": "Fiat Ducato",
          "make": "Fiat",
          "model": "Ducato",
          "distanceKm": 1156.1,
          "offerId": "247331"
        },
        {
          "originName": "Essen",
          "destName": "Berlin",
          "pickup": "2026-05-26T06:00:05+02:00",
          "dropoff": "2026-05-28T06:00:05+02:00",
          "vehicle": "Fiat Ducato",
          "make": "Fiat",
          "model": "Ducato",
          "distanceKm": 539.2,
          "offerId": "247272"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-23T06:00:05+02:00",
      "endUtc": "2026-05-28T06:00:05+02:00",
      "days": 5.0,
      "routeKm": 3218.0,
      "freeKm": 3970.0,
      "spareKm": 752.0,
      "driveHours": 37.858823529411765,
      "countries": [
        "Italy",
        "Germany"
      ],
      "appointment": "23 May – 28 May · Roma → Berlin"
    },
    {
      "score": 157.4,
      "route": [
        "Roma",
        "Berglern",
        "Venezia",
        "Essen"
      ],
      "legs": [
        {
          "originName": "Roma",
          "destName": "Berglern",
          "pickup": "2026-05-23T06:00:05+02:00",
          "dropoff": "2026-05-26T06:00:05+02:00",
          "vehicle": "Volkswagen California",
          "make": "Volkswagen",
          "model": "California",
          "distanceKm": 963.2,
          "offerId": "247363"
        },
        {
          "originName": "Berglern",
          "destName": "Venezia",
          "pickup": "2026-05-24T06:00:05+02:00",
          "dropoff": "2026-05-26T06:00:05+02:00",
          "vehicle": "Fiat Ducato",
          "make": "Fiat",
          "model": "Ducato",
          "distanceKm": 560.0,
          "offerId": "247273"
        },
        {
          "originName": "Venezia",
          "destName": "Essen",
          "pickup": "2026-05-25T06:00:05+02:00",
          "dropoff": "2026-05-28T06:00:05+02:00",
          "vehicle": "Fiat Ducato",
          "make": "Fiat",
          "model": "Ducato",
          "distanceKm": 1156.1,
          "offerId": "247331"
        }
      ],
      "type": "inbound",
      "homeCity": "Bochum",
      "startUtc": "2026-05-23T06:00:05+02:00",
      "endUtc": "2026-05-28T06:00:05+02:00",
      "days": 5.0,
      "routeKm": 2679.0,
      "freeKm": 3250.0,
      "spareKm": 571.0,
      "driveHours": 31.51764705882353,
      "countries": [
        "Italy",
        "Germany"
      ],
      "appointment": "23 May – 28 May · Roma → Essen"
    },
    {
      "score": 155.4,
      "route": [
        "Roma",
        "Berglern",
        "Florence",
        "Cagliari"
      ],
      "legs": [
        {
          "originName": "Roma",
          "destName": "Berglern",
          "pickup": "2026-05-23T06:00:05+02:00",
          "dropoff": "2026-05-26T06:00:05+02:00",
          "vehicle": "Volkswagen California",
          "make": "Volkswagen",
          "model": "California",
          "distanceKm": 963.2,
          "offerId": "247363"
        },
        {
          "originName": "Berglern",
          "destName": "Florence",
          "pickup": "2026-05-24T06:00:05+02:00",
          "dropoff": "2026-05-26T06:00:05+02:00",
          "vehicle": "Fiat Ducato",
          "make": "Fiat",
          "model": "Ducato",
          "distanceKm": 660.8,
          "offerId": "247284"
        },
        {
          "originName": "Florence",
          "destName": "Cagliari",
          "pickup": "2026-05-26T06:00:05+02:00",
          "dropoff": "2026-05-28T06:00:05+02:00",
          "vehicle": "Fiat Ducato",
          "make": "Fiat",
          "model": "Ducato",
          "distanceKm": 649.4,
          "offerId": "247306"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-23T06:00:05+02:00",
      "endUtc": "2026-05-28T06:00:05+02:00",
      "days": 5.0,
      "routeKm": 2273.0,
      "freeKm": 3070.0,
      "spareKm": 797.0,
      "driveHours": 26.741176470588236,
      "countries": [
        "Italy",
        "Germany",
        "Europe"
      ],
      "appointment": "23 May – 28 May · Roma → Cagliari"
    },
    {
      "score": 155.3,
      "route": [
        "Berglern",
        "Venezia",
        "Essen",
        "Berlin"
      ],
      "legs": [
        {
          "originName": "Berglern",
          "destName": "Venezia",
          "pickup": "2026-05-23T06:00:05+02:00",
          "dropoff": "2026-05-25T06:00:05+02:00",
          "vehicle": "Fiat Ducato",
          "make": "Fiat",
          "model": "Ducato",
          "distanceKm": 560.0,
          "offerId": "247273"
        },
        {
          "originName": "Venezia",
          "destName": "Essen",
          "pickup": "2026-05-24T06:00:05+02:00",
          "dropoff": "2026-05-27T06:00:05+02:00",
          "vehicle": "Fiat Ducato",
          "make": "Fiat",
          "model": "Ducato",
          "distanceKm": 1156.1,
          "offerId": "247331"
        },
        {
          "originName": "Essen",
          "destName": "Berlin",
          "pickup": "2026-05-26T06:00:05+02:00",
          "dropoff": "2026-05-28T06:00:05+02:00",
          "vehicle": "Fiat Ducato",
          "make": "Fiat",
          "model": "Ducato",
          "distanceKm": 539.2,
          "offerId": "247272"
        }
      ],
      "type": "oneway",
      "homeCity": "München",
      "startUtc": "2026-05-23T06:00:05+02:00",
      "endUtc": "2026-05-28T06:00:05+02:00",
      "days": 5.0,
      "routeKm": 2255.0,
      "freeKm": 2820.0,
      "spareKm": 565.0,
      "driveHours": 26.529411764705884,
      "countries": [
        "Germany",
        "Italy"
      ],
      "appointment": "23 May – 28 May · Berglern → Berlin"
    },
    {
      "score": 154.1,
      "route": [
        "Roma",
        "Berglern",
        "Florence",
        "Olbia"
      ],
      "legs": [
        {
          "originName": "Roma",
          "destName": "Berglern",
          "pickup": "2026-05-23T06:00:05+02:00",
          "dropoff": "2026-05-26T06:00:05+02:00",
          "vehicle": "Volkswagen California",
          "make": "Volkswagen",
          "model": "California",
          "distanceKm": 963.2,
          "offerId": "247363"
        },
        {
          "originName": "Berglern",
          "destName": "Florence",
          "pickup": "2026-05-24T06:00:05+02:00",
          "dropoff": "2026-05-26T06:00:05+02:00",
          "vehicle": "Fiat Ducato",
          "make": "Fiat",
          "model": "Ducato",
          "distanceKm": 660.8,
          "offerId": "247284"
        },
        {
          "originName": "Florence",
          "destName": "Olbia",
          "pickup": "2026-05-27T06:00:05+02:00",
          "dropoff": "2026-05-28T06:00:05+02:00",
          "vehicle": "Fiat Ducato",
          "make": "Fiat",
          "model": "Ducato",
          "distanceKm": 396.0,
          "offerId": "247275"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-23T06:00:05+02:00",
      "endUtc": "2026-05-28T06:00:05+02:00",
      "days": 5.0,
      "routeKm": 2020.0,
      "freeKm": 2590.0,
      "spareKm": 570.0,
      "driveHours": 23.764705882352942,
      "countries": [
        "Italy",
        "Germany",
        "Europe"
      ],
      "appointment": "23 May – 28 May · Roma → Olbia"
    },
    {
      "score": 153.8,
      "route": [
        "Roma",
        "Berglern",
        "Florence",
        "Milan"
      ],
      "legs": [
        {
          "originName": "Roma",
          "destName": "Berglern",
          "pickup": "2026-05-23T06:00:05+02:00",
          "dropoff": "2026-05-26T06:00:05+02:00",
          "vehicle": "Volkswagen California",
          "make": "Volkswagen",
          "model": "California",
          "distanceKm": 963.2,
          "offerId": "247363"
        },
        {
          "originName": "Berglern",
          "destName": "Florence",
          "pickup": "2026-05-24T06:00:05+02:00",
          "dropoff": "2026-05-26T06:00:05+02:00",
          "vehicle": "Fiat Ducato",
          "make": "Fiat",
          "model": "Ducato",
          "distanceKm": 660.8,
          "offerId": "247284"
        },
        {
          "originName": "Florence",
          "destName": "Milan",
          "pickup": "2026-05-27T06:00:05+02:00",
          "dropoff": "2026-05-28T06:00:05+02:00",
          "vehicle": "Fiat S 75SL / T 7400 SB or similar",
          "make": "Fiat",
          "model": "S 75SL / T 7400 SB or similar",
          "distanceKm": 345.7,
          "offerId": "247281"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-23T06:00:05+02:00",
      "endUtc": "2026-05-28T06:00:05+02:00",
      "days": 5.0,
      "routeKm": 1970.0,
      "freeKm": 2590.0,
      "spareKm": 620.0,
      "driveHours": 23.176470588235293,
      "countries": [
        "Italy",
        "Germany"
      ],
      "appointment": "23 May – 28 May · Roma → Milan"
    },
    {
      "score": 153.7,
      "route": [
        "Roma",
        "Berglern",
        "Florence",
        "Bergamo"
      ],
      "legs": [
        {
          "originName": "Roma",
          "destName": "Berglern",
          "pickup": "2026-05-23T06:00:05+02:00",
          "dropoff": "2026-05-26T06:00:05+02:00",
          "vehicle": "Volkswagen California",
          "make": "Volkswagen",
          "model": "California",
          "distanceKm": 963.2,
          "offerId": "247363"
        },
        {
          "originName": "Berglern",
          "destName": "Florence",
          "pickup": "2026-05-24T06:00:05+02:00",
          "dropoff": "2026-05-26T06:00:05+02:00",
          "vehicle": "Fiat Ducato",
          "make": "Fiat",
          "model": "Ducato",
          "distanceKm": 660.8,
          "offerId": "247284"
        },
        {
          "originName": "Florence",
          "destName": "Bergamo",
          "pickup": "2026-05-27T06:00:05+02:00",
          "dropoff": "2026-05-28T06:00:05+02:00",
          "vehicle": "Fiat S 75SL / T 7400 SB or similar",
          "make": "Fiat",
          "model": "S 75SL / T 7400 SB or similar",
          "distanceKm": 325.4,
          "offerId": "247276"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-23T06:00:05+02:00",
      "endUtc": "2026-05-28T06:00:05+02:00",
      "days": 5.0,
      "routeKm": 1949.0,
      "freeKm": 2590.0,
      "spareKm": 641.0,
      "driveHours": 22.929411764705883,
      "countries": [
        "Italy",
        "Germany"
      ],
      "appointment": "23 May – 28 May · Roma → Bergamo"
    },
    {
      "score": 153.0,
      "route": [
        "Roma",
        "Berglern",
        "Bologna",
        "Milan"
      ],
      "legs": [
        {
          "originName": "Roma",
          "destName": "Berglern",
          "pickup": "2026-05-23T06:00:05+02:00",
          "dropoff": "2026-05-26T06:00:05+02:00",
          "vehicle": "Volkswagen California",
          "make": "Volkswagen",
          "model": "California",
          "distanceKm": 963.2,
          "offerId": "247363"
        },
        {
          "originName": "Berglern",
          "destName": "Bologna",
          "pickup": "2026-05-24T06:00:05+02:00",
          "dropoff": "2026-05-26T06:00:05+02:00",
          "vehicle": "Fiat Ducato",
          "make": "Fiat",
          "model": "Ducato",
          "distanceKm": 580.4,
          "offerId": "247301"
        },
        {
          "originName": "Bologna",
          "destName": "Milan",
          "pickup": "2026-05-27T06:00:05+02:00",
          "dropoff": "2026-05-28T06:00:05+02:00",
          "vehicle": "Fiat S 75SL / T 7400 SB or similar",
          "make": "Fiat",
          "model": "S 75SL / T 7400 SB or similar",
          "distanceKm": 263.8,
          "offerId": "247317"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-23T06:00:05+02:00",
      "endUtc": "2026-05-28T06:00:05+02:00",
      "days": 5.0,
      "routeKm": 1807.0,
      "freeKm": 2350.0,
      "spareKm": 543.0,
      "driveHours": 21.258823529411764,
      "countries": [
        "Italy",
        "Germany"
      ],
      "appointment": "23 May – 28 May · Roma → Milan"
    },
    {
      "score": 144.6,
      "route": [
        "Berglern",
        "Venezia",
        "Essen"
      ],
      "legs": [
        {
          "originName": "Berglern",
          "destName": "Venezia",
          "pickup": "2026-05-23T06:00:05+02:00",
          "dropoff": "2026-05-25T06:00:05+02:00",
          "vehicle": "Fiat Ducato",
          "make": "Fiat",
          "model": "Ducato",
          "distanceKm": 560.0,
          "offerId": "247273"
        },
        {
          "originName": "Venezia",
          "destName": "Essen",
          "pickup": "2026-05-25T06:00:05+02:00",
          "dropoff": "2026-05-28T06:00:05+02:00",
          "vehicle": "Fiat Ducato",
          "make": "Fiat",
          "model": "Ducato",
          "distanceKm": 1156.1,
          "offerId": "247331"
        }
      ],
      "type": "oneway",
      "homeCity": "München",
      "startUtc": "2026-05-23T06:00:05+02:00",
      "endUtc": "2026-05-28T06:00:05+02:00",
      "days": 5.0,
      "routeKm": 1716.0,
      "freeKm": 2100.0,
      "spareKm": 384.0,
      "driveHours": 20.188235294117646,
      "countries": [
        "Germany",
        "Italy"
      ],
      "appointment": "23 May – 28 May · Berglern → Essen"
    },
    {
      "score": 144.1,
      "route": [
        "Roma",
        "Berglern",
        "Florence"
      ],
      "legs": [
        {
          "originName": "Roma",
          "destName": "Berglern",
          "pickup": "2026-05-23T06:00:05+02:00",
          "dropoff": "2026-05-26T06:00:05+02:00",
          "vehicle": "Volkswagen California",
          "make": "Volkswagen",
          "model": "California",
          "distanceKm": 963.2,
          "offerId": "247363"
        },
        {
          "originName": "Berglern",
          "destName": "Florence",
          "pickup": "2026-05-26T06:00:05+02:00",
          "dropoff": "2026-05-28T06:00:05+02:00",
          "vehicle": "Fiat Ducato",
          "make": "Fiat",
          "model": "Ducato",
          "distanceKm": 660.8,
          "offerId": "247284"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-23T06:00:05+02:00",
      "endUtc": "2026-05-28T06:00:05+02:00",
      "days": 5.0,
      "routeKm": 1624.0,
      "freeKm": 2110.0,
      "spareKm": 486.0,
      "driveHours": 19.105882352941176,
      "countries": [
        "Italy",
        "Germany"
      ],
      "appointment": "23 May – 28 May · Roma → Florence"
    },
    {
      "score": 143.7,
      "route": [
        "Roma",
        "Berglern",
        "Bologna"
      ],
      "legs": [
        {
          "originName": "Roma",
          "destName": "Berglern",
          "pickup": "2026-05-23T06:00:05+02:00",
          "dropoff": "2026-05-26T06:00:05+02:00",
          "vehicle": "Volkswagen California",
          "make": "Volkswagen",
          "model": "California",
          "distanceKm": 963.2,
          "offerId": "247363"
        },
        {
          "originName": "Berglern",
          "destName": "Bologna",
          "pickup": "2026-05-26T06:00:05+02:00",
          "dropoff": "2026-05-28T06:00:05+02:00",
          "vehicle": "Fiat Ducato",
          "make": "Fiat",
          "model": "Ducato",
          "distanceKm": 580.4,
          "offerId": "247301"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-23T06:00:05+02:00",
      "endUtc": "2026-05-28T06:00:05+02:00",
      "days": 5.0,
      "routeKm": 1544.0,
      "freeKm": 1870.0,
      "spareKm": 326.0,
      "driveHours": 18.16470588235294,
      "countries": [
        "Italy",
        "Germany"
      ],
      "appointment": "23 May – 28 May · Roma → Bologna"
    },
    {
      "score": 143.6,
      "route": [
        "Roma",
        "Berglern",
        "Venezia"
      ],
      "legs": [
        {
          "originName": "Roma",
          "destName": "Berglern",
          "pickup": "2026-05-23T06:00:05+02:00",
          "dropoff": "2026-05-26T06:00:05+02:00",
          "vehicle": "Volkswagen California",
          "make": "Volkswagen",
          "model": "California",
          "distanceKm": 963.2,
          "offerId": "247363"
        },
        {
          "originName": "Berglern",
          "destName": "Venezia",
          "pickup": "2026-05-26T06:00:05+02:00",
          "dropoff": "2026-05-28T06:00:05+02:00",
          "vehicle": "Fiat Ducato",
          "make": "Fiat",
          "model": "Ducato",
          "distanceKm": 560.0,
          "offerId": "247273"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-23T06:00:05+02:00",
      "endUtc": "2026-05-28T06:00:05+02:00",
      "days": 5.0,
      "routeKm": 1523.0,
      "freeKm": 1870.0,
      "spareKm": 347.0,
      "driveHours": 17.91764705882353,
      "countries": [
        "Italy",
        "Germany"
      ],
      "appointment": "23 May – 28 May · Roma → Venezia"
    },
    {
      "score": 143.5,
      "route": [
        "Roma",
        "Berglern",
        "Milan"
      ],
      "legs": [
        {
          "originName": "Roma",
          "destName": "Berglern",
          "pickup": "2026-05-23T06:00:05+02:00",
          "dropoff": "2026-05-26T06:00:05+02:00",
          "vehicle": "Volkswagen California",
          "make": "Volkswagen",
          "model": "California",
          "distanceKm": 963.2,
          "offerId": "247363"
        },
        {
          "originName": "Berglern",
          "destName": "Milan",
          "pickup": "2026-05-26T06:00:05+02:00",
          "dropoff": "2026-05-28T06:00:05+02:00",
          "vehicle": "Fiat Ducato",
          "make": "Fiat",
          "model": "Ducato",
          "distanceKm": 535.0,
          "offerId": "247297"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-23T06:00:05+02:00",
      "endUtc": "2026-05-28T06:00:05+02:00",
      "days": 5.0,
      "routeKm": 1498.0,
      "freeKm": 1870.0,
      "spareKm": 372.0,
      "driveHours": 17.623529411764707,
      "countries": [
        "Italy",
        "Germany"
      ],
      "appointment": "23 May – 28 May · Roma → Milan"
    },
    {
      "score": 143.5,
      "route": [
        "Roma",
        "Berglern",
        "Bergamo"
      ],
      "legs": [
        {
          "originName": "Roma",
          "destName": "Berglern",
          "pickup": "2026-05-23T06:00:05+02:00",
          "dropoff": "2026-05-26T06:00:05+02:00",
          "vehicle": "Volkswagen California",
          "make": "Volkswagen",
          "model": "California",
          "distanceKm": 963.2,
          "offerId": "247363"
        },
        {
          "originName": "Berglern",
          "destName": "Bergamo",
          "pickup": "2026-05-26T06:00:05+02:00",
          "dropoff": "2026-05-28T06:00:05+02:00",
          "vehicle": "Fiat Ducato",
          "make": "Fiat",
          "model": "Ducato",
          "distanceKm": 534.6,
          "offerId": "247290"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-23T06:00:05+02:00",
      "endUtc": "2026-05-28T06:00:05+02:00",
      "days": 5.0,
      "routeKm": 1498.0,
      "freeKm": 1870.0,
      "spareKm": 372.0,
      "driveHours": 17.623529411764707,
      "countries": [
        "Italy",
        "Germany"
      ],
      "appointment": "23 May – 28 May · Roma → Bergamo"
    },
    {
      "score": 142.6,
      "route": [
        "Berglern",
        "Florence",
        "Cagliari"
      ],
      "legs": [
        {
          "originName": "Berglern",
          "destName": "Florence",
          "pickup": "2026-05-23T06:00:05+02:00",
          "dropoff": "2026-05-25T06:00:05+02:00",
          "vehicle": "Fiat Ducato",
          "make": "Fiat",
          "model": "Ducato",
          "distanceKm": 660.8,
          "offerId": "247284"
        },
        {
          "originName": "Florence",
          "destName": "Cagliari",
          "pickup": "2026-05-26T06:00:05+02:00",
          "dropoff": "2026-05-28T06:00:05+02:00",
          "vehicle": "Fiat Ducato",
          "make": "Fiat",
          "model": "Ducato",
          "distanceKm": 649.4,
          "offerId": "247306"
        }
      ],
      "type": "oneway",
      "homeCity": "München",
      "startUtc": "2026-05-23T06:00:05+02:00",
      "endUtc": "2026-05-28T06:00:05+02:00",
      "days": 5.0,
      "routeKm": 1310.0,
      "freeKm": 1920.0,
      "spareKm": 610.0,
      "driveHours": 15.411764705882353,
      "countries": [
        "Germany",
        "Italy",
        "Europe"
      ],
      "appointment": "23 May – 28 May · Berglern → Cagliari"
    },
    {
      "score": 141.3,
      "route": [
        "Berglern",
        "Florence",
        "Olbia"
      ],
      "legs": [
        {
          "originName": "Berglern",
          "destName": "Florence",
          "pickup": "2026-05-23T06:00:05+02:00",
          "dropoff": "2026-05-25T06:00:05+02:00",
          "vehicle": "Fiat Ducato",
          "make": "Fiat",
          "model": "Ducato",
          "distanceKm": 660.8,
          "offerId": "247284"
        },
        {
          "originName": "Florence",
          "destName": "Olbia",
          "pickup": "2026-05-27T06:00:05+02:00",
          "dropoff": "2026-05-28T06:00:05+02:00",
          "vehicle": "Fiat Ducato",
          "make": "Fiat",
          "model": "Ducato",
          "distanceKm": 396.0,
          "offerId": "247275"
        }
      ],
      "type": "oneway",
      "homeCity": "München",
      "startUtc": "2026-05-23T06:00:05+02:00",
      "endUtc": "2026-05-28T06:00:05+02:00",
      "days": 5.0,
      "routeKm": 1057.0,
      "freeKm": 1440.0,
      "spareKm": 383.0,
      "driveHours": 12.435294117647059,
      "countries": [
        "Germany",
        "Italy",
        "Europe"
      ],
      "appointment": "23 May – 28 May · Berglern → Olbia"
    },
    {
      "score": 141.0,
      "route": [
        "Berglern",
        "Florence",
        "Milan"
      ],
      "legs": [
        {
          "originName": "Berglern",
          "destName": "Florence",
          "pickup": "2026-05-23T06:00:05+02:00",
          "dropoff": "2026-05-25T06:00:05+02:00",
          "vehicle": "Fiat Ducato",
          "make": "Fiat",
          "model": "Ducato",
          "distanceKm": 660.8,
          "offerId": "247284"
        },
        {
          "originName": "Florence",
          "destName": "Milan",
          "pickup": "2026-05-27T06:00:05+02:00",
          "dropoff": "2026-05-28T06:00:05+02:00",
          "vehicle": "Fiat S 75SL / T 7400 SB or similar",
          "make": "Fiat",
          "model": "S 75SL / T 7400 SB or similar",
          "distanceKm": 345.7,
          "offerId": "247281"
        }
      ],
      "type": "oneway",
      "homeCity": "München",
      "startUtc": "2026-05-23T06:00:05+02:00",
      "endUtc": "2026-05-28T06:00:05+02:00",
      "days": 5.0,
      "routeKm": 1006.0,
      "freeKm": 1440.0,
      "spareKm": 434.0,
      "driveHours": 11.83529411764706,
      "countries": [
        "Germany",
        "Italy"
      ],
      "appointment": "23 May – 28 May · Berglern → Milan"
    },
    {
      "score": 140.9,
      "route": [
        "Berglern",
        "Florence",
        "Bergamo"
      ],
      "legs": [
        {
          "originName": "Berglern",
          "destName": "Florence",
          "pickup": "2026-05-23T06:00:05+02:00",
          "dropoff": "2026-05-25T06:00:05+02:00",
          "vehicle": "Fiat Ducato",
          "make": "Fiat",
          "model": "Ducato",
          "distanceKm": 660.8,
          "offerId": "247284"
        },
        {
          "originName": "Florence",
          "destName": "Bergamo",
          "pickup": "2026-05-27T06:00:05+02:00",
          "dropoff": "2026-05-28T06:00:05+02:00",
          "vehicle": "Fiat S 75SL / T 7400 SB or similar",
          "make": "Fiat",
          "model": "S 75SL / T 7400 SB or similar",
          "distanceKm": 325.4,
          "offerId": "247276"
        }
      ],
      "type": "oneway",
      "homeCity": "München",
      "startUtc": "2026-05-23T06:00:05+02:00",
      "endUtc": "2026-05-28T06:00:05+02:00",
      "days": 5.0,
      "routeKm": 986.0,
      "freeKm": 1440.0,
      "spareKm": 454.0,
      "driveHours": 11.6,
      "countries": [
        "Germany",
        "Italy"
      ],
      "appointment": "23 May – 28 May · Berglern → Bergamo"
    },
    {
      "score": 140.2,
      "route": [
        "Berglern",
        "Bologna",
        "Milan"
      ],
      "legs": [
        {
          "originName": "Berglern",
          "destName": "Bologna",
          "pickup": "2026-05-23T06:00:05+02:00",
          "dropoff": "2026-05-25T06:00:05+02:00",
          "vehicle": "Fiat Ducato",
          "make": "Fiat",
          "model": "Ducato",
          "distanceKm": 580.4,
          "offerId": "247301"
        },
        {
          "originName": "Bologna",
          "destName": "Milan",
          "pickup": "2026-05-27T06:00:05+02:00",
          "dropoff": "2026-05-28T06:00:05+02:00",
          "vehicle": "Fiat S 75SL / T 7400 SB or similar",
          "make": "Fiat",
          "model": "S 75SL / T 7400 SB or similar",
          "distanceKm": 263.8,
          "offerId": "247317"
        }
      ],
      "type": "oneway",
      "homeCity": "München",
      "startUtc": "2026-05-23T06:00:05+02:00",
      "endUtc": "2026-05-28T06:00:05+02:00",
      "days": 5.0,
      "routeKm": 844.0,
      "freeKm": 1200.0,
      "spareKm": 356.0,
      "driveHours": 9.929411764705883,
      "countries": [
        "Germany",
        "Italy"
      ],
      "appointment": "23 May – 28 May · Berglern → Milan"
    },
    {
      "score": 129.8,
      "route": [
        "Nantes",
        "Bergamo"
      ],
      "legs": [
        {
          "originName": "Nantes",
          "destName": "Bergamo",
          "pickup": "2026-05-23T06:00:05+02:00",
          "dropoff": "2026-05-26T06:00:05+02:00",
          "vehicle": "Pilote G690 GJ or similar",
          "make": "Pilote",
          "model": "G690 GJ or similar",
          "distanceKm": 1164.9,
          "offerId": "247299"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-23T06:00:05+02:00",
      "endUtc": "2026-05-26T06:00:05+02:00",
      "days": 3.0,
      "routeKm": 1165.0,
      "freeKm": 1380.0,
      "spareKm": 215.0,
      "driveHours": 13.705882352941176,
      "countries": [
        "France",
        "Italy"
      ],
      "appointment": "23 May – 26 May · Nantes → Bergamo"
    },
    {
      "score": 129.6,
      "route": [
        "Nantes",
        "Milan"
      ],
      "legs": [
        {
          "originName": "Nantes",
          "destName": "Milan",
          "pickup": "2026-05-23T06:00:05+02:00",
          "dropoff": "2026-05-26T06:00:05+02:00",
          "vehicle": "Pilote G690 GJ or similar",
          "make": "Pilote",
          "model": "G690 GJ or similar",
          "distanceKm": 1118.6,
          "offerId": "247286"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-23T06:00:05+02:00",
      "endUtc": "2026-05-26T06:00:05+02:00",
      "days": 3.0,
      "routeKm": 1119.0,
      "freeKm": 1380.0,
      "spareKm": 261.0,
      "driveHours": 13.16470588235294,
      "countries": [
        "France",
        "Italy"
      ],
      "appointment": "23 May – 26 May · Nantes → Milan"
    },
    {
      "score": 129.4,
      "route": [
        "Roma",
        "Stuttgart"
      ],
      "legs": [
        {
          "originName": "Roma",
          "destName": "Stuttgart",
          "pickup": "2026-05-23T06:00:05+02:00",
          "dropoff": "2026-05-26T06:00:05+02:00",
          "vehicle": "Volkswagen California",
          "make": "Volkswagen",
          "model": "California",
          "distanceKm": 1087.9,
          "offerId": "247267"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-23T06:00:05+02:00",
      "endUtc": "2026-05-26T06:00:05+02:00",
      "days": 3.0,
      "routeKm": 1088.0,
      "freeKm": 1380.0,
      "spareKm": 292.0,
      "driveHours": 12.8,
      "countries": [
        "Italy",
        "Germany"
      ],
      "appointment": "23 May – 26 May · Roma → Stuttgart"
    },
    {
      "score": 128.0,
      "route": [
        "Marburg",
        "Graz"
      ],
      "legs": [
        {
          "originName": "Marburg",
          "destName": "Graz",
          "pickup": "2026-05-22T00:00:00+02:00",
          "dropoff": "2026-05-25T00:00:00+02:00",
          "vehicle": "CAMPER CABIN DELUXE Ford Nugget Plus - Ford Transit Custom V362",
          "make": "CAMPER CABIN DELUXE",
          "model": "Ford Nugget Plus - Ford Transit Custom V362",
          "distanceKm": 807.8,
          "offerId": "245850"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-22T00:00:00+02:00",
      "endUtc": "2026-05-25T00:00:00+02:00",
      "days": 3.0,
      "routeKm": 808.0,
      "freeKm": 1400.0,
      "spareKm": 592.0,
      "driveHours": 9.505882352941176,
      "countries": [
        "Germany",
        "Austria"
      ],
      "appointment": "22 May – 25 May · Marburg → Graz"
    },
    {
      "score": 126.1,
      "route": [
        "Roma",
        "Berglern",
        "Olbia"
      ],
      "legs": [
        {
          "originName": "Roma",
          "destName": "Berglern",
          "pickup": "2026-05-23T06:00:05+02:00",
          "dropoff": "2026-05-26T06:00:05+02:00",
          "vehicle": "Volkswagen California",
          "make": "Volkswagen",
          "model": "California",
          "distanceKm": 963.2,
          "offerId": "247363"
        },
        {
          "originName": "Berglern",
          "destName": "Olbia",
          "pickup": "2026-05-25T06:00:05+02:00",
          "dropoff": "2026-05-28T06:00:05+02:00",
          "vehicle": "Fiat Ducato",
          "make": "Fiat",
          "model": "Ducato",
          "distanceKm": 1059.7,
          "offerId": "247360"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-23T06:00:05+02:00",
      "endUtc": "2026-05-28T06:00:05+02:00",
      "days": 5.0,
      "routeKm": 2023.0,
      "freeKm": 2530.0,
      "spareKm": 507.0,
      "driveHours": 23.8,
      "countries": [
        "Italy",
        "Germany",
        "Europe"
      ],
      "appointment": "23 May – 28 May · Roma → Olbia"
    },
    {
      "score": 125.4,
      "route": [
        "Amstelveen",
        "Stuttgart"
      ],
      "legs": [
        {
          "originName": "Amstelveen",
          "destName": "Stuttgart",
          "pickup": "2026-05-23T06:00:05+02:00",
          "dropoff": "2026-05-25T06:00:05+02:00",
          "vehicle": "Volkswagen California",
          "make": "Volkswagen",
          "model": "California",
          "distanceKm": 681.9,
          "offerId": "247266"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-23T06:00:05+02:00",
      "endUtc": "2026-05-25T06:00:05+02:00",
      "days": 2.0,
      "routeKm": 682.0,
      "freeKm": 960.0,
      "spareKm": 278.0,
      "driveHours": 8.023529411764706,
      "countries": [
        "Europe",
        "Germany"
      ],
      "appointment": "23 May – 25 May · Amstelveen → Stuttgart"
    },
    {
      "score": 125.3,
      "route": [
        "Berglern",
        "Florence"
      ],
      "legs": [
        {
          "originName": "Berglern",
          "destName": "Florence",
          "pickup": "2026-05-23T06:00:05+02:00",
          "dropoff": "2026-05-25T06:00:05+02:00",
          "vehicle": "Fiat Ducato",
          "make": "Fiat",
          "model": "Ducato",
          "distanceKm": 660.8,
          "offerId": "247284"
        }
      ],
      "type": "oneway",
      "homeCity": "München",
      "startUtc": "2026-05-23T06:00:05+02:00",
      "endUtc": "2026-05-25T06:00:05+02:00",
      "days": 2.0,
      "routeKm": 661.0,
      "freeKm": 960.0,
      "spareKm": 299.0,
      "driveHours": 7.776470588235294,
      "countries": [
        "Germany",
        "Italy"
      ],
      "appointment": "23 May – 25 May · Berglern → Florence"
    },
    {
      "score": 124.9,
      "route": [
        "Berglern",
        "Bologna"
      ],
      "legs": [
        {
          "originName": "Berglern",
          "destName": "Bologna",
          "pickup": "2026-05-23T06:00:05+02:00",
          "dropoff": "2026-05-25T06:00:05+02:00",
          "vehicle": "Fiat Ducato",
          "make": "Fiat",
          "model": "Ducato",
          "distanceKm": 580.4,
          "offerId": "247301"
        }
      ],
      "type": "oneway",
      "homeCity": "München",
      "startUtc": "2026-05-23T06:00:05+02:00",
      "endUtc": "2026-05-25T06:00:05+02:00",
      "days": 2.0,
      "routeKm": 580.0,
      "freeKm": 720.0,
      "spareKm": 140.0,
      "driveHours": 6.823529411764706,
      "countries": [
        "Germany",
        "Italy"
      ],
      "appointment": "23 May – 25 May · Berglern → Bologna"
    },
    {
      "score": 124.8,
      "route": [
        "Berglern",
        "Venezia"
      ],
      "legs": [
        {
          "originName": "Berglern",
          "destName": "Venezia",
          "pickup": "2026-05-23T06:00:05+02:00",
          "dropoff": "2026-05-25T06:00:05+02:00",
          "vehicle": "Fiat Ducato",
          "make": "Fiat",
          "model": "Ducato",
          "distanceKm": 560.0,
          "offerId": "247273"
        }
      ],
      "type": "oneway",
      "homeCity": "München",
      "startUtc": "2026-05-23T06:00:05+02:00",
      "endUtc": "2026-05-25T06:00:05+02:00",
      "days": 2.0,
      "routeKm": 560.0,
      "freeKm": 720.0,
      "spareKm": 160.0,
      "driveHours": 6.588235294117647,
      "countries": [
        "Germany",
        "Italy"
      ],
      "appointment": "23 May – 25 May · Berglern → Venezia"
    },
    {
      "score": 124.7,
      "route": [
        "Berglern",
        "Milan"
      ],
      "legs": [
        {
          "originName": "Berglern",
          "destName": "Milan",
          "pickup": "2026-05-23T06:00:05+02:00",
          "dropoff": "2026-05-25T06:00:05+02:00",
          "vehicle": "Fiat Ducato",
          "make": "Fiat",
          "model": "Ducato",
          "distanceKm": 535.0,
          "offerId": "247297"
        }
      ],
      "type": "oneway",
      "homeCity": "München",
      "startUtc": "2026-05-23T06:00:05+02:00",
      "endUtc": "2026-05-25T06:00:05+02:00",
      "days": 2.0,
      "routeKm": 535.0,
      "freeKm": 720.0,
      "spareKm": 185.0,
      "driveHours": 6.294117647058823,
      "countries": [
        "Germany",
        "Italy"
      ],
      "appointment": "23 May – 25 May · Berglern → Milan"
    },
    {
      "score": 124.7,
      "route": [
        "Berglern",
        "Bergamo"
      ],
      "legs": [
        {
          "originName": "Berglern",
          "destName": "Bergamo",
          "pickup": "2026-05-23T06:00:05+02:00",
          "dropoff": "2026-05-25T06:00:05+02:00",
          "vehicle": "Fiat Ducato",
          "make": "Fiat",
          "model": "Ducato",
          "distanceKm": 534.6,
          "offerId": "247290"
        }
      ],
      "type": "oneway",
      "homeCity": "München",
      "startUtc": "2026-05-23T06:00:05+02:00",
      "endUtc": "2026-05-25T06:00:05+02:00",
      "days": 2.0,
      "routeKm": 535.0,
      "freeKm": 720.0,
      "spareKm": 185.0,
      "driveHours": 6.294117647058823,
      "countries": [
        "Germany",
        "Italy"
      ],
      "appointment": "23 May – 25 May · Berglern → Bergamo"
    },
    {
      "score": 124.6,
      "route": [
        "Pisa",
        "Essen",
        "Berlin"
      ],
      "legs": [
        {
          "originName": "Pisa",
          "destName": "Essen",
          "pickup": "2026-05-23T06:00:05+02:00",
          "dropoff": "2026-05-26T06:00:05+02:00",
          "vehicle": "Fiat Ducato",
          "make": "Fiat",
          "model": "Ducato",
          "distanceKm": 1181.8,
          "offerId": "247353"
        },
        {
          "originName": "Essen",
          "destName": "Berlin",
          "pickup": "2026-05-26T06:00:05+02:00",
          "dropoff": "2026-05-28T06:00:05+02:00",
          "vehicle": "Fiat Ducato",
          "make": "Fiat",
          "model": "Ducato",
          "distanceKm": 539.2,
          "offerId": "247272"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-23T06:00:05+02:00",
      "endUtc": "2026-05-28T06:00:05+02:00",
      "days": 5.0,
      "routeKm": 1721.0,
      "freeKm": 2100.0,
      "spareKm": 379.0,
      "driveHours": 20.24705882352941,
      "countries": [
        "Europe",
        "Germany"
      ],
      "appointment": "23 May – 28 May · Pisa → Berlin"
    },
    {
      "score": 124.5,
      "route": [
        "Venezia",
        "Essen",
        "Berlin"
      ],
      "legs": [
        {
          "originName": "Venezia",
          "destName": "Essen",
          "pickup": "2026-05-23T06:00:05+02:00",
          "dropoff": "2026-05-26T06:00:05+02:00",
          "vehicle": "Fiat Ducato",
          "make": "Fiat",
          "model": "Ducato",
          "distanceKm": 1156.1,
          "offerId": "247331"
        },
        {
          "originName": "Essen",
          "destName": "Berlin",
          "pickup": "2026-05-26T06:00:05+02:00",
          "dropoff": "2026-05-28T06:00:05+02:00",
          "vehicle": "Fiat Ducato",
          "make": "Fiat",
          "model": "Ducato",
          "distanceKm": 539.2,
          "offerId": "247272"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-23T06:00:05+02:00",
      "endUtc": "2026-05-28T06:00:05+02:00",
      "days": 5.0,
      "routeKm": 1695.0,
      "freeKm": 2100.0,
      "spareKm": 405.0,
      "driveHours": 19.941176470588236,
      "countries": [
        "Italy",
        "Germany"
      ],
      "appointment": "23 May – 28 May · Venezia → Berlin"
    },
    {
      "score": 123.8,
      "route": [
        "Roma",
        "Berglern",
        "Berlin"
      ],
      "legs": [
        {
          "originName": "Roma",
          "destName": "Berglern",
          "pickup": "2026-05-23T06:00:05+02:00",
          "dropoff": "2026-05-26T06:00:05+02:00",
          "vehicle": "Volkswagen California",
          "make": "Volkswagen",
          "model": "California",
          "distanceKm": 963.2,
          "offerId": "247363"
        },
        {
          "originName": "Berglern",
          "destName": "Berlin",
          "pickup": "2026-05-26T06:00:05+02:00",
          "dropoff": "2026-05-28T06:00:05+02:00",
          "vehicle": "Fiat Ducato",
          "make": "Fiat",
          "model": "Ducato",
          "distanceKm": 598.2,
          "offerId": "247282"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-23T06:00:05+02:00",
      "endUtc": "2026-05-28T06:00:05+02:00",
      "days": 5.0,
      "routeKm": 1561.0,
      "freeKm": 1870.0,
      "spareKm": 309.0,
      "driveHours": 18.36470588235294,
      "countries": [
        "Italy",
        "Germany"
      ],
      "appointment": "23 May – 28 May · Roma → Berlin"
    },
    {
      "score": 122.1,
      "route": [
        "Marburg",
        "Champlan",
        "Frankfurt am Main"
      ],
      "legs": [
        {
          "originName": "Marburg",
          "destName": "Champlan",
          "pickup": "2026-05-22T00:00:00+02:00",
          "dropoff": "2026-05-24T00:00:00+02:00",
          "vehicle": "CAMPER CABIN DELUXE Ford Nugget Plus - Ford Transit Custom V362",
          "make": "CAMPER CABIN DELUXE",
          "model": "Ford Nugget Plus - Ford Transit Custom V362",
          "distanceKm": 651.9,
          "offerId": "247752"
        },
        {
          "originName": "Champlan",
          "destName": "Frankfurt am Main",
          "pickup": "2026-05-25T00:00:00+02:00",
          "dropoff": "2026-05-27T00:00:00+02:00",
          "vehicle": "COUPLE COTTAGE Weinsberg Signeo C590 - Ford Transit V363",
          "make": "COUPLE COTTAGE",
          "model": "Weinsberg Signeo C590 - Ford Transit V363",
          "distanceKm": 573.3,
          "offerId": "247816"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-22T00:00:00+02:00",
      "endUtc": "2026-05-27T00:00:00+02:00",
      "days": 5.0,
      "routeKm": 1225.0,
      "freeKm": 2000.0,
      "spareKm": 775.0,
      "driveHours": 14.411764705882353,
      "countries": [
        "Germany",
        "France"
      ],
      "appointment": "22 May – 27 May · Marburg → Frankfurt am Main"
    },
    {
      "score": 121.8,
      "route": [
        "Saint-Jean-de-Gonville",
        "Aach"
      ],
      "legs": [
        {
          "originName": "Saint-Jean-de-Gonville",
          "destName": "Aach",
          "pickup": "2026-05-23T00:00:00+02:00",
          "dropoff": "2026-05-24T00:00:00+02:00",
          "vehicle": "SURFER SUITE VW California Ocean",
          "make": "SURFER SUITE",
          "model": "VW California Ocean",
          "distanceKm": 353.4,
          "offerId": "246475"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-23T00:00:00+02:00",
      "endUtc": "2026-05-24T00:00:00+02:00",
      "days": 1.0,
      "routeKm": 353.0,
      "freeKm": 600.0,
      "spareKm": 247.0,
      "driveHours": 4.152941176470589,
      "countries": [
        "France",
        "Germany"
      ],
      "appointment": "23 May – 24 May · Saint-Jean-de-Gonville → Aach"
    },
    {
      "score": 121.7,
      "route": [
        "Florence",
        "Milan"
      ],
      "legs": [
        {
          "originName": "Florence",
          "destName": "Milan",
          "pickup": "2026-05-23T06:00:05+02:00",
          "dropoff": "2026-05-24T06:00:05+02:00",
          "vehicle": "Fiat S 75SL / T 7400 SB or similar",
          "make": "Fiat",
          "model": "S 75SL / T 7400 SB or similar",
          "distanceKm": 345.7,
          "offerId": "247281"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-23T06:00:05+02:00",
      "endUtc": "2026-05-24T06:00:05+02:00",
      "days": 1.0,
      "routeKm": 346.0,
      "freeKm": 480.0,
      "spareKm": 134.0,
      "driveHours": 4.070588235294117,
      "countries": [
        "Italy"
      ],
      "appointment": "23 May – 24 May · Florence → Milan"
    },
    {
      "score": 121.6,
      "route": [
        "Florence",
        "Bergamo"
      ],
      "legs": [
        {
          "originName": "Florence",
          "destName": "Bergamo",
          "pickup": "2026-05-23T06:00:05+02:00",
          "dropoff": "2026-05-24T06:00:05+02:00",
          "vehicle": "Fiat S 75SL / T 7400 SB or similar",
          "make": "Fiat",
          "model": "S 75SL / T 7400 SB or similar",
          "distanceKm": 325.4,
          "offerId": "247276"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-23T06:00:05+02:00",
      "endUtc": "2026-05-24T06:00:05+02:00",
      "days": 1.0,
      "routeKm": 325.0,
      "freeKm": 480.0,
      "spareKm": 155.0,
      "driveHours": 3.823529411764706,
      "countries": [
        "Italy"
      ],
      "appointment": "23 May – 24 May · Florence → Bergamo"
    },
    {
      "score": 121.3,
      "route": [
        "Bologna",
        "Milan"
      ],
      "legs": [
        {
          "originName": "Bologna",
          "destName": "Milan",
          "pickup": "2026-05-23T06:00:05+02:00",
          "dropoff": "2026-05-24T06:00:05+02:00",
          "vehicle": "Fiat S 75SL / T 7400 SB or similar",
          "make": "Fiat",
          "model": "S 75SL / T 7400 SB or similar",
          "distanceKm": 263.8,
          "offerId": "247317"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-23T06:00:05+02:00",
      "endUtc": "2026-05-24T06:00:05+02:00",
      "days": 1.0,
      "routeKm": 264.0,
      "freeKm": 480.0,
      "spareKm": 216.0,
      "driveHours": 3.1058823529411765,
      "countries": [
        "Italy"
      ],
      "appointment": "23 May – 24 May · Bologna → Milan"
    },
    {
      "score": 109.9,
      "route": [
        "Pisa",
        "Essen"
      ],
      "legs": [
        {
          "originName": "Pisa",
          "destName": "Essen",
          "pickup": "2026-05-23T06:00:05+02:00",
          "dropoff": "2026-05-26T06:00:05+02:00",
          "vehicle": "Fiat Ducato",
          "make": "Fiat",
          "model": "Ducato",
          "distanceKm": 1181.8,
          "offerId": "247353"
        }
      ],
      "type": "inbound",
      "homeCity": "Bochum",
      "startUtc": "2026-05-23T06:00:05+02:00",
      "endUtc": "2026-05-26T06:00:05+02:00",
      "days": 3.0,
      "routeKm": 1182.0,
      "freeKm": 1380.0,
      "spareKm": 198.0,
      "driveHours": 13.905882352941177,
      "countries": [
        "Europe",
        "Germany"
      ],
      "appointment": "23 May – 26 May · Pisa → Essen"
    },
    {
      "score": 109.8,
      "route": [
        "Venezia",
        "Essen"
      ],
      "legs": [
        {
          "originName": "Venezia",
          "destName": "Essen",
          "pickup": "2026-05-23T06:00:05+02:00",
          "dropoff": "2026-05-26T06:00:05+02:00",
          "vehicle": "Fiat Ducato",
          "make": "Fiat",
          "model": "Ducato",
          "distanceKm": 1156.1,
          "offerId": "247331"
        }
      ],
      "type": "inbound",
      "homeCity": "Bochum",
      "startUtc": "2026-05-23T06:00:05+02:00",
      "endUtc": "2026-05-26T06:00:05+02:00",
      "days": 3.0,
      "routeKm": 1156.0,
      "freeKm": 1380.0,
      "spareKm": 224.0,
      "driveHours": 13.6,
      "countries": [
        "Italy",
        "Germany"
      ],
      "appointment": "23 May – 26 May · Venezia → Essen"
    },
    {
      "score": 109.3,
      "route": [
        "Berglern",
        "Olbia"
      ],
      "legs": [
        {
          "originName": "Berglern",
          "destName": "Olbia",
          "pickup": "2026-05-23T06:00:05+02:00",
          "dropoff": "2026-05-26T06:00:05+02:00",
          "vehicle": "Fiat Ducato",
          "make": "Fiat",
          "model": "Ducato",
          "distanceKm": 1059.7,
          "offerId": "247360"
        }
      ],
      "type": "oneway",
      "homeCity": "München",
      "startUtc": "2026-05-23T06:00:05+02:00",
      "endUtc": "2026-05-26T06:00:05+02:00",
      "days": 3.0,
      "routeKm": 1060.0,
      "freeKm": 1380.0,
      "spareKm": 320.0,
      "driveHours": 12.470588235294118,
      "countries": [
        "Germany",
        "Europe"
      ],
      "appointment": "23 May – 26 May · Berglern → Olbia"
    },
    {
      "score": 109.0,
      "route": [
        "Nantes",
        "Frankfurt am Main"
      ],
      "legs": [
        {
          "originName": "Nantes",
          "destName": "Frankfurt am Main",
          "pickup": "2026-05-23T06:00:05+02:00",
          "dropoff": "2026-05-26T06:00:05+02:00",
          "vehicle": "Pilote G690 GJ or similar",
          "make": "Pilote",
          "model": "G690 GJ or similar",
          "distanceKm": 994.6,
          "offerId": "247310"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-23T06:00:05+02:00",
      "endUtc": "2026-05-26T06:00:05+02:00",
      "days": 3.0,
      "routeKm": 995.0,
      "freeKm": 1150.0,
      "spareKm": 155.0,
      "driveHours": 11.705882352941176,
      "countries": [
        "France",
        "Germany"
      ],
      "appointment": "23 May – 26 May · Nantes → Frankfurt am Main"
    },
    {
      "score": 108.8,
      "route": [
        "Roma",
        "Berglern"
      ],
      "legs": [
        {
          "originName": "Roma",
          "destName": "Berglern",
          "pickup": "2026-05-23T06:00:05+02:00",
          "dropoff": "2026-05-26T06:00:05+02:00",
          "vehicle": "Volkswagen California",
          "make": "Volkswagen",
          "model": "California",
          "distanceKm": 963.2,
          "offerId": "247363"
        }
      ],
      "type": "inbound",
      "homeCity": "München",
      "startUtc": "2026-05-23T06:00:05+02:00",
      "endUtc": "2026-05-26T06:00:05+02:00",
      "days": 3.0,
      "routeKm": 963.0,
      "freeKm": 1150.0,
      "spareKm": 187.0,
      "driveHours": 11.329411764705883,
      "countries": [
        "Italy",
        "Germany"
      ],
      "appointment": "23 May – 26 May · Roma → Berglern"
    },
    {
      "score": 108.3,
      "route": [
        "Hamburg",
        "Warszawa"
      ],
      "legs": [
        {
          "originName": "Hamburg",
          "destName": "Warszawa",
          "pickup": "2026-05-23T06:00:05+02:00",
          "dropoff": "2026-05-26T06:00:05+02:00",
          "vehicle": "Fiat Ducato",
          "make": "Fiat",
          "model": "Ducato",
          "distanceKm": 851.2,
          "offerId": "247315"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-23T06:00:05+02:00",
      "endUtc": "2026-05-26T06:00:05+02:00",
      "days": 3.0,
      "routeKm": 851.0,
      "freeKm": 1150.0,
      "spareKm": 299.0,
      "driveHours": 10.011764705882353,
      "countries": [
        "Germany",
        "Europe"
      ],
      "appointment": "23 May – 26 May · Hamburg → Warszawa"
    },
    {
      "score": 105.7,
      "route": [
        "Marburg",
        "Castellanza"
      ],
      "legs": [
        {
          "originName": "Marburg",
          "destName": "Castellanza",
          "pickup": "2026-05-22T00:00:00+02:00",
          "dropoff": "2026-05-24T00:00:00+02:00",
          "vehicle": "FAMILY FINCA VW Grand California 600 - VW Crafter 2",
          "make": "FAMILY FINCA",
          "model": "VW Grand California 600 - VW Crafter 2",
          "distanceKm": 740.4,
          "offerId": "246239"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-22T00:00:00+02:00",
      "endUtc": "2026-05-24T00:00:00+02:00",
      "days": 2.0,
      "routeKm": 740.0,
      "freeKm": 1000.0,
      "spareKm": 260.0,
      "driveHours": 8.705882352941176,
      "countries": [
        "Germany",
        "Italy"
      ],
      "appointment": "22 May – 24 May · Marburg → Castellanza"
    },
    {
      "score": 105.3,
      "route": [
        "Marburg",
        "Champlan"
      ],
      "legs": [
        {
          "originName": "Marburg",
          "destName": "Champlan",
          "pickup": "2026-05-22T00:00:00+02:00",
          "dropoff": "2026-05-24T00:00:00+02:00",
          "vehicle": "CAMPER CABIN DELUXE Ford Nugget Plus - Ford Transit Custom V362",
          "make": "CAMPER CABIN DELUXE",
          "model": "Ford Nugget Plus - Ford Transit Custom V362",
          "distanceKm": 651.9,
          "offerId": "247752"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-22T00:00:00+02:00",
      "endUtc": "2026-05-24T00:00:00+02:00",
      "days": 2.0,
      "routeKm": 652.0,
      "freeKm": 1000.0,
      "spareKm": 348.0,
      "driveHours": 7.670588235294118,
      "countries": [
        "Germany",
        "France"
      ],
      "appointment": "22 May – 24 May · Marburg → Champlan"
    },
    {
      "score": 105.2,
      "route": [
        "Florence",
        "Cagliari"
      ],
      "legs": [
        {
          "originName": "Florence",
          "destName": "Cagliari",
          "pickup": "2026-05-23T06:00:05+02:00",
          "dropoff": "2026-05-25T06:00:05+02:00",
          "vehicle": "Fiat Ducato",
          "make": "Fiat",
          "model": "Ducato",
          "distanceKm": 649.4,
          "offerId": "247306"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-23T06:00:05+02:00",
      "endUtc": "2026-05-25T06:00:05+02:00",
      "days": 2.0,
      "routeKm": 649.0,
      "freeKm": 960.0,
      "spareKm": 311.0,
      "driveHours": 7.635294117647059,
      "countries": [
        "Italy",
        "Europe"
      ],
      "appointment": "23 May – 25 May · Florence → Cagliari"
    },
    {
      "score": 105.0,
      "route": [
        "Berglern",
        "Berlin"
      ],
      "legs": [
        {
          "originName": "Berglern",
          "destName": "Berlin",
          "pickup": "2026-05-23T06:00:05+02:00",
          "dropoff": "2026-05-25T06:00:05+02:00",
          "vehicle": "Fiat Ducato",
          "make": "Fiat",
          "model": "Ducato",
          "distanceKm": 598.2,
          "offerId": "247282"
        }
      ],
      "type": "oneway",
      "homeCity": "München",
      "startUtc": "2026-05-23T06:00:05+02:00",
      "endUtc": "2026-05-25T06:00:05+02:00",
      "days": 2.0,
      "routeKm": 598.0,
      "freeKm": 720.0,
      "spareKm": 122.0,
      "driveHours": 7.035294117647059,
      "countries": [
        "Germany"
      ],
      "appointment": "23 May – 25 May · Berglern → Berlin"
    },
    {
      "score": 104.9,
      "route": [
        "Champlan",
        "Frankfurt am Main"
      ],
      "legs": [
        {
          "originName": "Champlan",
          "destName": "Frankfurt am Main",
          "pickup": "2026-05-23T00:00:00+02:00",
          "dropoff": "2026-05-25T00:00:00+02:00",
          "vehicle": "COUPLE COTTAGE Weinsberg Signeo C590 - Ford Transit V363",
          "make": "COUPLE COTTAGE",
          "model": "Weinsberg Signeo C590 - Ford Transit V363",
          "distanceKm": 573.3,
          "offerId": "247816"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-23T00:00:00+02:00",
      "endUtc": "2026-05-25T00:00:00+02:00",
      "days": 2.0,
      "routeKm": 573.0,
      "freeKm": 1000.0,
      "spareKm": 427.0,
      "driveHours": 6.741176470588235,
      "countries": [
        "France",
        "Germany"
      ],
      "appointment": "23 May – 25 May · Champlan → Frankfurt am Main"
    },
    {
      "score": 104.7,
      "route": [
        "Essen",
        "Berlin"
      ],
      "legs": [
        {
          "originName": "Essen",
          "destName": "Berlin",
          "pickup": "2026-05-23T06:00:05+02:00",
          "dropoff": "2026-05-25T06:00:05+02:00",
          "vehicle": "Fiat Ducato",
          "make": "Fiat",
          "model": "Ducato",
          "distanceKm": 539.2,
          "offerId": "247272"
        }
      ],
      "type": "oneway",
      "homeCity": "Bochum",
      "startUtc": "2026-05-23T06:00:05+02:00",
      "endUtc": "2026-05-25T06:00:05+02:00",
      "days": 2.0,
      "routeKm": 539.0,
      "freeKm": 720.0,
      "spareKm": 181.0,
      "driveHours": 6.341176470588235,
      "countries": [
        "Germany"
      ],
      "appointment": "23 May – 25 May · Essen → Berlin"
    },
    {
      "score": 104.1,
      "route": [
        "Gersthofen",
        "Leipzig"
      ],
      "legs": [
        {
          "originName": "Gersthofen",
          "destName": "Leipzig",
          "pickup": "2026-05-22T00:00:00+02:00",
          "dropoff": "2026-05-24T00:00:00+02:00",
          "vehicle": "COZY COTTAGE Knaus Van TI Plus 650 MEG Platinum Selection - VW Crafter 2",
          "make": "COZY COTTAGE",
          "model": "Knaus Van TI Plus 650 MEG Platinum Selection - VW Crafter 2",
          "distanceKm": 419.4,
          "offerId": "247229"
        }
      ],
      "type": "oneway",
      "homeCity": "München",
      "startUtc": "2026-05-22T00:00:00+02:00",
      "endUtc": "2026-05-24T00:00:00+02:00",
      "days": 2.0,
      "routeKm": 419.0,
      "freeKm": 1000.0,
      "spareKm": 581.0,
      "driveHours": 4.929411764705883,
      "countries": [
        "Germany"
      ],
      "appointment": "22 May – 24 May · Gersthofen → Leipzig"
    },
    {
      "score": 102.0,
      "route": [
        "Florence",
        "Olbia"
      ],
      "legs": [
        {
          "originName": "Florence",
          "destName": "Olbia",
          "pickup": "2026-05-23T06:00:05+02:00",
          "dropoff": "2026-05-24T06:00:05+02:00",
          "vehicle": "Fiat Ducato",
          "make": "Fiat",
          "model": "Ducato",
          "distanceKm": 396.0,
          "offerId": "247275"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-23T06:00:05+02:00",
      "endUtc": "2026-05-24T06:00:05+02:00",
      "days": 1.0,
      "routeKm": 396.0,
      "freeKm": 480.0,
      "spareKm": 84.0,
      "driveHours": 4.658823529411765,
      "countries": [
        "Italy",
        "Europe"
      ],
      "appointment": "23 May – 24 May · Florence → Olbia"
    },
    {
      "score": 101.7,
      "route": [
        "Pisa",
        "Olbia"
      ],
      "legs": [
        {
          "originName": "Pisa",
          "destName": "Olbia",
          "pickup": "2026-05-23T06:00:05+02:00",
          "dropoff": "2026-05-24T06:00:05+02:00",
          "vehicle": "Volkswagen California",
          "make": "Volkswagen",
          "model": "California",
          "distanceKm": 339.4,
          "offerId": "247270"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-23T06:00:05+02:00",
      "endUtc": "2026-05-24T06:00:05+02:00",
      "days": 1.0,
      "routeKm": 339.0,
      "freeKm": 480.0,
      "spareKm": 141.0,
      "driveHours": 3.988235294117647,
      "countries": [
        "Europe"
      ],
      "appointment": "23 May – 24 May · Pisa → Olbia"
    },
    {
      "score": 101.5,
      "route": [
        "Bamberg",
        "Rosenheim"
      ],
      "legs": [
        {
          "originName": "Bamberg",
          "destName": "Rosenheim",
          "pickup": "2026-05-22T00:00:00+02:00",
          "dropoff": "2026-05-23T00:00:00+02:00",
          "vehicle": "CITRO C3 AIRCROSS OFF BE AUT",
          "make": "CITRO",
          "model": "C3 AIRCROSS OFF BE AUT",
          "distanceKm": 305.5,
          "offerId": "247820"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-22T00:00:00+02:00",
      "endUtc": "2026-05-23T00:00:00+02:00",
      "days": 1.0,
      "routeKm": 306.0,
      "freeKm": 400.0,
      "spareKm": 94.0,
      "driveHours": 3.6,
      "countries": [
        "Europe"
      ],
      "appointment": "22 May – 23 May · Bamberg → Rosenheim"
    },
    {
      "score": 101.5,
      "route": [
        "Bayreuth",
        "Rosenheim"
      ],
      "legs": [
        {
          "originName": "Bayreuth",
          "destName": "Rosenheim",
          "pickup": "2026-05-22T00:00:00+02:00",
          "dropoff": "2026-05-23T00:00:00+02:00",
          "vehicle": "MB CLE180 CAB BE AUT",
          "make": "MB",
          "model": "CLE180 CAB BE AUT",
          "distanceKm": 302.5,
          "offerId": "247818"
        }
      ],
      "type": "oneway",
      "startUtc": "2026-05-22T00:00:00+02:00",
      "endUtc": "2026-05-23T00:00:00+02:00",
      "days": 1.0,
      "routeKm": 302.0,
      "freeKm": 400.0,
      "spareKm": 98.0,
      "driveHours": 3.552941176470588,
      "countries": [
        "Europe"
      ],
      "appointment": "22 May – 23 May · Bayreuth → Rosenheim"
    }
  ]
} as const;
